/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2PublicVifDynamic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2PublicVifDynamic{}

// ManaV2PublicVifDynamic struct for ManaV2PublicVifDynamic
type ManaV2PublicVifDynamic struct {
	Entries []string `json:"entries,omitempty"`
}

// NewManaV2PublicVifDynamic instantiates a new ManaV2PublicVifDynamic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2PublicVifDynamic() *ManaV2PublicVifDynamic {
	this := ManaV2PublicVifDynamic{}
	return &this
}

// NewManaV2PublicVifDynamicWithDefaults instantiates a new ManaV2PublicVifDynamic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2PublicVifDynamicWithDefaults() *ManaV2PublicVifDynamic {
	this := ManaV2PublicVifDynamic{}
	return &this
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *ManaV2PublicVifDynamic) GetEntries() []string {
	if o == nil || IsNil(o.Entries) {
		var ret []string
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifDynamic) GetEntriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *ManaV2PublicVifDynamic) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []string and assigns it to the Entries field.
func (o *ManaV2PublicVifDynamic) SetEntries(v []string) {
	o.Entries = v
}

func (o ManaV2PublicVifDynamic) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2PublicVifDynamic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	return toSerialize, nil
}

type NullableManaV2PublicVifDynamic struct {
	value *ManaV2PublicVifDynamic
	isSet bool
}

func (v NullableManaV2PublicVifDynamic) Get() *ManaV2PublicVifDynamic {
	return v.value
}

func (v *NullableManaV2PublicVifDynamic) Set(val *ManaV2PublicVifDynamic) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2PublicVifDynamic) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2PublicVifDynamic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2PublicVifDynamic(val *ManaV2PublicVifDynamic) *NullableManaV2PublicVifDynamic {
	return &NullableManaV2PublicVifDynamic{value: val, isSet: true}
}

func (v NullableManaV2PublicVifDynamic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2PublicVifDynamic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


