/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1GlobalContentFiltersPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1GlobalContentFiltersPostResponse{}

// V1GlobalContentFiltersPostResponse struct for V1GlobalContentFiltersPostResponse
type V1GlobalContentFiltersPostResponse struct {
	// Server-assigned ID for the newly created global content filter.
	GlobalContentFilterId *int64 `json:"globalContentFilterId,omitempty"`
}

// NewV1GlobalContentFiltersPostResponse instantiates a new V1GlobalContentFiltersPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1GlobalContentFiltersPostResponse() *V1GlobalContentFiltersPostResponse {
	this := V1GlobalContentFiltersPostResponse{}
	return &this
}

// NewV1GlobalContentFiltersPostResponseWithDefaults instantiates a new V1GlobalContentFiltersPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1GlobalContentFiltersPostResponseWithDefaults() *V1GlobalContentFiltersPostResponse {
	this := V1GlobalContentFiltersPostResponse{}
	return &this
}

// GetGlobalContentFilterId returns the GlobalContentFilterId field value if set, zero value otherwise.
func (o *V1GlobalContentFiltersPostResponse) GetGlobalContentFilterId() int64 {
	if o == nil || IsNil(o.GlobalContentFilterId) {
		var ret int64
		return ret
	}
	return *o.GlobalContentFilterId
}

// GetGlobalContentFilterIdOk returns a tuple with the GlobalContentFilterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1GlobalContentFiltersPostResponse) GetGlobalContentFilterIdOk() (*int64, bool) {
	if o == nil || IsNil(o.GlobalContentFilterId) {
		return nil, false
	}
	return o.GlobalContentFilterId, true
}

// HasGlobalContentFilterId returns a boolean if a field has been set.
func (o *V1GlobalContentFiltersPostResponse) HasGlobalContentFilterId() bool {
	if o != nil && !IsNil(o.GlobalContentFilterId) {
		return true
	}

	return false
}

// SetGlobalContentFilterId gets a reference to the given int64 and assigns it to the GlobalContentFilterId field.
func (o *V1GlobalContentFiltersPostResponse) SetGlobalContentFilterId(v int64) {
	o.GlobalContentFilterId = &v
}

func (o V1GlobalContentFiltersPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1GlobalContentFiltersPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GlobalContentFilterId) {
		toSerialize["globalContentFilterId"] = o.GlobalContentFilterId
	}
	return toSerialize, nil
}

type NullableV1GlobalContentFiltersPostResponse struct {
	value *V1GlobalContentFiltersPostResponse
	isSet bool
}

func (v NullableV1GlobalContentFiltersPostResponse) Get() *V1GlobalContentFiltersPostResponse {
	return v.value
}

func (v *NullableV1GlobalContentFiltersPostResponse) Set(val *V1GlobalContentFiltersPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1GlobalContentFiltersPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1GlobalContentFiltersPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1GlobalContentFiltersPostResponse(val *V1GlobalContentFiltersPostResponse) *NullableV1GlobalContentFiltersPostResponse {
	return &NullableV1GlobalContentFiltersPostResponse{value: val, isSet: true}
}

func (v NullableV1GlobalContentFiltersPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1GlobalContentFiltersPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


