/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2LanSegmentSitesMap type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2LanSegmentSitesMap{}

// ManaV2LanSegmentSitesMap struct for ManaV2LanSegmentSitesMap
type ManaV2LanSegmentSitesMap struct {
	SiteIds *map[string]ManaV2SiteLanSegmentDeviceBuckets `json:"siteIds,omitempty"`
	SiteListIds *map[string]ManaV2SiteLanSegmentDeviceBuckets `json:"siteListIds,omitempty"`
}

// NewManaV2LanSegmentSitesMap instantiates a new ManaV2LanSegmentSitesMap object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2LanSegmentSitesMap() *ManaV2LanSegmentSitesMap {
	this := ManaV2LanSegmentSitesMap{}
	return &this
}

// NewManaV2LanSegmentSitesMapWithDefaults instantiates a new ManaV2LanSegmentSitesMap object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2LanSegmentSitesMapWithDefaults() *ManaV2LanSegmentSitesMap {
	this := ManaV2LanSegmentSitesMap{}
	return &this
}

// GetSiteIds returns the SiteIds field value if set, zero value otherwise.
func (o *ManaV2LanSegmentSitesMap) GetSiteIds() map[string]ManaV2SiteLanSegmentDeviceBuckets {
	if o == nil || IsNil(o.SiteIds) {
		var ret map[string]ManaV2SiteLanSegmentDeviceBuckets
		return ret
	}
	return *o.SiteIds
}

// GetSiteIdsOk returns a tuple with the SiteIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2LanSegmentSitesMap) GetSiteIdsOk() (*map[string]ManaV2SiteLanSegmentDeviceBuckets, bool) {
	if o == nil || IsNil(o.SiteIds) {
		return nil, false
	}
	return o.SiteIds, true
}

// HasSiteIds returns a boolean if a field has been set.
func (o *ManaV2LanSegmentSitesMap) HasSiteIds() bool {
	if o != nil && !IsNil(o.SiteIds) {
		return true
	}

	return false
}

// SetSiteIds gets a reference to the given map[string]ManaV2SiteLanSegmentDeviceBuckets and assigns it to the SiteIds field.
func (o *ManaV2LanSegmentSitesMap) SetSiteIds(v map[string]ManaV2SiteLanSegmentDeviceBuckets) {
	o.SiteIds = &v
}

// GetSiteListIds returns the SiteListIds field value if set, zero value otherwise.
func (o *ManaV2LanSegmentSitesMap) GetSiteListIds() map[string]ManaV2SiteLanSegmentDeviceBuckets {
	if o == nil || IsNil(o.SiteListIds) {
		var ret map[string]ManaV2SiteLanSegmentDeviceBuckets
		return ret
	}
	return *o.SiteListIds
}

// GetSiteListIdsOk returns a tuple with the SiteListIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2LanSegmentSitesMap) GetSiteListIdsOk() (*map[string]ManaV2SiteLanSegmentDeviceBuckets, bool) {
	if o == nil || IsNil(o.SiteListIds) {
		return nil, false
	}
	return o.SiteListIds, true
}

// HasSiteListIds returns a boolean if a field has been set.
func (o *ManaV2LanSegmentSitesMap) HasSiteListIds() bool {
	if o != nil && !IsNil(o.SiteListIds) {
		return true
	}

	return false
}

// SetSiteListIds gets a reference to the given map[string]ManaV2SiteLanSegmentDeviceBuckets and assigns it to the SiteListIds field.
func (o *ManaV2LanSegmentSitesMap) SetSiteListIds(v map[string]ManaV2SiteLanSegmentDeviceBuckets) {
	o.SiteListIds = &v
}

func (o ManaV2LanSegmentSitesMap) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2LanSegmentSitesMap) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SiteIds) {
		toSerialize["siteIds"] = o.SiteIds
	}
	if !IsNil(o.SiteListIds) {
		toSerialize["siteListIds"] = o.SiteListIds
	}
	return toSerialize, nil
}

type NullableManaV2LanSegmentSitesMap struct {
	value *ManaV2LanSegmentSitesMap
	isSet bool
}

func (v NullableManaV2LanSegmentSitesMap) Get() *ManaV2LanSegmentSitesMap {
	return v.value
}

func (v *NullableManaV2LanSegmentSitesMap) Set(val *ManaV2LanSegmentSitesMap) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2LanSegmentSitesMap) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2LanSegmentSitesMap) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2LanSegmentSitesMap(val *ManaV2LanSegmentSitesMap) *NullableManaV2LanSegmentSitesMap {
	return &NullableManaV2LanSegmentSitesMap{value: val, isSet: true}
}

func (v NullableManaV2LanSegmentSitesMap) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2LanSegmentSitesMap) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


