/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetB2bCustomersIdMatchesSummaryGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bCustomersIdMatchesSummaryGetResponse{}

// V1ExtranetB2bCustomersIdMatchesSummaryGetResponse struct for V1ExtranetB2bCustomersIdMatchesSummaryGetResponse
type V1ExtranetB2bCustomersIdMatchesSummaryGetResponse struct {
	Matches []ManaV2ExtranetServiceCustomerMatchSummary `json:"matches,omitempty"`
}

// NewV1ExtranetB2bCustomersIdMatchesSummaryGetResponse instantiates a new V1ExtranetB2bCustomersIdMatchesSummaryGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bCustomersIdMatchesSummaryGetResponse() *V1ExtranetB2bCustomersIdMatchesSummaryGetResponse {
	this := V1ExtranetB2bCustomersIdMatchesSummaryGetResponse{}
	return &this
}

// NewV1ExtranetB2bCustomersIdMatchesSummaryGetResponseWithDefaults instantiates a new V1ExtranetB2bCustomersIdMatchesSummaryGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bCustomersIdMatchesSummaryGetResponseWithDefaults() *V1ExtranetB2bCustomersIdMatchesSummaryGetResponse {
	this := V1ExtranetB2bCustomersIdMatchesSummaryGetResponse{}
	return &this
}

// GetMatches returns the Matches field value if set, zero value otherwise.
func (o *V1ExtranetB2bCustomersIdMatchesSummaryGetResponse) GetMatches() []ManaV2ExtranetServiceCustomerMatchSummary {
	if o == nil || IsNil(o.Matches) {
		var ret []ManaV2ExtranetServiceCustomerMatchSummary
		return ret
	}
	return o.Matches
}

// GetMatchesOk returns a tuple with the Matches field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bCustomersIdMatchesSummaryGetResponse) GetMatchesOk() ([]ManaV2ExtranetServiceCustomerMatchSummary, bool) {
	if o == nil || IsNil(o.Matches) {
		return nil, false
	}
	return o.Matches, true
}

// HasMatches returns a boolean if a field has been set.
func (o *V1ExtranetB2bCustomersIdMatchesSummaryGetResponse) HasMatches() bool {
	if o != nil && !IsNil(o.Matches) {
		return true
	}

	return false
}

// SetMatches gets a reference to the given []ManaV2ExtranetServiceCustomerMatchSummary and assigns it to the Matches field.
func (o *V1ExtranetB2bCustomersIdMatchesSummaryGetResponse) SetMatches(v []ManaV2ExtranetServiceCustomerMatchSummary) {
	o.Matches = v
}

func (o V1ExtranetB2bCustomersIdMatchesSummaryGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bCustomersIdMatchesSummaryGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Matches) {
		toSerialize["matches"] = o.Matches
	}
	return toSerialize, nil
}

type NullableV1ExtranetB2bCustomersIdMatchesSummaryGetResponse struct {
	value *V1ExtranetB2bCustomersIdMatchesSummaryGetResponse
	isSet bool
}

func (v NullableV1ExtranetB2bCustomersIdMatchesSummaryGetResponse) Get() *V1ExtranetB2bCustomersIdMatchesSummaryGetResponse {
	return v.value
}

func (v *NullableV1ExtranetB2bCustomersIdMatchesSummaryGetResponse) Set(val *V1ExtranetB2bCustomersIdMatchesSummaryGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bCustomersIdMatchesSummaryGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bCustomersIdMatchesSummaryGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bCustomersIdMatchesSummaryGetResponse(val *V1ExtranetB2bCustomersIdMatchesSummaryGetResponse) *NullableV1ExtranetB2bCustomersIdMatchesSummaryGetResponse {
	return &NullableV1ExtranetB2bCustomersIdMatchesSummaryGetResponse{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bCustomersIdMatchesSummaryGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bCustomersIdMatchesSummaryGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


