/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1GlobalContentFiltersGetResponseRowSiteEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1GlobalContentFiltersGetResponseRowSiteEntry{}

// V1GlobalContentFiltersGetResponseRowSiteEntry struct for V1GlobalContentFiltersGetResponseRowSiteEntry
type V1GlobalContentFiltersGetResponseRowSiteEntry struct {
	// Display name of a site included in this filter's global or site-list-bounded scope.
	SiteName *string `json:"siteName,omitempty"`
}

// NewV1GlobalContentFiltersGetResponseRowSiteEntry instantiates a new V1GlobalContentFiltersGetResponseRowSiteEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1GlobalContentFiltersGetResponseRowSiteEntry() *V1GlobalContentFiltersGetResponseRowSiteEntry {
	this := V1GlobalContentFiltersGetResponseRowSiteEntry{}
	return &this
}

// NewV1GlobalContentFiltersGetResponseRowSiteEntryWithDefaults instantiates a new V1GlobalContentFiltersGetResponseRowSiteEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1GlobalContentFiltersGetResponseRowSiteEntryWithDefaults() *V1GlobalContentFiltersGetResponseRowSiteEntry {
	this := V1GlobalContentFiltersGetResponseRowSiteEntry{}
	return &this
}

// GetSiteName returns the SiteName field value if set, zero value otherwise.
func (o *V1GlobalContentFiltersGetResponseRowSiteEntry) GetSiteName() string {
	if o == nil || IsNil(o.SiteName) {
		var ret string
		return ret
	}
	return *o.SiteName
}

// GetSiteNameOk returns a tuple with the SiteName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1GlobalContentFiltersGetResponseRowSiteEntry) GetSiteNameOk() (*string, bool) {
	if o == nil || IsNil(o.SiteName) {
		return nil, false
	}
	return o.SiteName, true
}

// HasSiteName returns a boolean if a field has been set.
func (o *V1GlobalContentFiltersGetResponseRowSiteEntry) HasSiteName() bool {
	if o != nil && !IsNil(o.SiteName) {
		return true
	}

	return false
}

// SetSiteName gets a reference to the given string and assigns it to the SiteName field.
func (o *V1GlobalContentFiltersGetResponseRowSiteEntry) SetSiteName(v string) {
	o.SiteName = &v
}

func (o V1GlobalContentFiltersGetResponseRowSiteEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1GlobalContentFiltersGetResponseRowSiteEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SiteName) {
		toSerialize["siteName"] = o.SiteName
	}
	return toSerialize, nil
}

type NullableV1GlobalContentFiltersGetResponseRowSiteEntry struct {
	value *V1GlobalContentFiltersGetResponseRowSiteEntry
	isSet bool
}

func (v NullableV1GlobalContentFiltersGetResponseRowSiteEntry) Get() *V1GlobalContentFiltersGetResponseRowSiteEntry {
	return v.value
}

func (v *NullableV1GlobalContentFiltersGetResponseRowSiteEntry) Set(val *V1GlobalContentFiltersGetResponseRowSiteEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableV1GlobalContentFiltersGetResponseRowSiteEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableV1GlobalContentFiltersGetResponseRowSiteEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1GlobalContentFiltersGetResponseRowSiteEntry(val *V1GlobalContentFiltersGetResponseRowSiteEntry) *NullableV1GlobalContentFiltersGetResponseRowSiteEntry {
	return &NullableV1GlobalContentFiltersGetResponseRowSiteEntry{value: val, isSet: true}
}

func (v NullableV1GlobalContentFiltersGetResponseRowSiteEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1GlobalContentFiltersGetResponseRowSiteEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


