/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1RegionsRegionIdGatewaysGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1RegionsRegionIdGatewaysGetResponse{}

// V1RegionsRegionIdGatewaysGetResponse struct for V1RegionsRegionIdGatewaysGetResponse
type V1RegionsRegionIdGatewaysGetResponse struct {
	Gateways []V1RegionsRegionIdGatewaysGetResponseGateway `json:"gateways,omitempty"`
}

// NewV1RegionsRegionIdGatewaysGetResponse instantiates a new V1RegionsRegionIdGatewaysGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1RegionsRegionIdGatewaysGetResponse() *V1RegionsRegionIdGatewaysGetResponse {
	this := V1RegionsRegionIdGatewaysGetResponse{}
	return &this
}

// NewV1RegionsRegionIdGatewaysGetResponseWithDefaults instantiates a new V1RegionsRegionIdGatewaysGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1RegionsRegionIdGatewaysGetResponseWithDefaults() *V1RegionsRegionIdGatewaysGetResponse {
	this := V1RegionsRegionIdGatewaysGetResponse{}
	return &this
}

// GetGateways returns the Gateways field value if set, zero value otherwise.
func (o *V1RegionsRegionIdGatewaysGetResponse) GetGateways() []V1RegionsRegionIdGatewaysGetResponseGateway {
	if o == nil || IsNil(o.Gateways) {
		var ret []V1RegionsRegionIdGatewaysGetResponseGateway
		return ret
	}
	return o.Gateways
}

// GetGatewaysOk returns a tuple with the Gateways field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1RegionsRegionIdGatewaysGetResponse) GetGatewaysOk() ([]V1RegionsRegionIdGatewaysGetResponseGateway, bool) {
	if o == nil || IsNil(o.Gateways) {
		return nil, false
	}
	return o.Gateways, true
}

// HasGateways returns a boolean if a field has been set.
func (o *V1RegionsRegionIdGatewaysGetResponse) HasGateways() bool {
	if o != nil && !IsNil(o.Gateways) {
		return true
	}

	return false
}

// SetGateways gets a reference to the given []V1RegionsRegionIdGatewaysGetResponseGateway and assigns it to the Gateways field.
func (o *V1RegionsRegionIdGatewaysGetResponse) SetGateways(v []V1RegionsRegionIdGatewaysGetResponseGateway) {
	o.Gateways = v
}

func (o V1RegionsRegionIdGatewaysGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1RegionsRegionIdGatewaysGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Gateways) {
		toSerialize["gateways"] = o.Gateways
	}
	return toSerialize, nil
}

type NullableV1RegionsRegionIdGatewaysGetResponse struct {
	value *V1RegionsRegionIdGatewaysGetResponse
	isSet bool
}

func (v NullableV1RegionsRegionIdGatewaysGetResponse) Get() *V1RegionsRegionIdGatewaysGetResponse {
	return v.value
}

func (v *NullableV1RegionsRegionIdGatewaysGetResponse) Set(val *V1RegionsRegionIdGatewaysGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1RegionsRegionIdGatewaysGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1RegionsRegionIdGatewaysGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1RegionsRegionIdGatewaysGetResponse(val *V1RegionsRegionIdGatewaysGetResponse) *NullableV1RegionsRegionIdGatewaysGetResponse {
	return &NullableV1RegionsRegionIdGatewaysGetResponse{value: val, isSet: true}
}

func (v NullableV1RegionsRegionIdGatewaysGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1RegionsRegionIdGatewaysGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


