/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2ExtranetServiceCustomerMatchSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2ExtranetServiceCustomerMatchSummary{}

// ManaV2ExtranetServiceCustomerMatchSummary struct for ManaV2ExtranetServiceCustomerMatchSummary
type ManaV2ExtranetServiceCustomerMatchSummary struct {
	Id *int64 `json:"id,omitempty"`
	LanSegment *int64 `json:"lanSegment,omitempty"`
	MatchedCustomers *int32 `json:"matchedCustomers,omitempty"`
	Name *string `json:"name,omitempty"`
	ServiceType *string `json:"serviceType,omitempty"`
	Status *string `json:"status,omitempty"`
	UpdatedAt *GoogleProtobufTimestamp `json:"updatedAt,omitempty"`
}

// NewManaV2ExtranetServiceCustomerMatchSummary instantiates a new ManaV2ExtranetServiceCustomerMatchSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2ExtranetServiceCustomerMatchSummary() *ManaV2ExtranetServiceCustomerMatchSummary {
	this := ManaV2ExtranetServiceCustomerMatchSummary{}
	return &this
}

// NewManaV2ExtranetServiceCustomerMatchSummaryWithDefaults instantiates a new ManaV2ExtranetServiceCustomerMatchSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2ExtranetServiceCustomerMatchSummaryWithDefaults() *ManaV2ExtranetServiceCustomerMatchSummary {
	this := ManaV2ExtranetServiceCustomerMatchSummary{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) SetId(v int64) {
	o.Id = &v
}

// GetLanSegment returns the LanSegment field value if set, zero value otherwise.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) GetLanSegment() int64 {
	if o == nil || IsNil(o.LanSegment) {
		var ret int64
		return ret
	}
	return *o.LanSegment
}

// GetLanSegmentOk returns a tuple with the LanSegment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) GetLanSegmentOk() (*int64, bool) {
	if o == nil || IsNil(o.LanSegment) {
		return nil, false
	}
	return o.LanSegment, true
}

// HasLanSegment returns a boolean if a field has been set.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) HasLanSegment() bool {
	if o != nil && !IsNil(o.LanSegment) {
		return true
	}

	return false
}

// SetLanSegment gets a reference to the given int64 and assigns it to the LanSegment field.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) SetLanSegment(v int64) {
	o.LanSegment = &v
}

// GetMatchedCustomers returns the MatchedCustomers field value if set, zero value otherwise.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) GetMatchedCustomers() int32 {
	if o == nil || IsNil(o.MatchedCustomers) {
		var ret int32
		return ret
	}
	return *o.MatchedCustomers
}

// GetMatchedCustomersOk returns a tuple with the MatchedCustomers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) GetMatchedCustomersOk() (*int32, bool) {
	if o == nil || IsNil(o.MatchedCustomers) {
		return nil, false
	}
	return o.MatchedCustomers, true
}

// HasMatchedCustomers returns a boolean if a field has been set.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) HasMatchedCustomers() bool {
	if o != nil && !IsNil(o.MatchedCustomers) {
		return true
	}

	return false
}

// SetMatchedCustomers gets a reference to the given int32 and assigns it to the MatchedCustomers field.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) SetMatchedCustomers(v int32) {
	o.MatchedCustomers = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) SetName(v string) {
	o.Name = &v
}

// GetServiceType returns the ServiceType field value if set, zero value otherwise.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) GetServiceType() string {
	if o == nil || IsNil(o.ServiceType) {
		var ret string
		return ret
	}
	return *o.ServiceType
}

// GetServiceTypeOk returns a tuple with the ServiceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) GetServiceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceType) {
		return nil, false
	}
	return o.ServiceType, true
}

// HasServiceType returns a boolean if a field has been set.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) HasServiceType() bool {
	if o != nil && !IsNil(o.ServiceType) {
		return true
	}

	return false
}

// SetServiceType gets a reference to the given string and assigns it to the ServiceType field.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) SetServiceType(v string) {
	o.ServiceType = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) SetStatus(v string) {
	o.Status = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) GetUpdatedAt() GoogleProtobufTimestamp {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret GoogleProtobufTimestamp
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) GetUpdatedAtOk() (*GoogleProtobufTimestamp, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given GoogleProtobufTimestamp and assigns it to the UpdatedAt field.
func (o *ManaV2ExtranetServiceCustomerMatchSummary) SetUpdatedAt(v GoogleProtobufTimestamp) {
	o.UpdatedAt = &v
}

func (o ManaV2ExtranetServiceCustomerMatchSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2ExtranetServiceCustomerMatchSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LanSegment) {
		toSerialize["lanSegment"] = o.LanSegment
	}
	if !IsNil(o.MatchedCustomers) {
		toSerialize["matchedCustomers"] = o.MatchedCustomers
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ServiceType) {
		toSerialize["serviceType"] = o.ServiceType
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableManaV2ExtranetServiceCustomerMatchSummary struct {
	value *ManaV2ExtranetServiceCustomerMatchSummary
	isSet bool
}

func (v NullableManaV2ExtranetServiceCustomerMatchSummary) Get() *ManaV2ExtranetServiceCustomerMatchSummary {
	return v.value
}

func (v *NullableManaV2ExtranetServiceCustomerMatchSummary) Set(val *ManaV2ExtranetServiceCustomerMatchSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2ExtranetServiceCustomerMatchSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2ExtranetServiceCustomerMatchSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2ExtranetServiceCustomerMatchSummary(val *ManaV2ExtranetServiceCustomerMatchSummary) *NullableManaV2ExtranetServiceCustomerMatchSummary {
	return &NullableManaV2ExtranetServiceCustomerMatchSummary{value: val, isSet: true}
}

func (v NullableManaV2ExtranetServiceCustomerMatchSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2ExtranetServiceCustomerMatchSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


