/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1ExtranetB2bCustomersPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bCustomersPostRequest{}

// V1ExtranetB2bCustomersPostRequest struct for V1ExtranetB2bCustomersPostRequest
type V1ExtranetB2bCustomersPostRequest struct {
	Invite ManaV2ExtranetServiceCustomerInvite `json:"invite"`
	// Partner display name (required)
	Name string `json:"name"`
	// Graphiant peer vs guest (non-Graphiant) partner (required)
	Type string `json:"type"`
}

type _V1ExtranetB2bCustomersPostRequest V1ExtranetB2bCustomersPostRequest

// NewV1ExtranetB2bCustomersPostRequest instantiates a new V1ExtranetB2bCustomersPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bCustomersPostRequest(invite ManaV2ExtranetServiceCustomerInvite, name string, type_ string) *V1ExtranetB2bCustomersPostRequest {
	this := V1ExtranetB2bCustomersPostRequest{}
	this.Invite = invite
	this.Name = name
	this.Type = type_
	return &this
}

// NewV1ExtranetB2bCustomersPostRequestWithDefaults instantiates a new V1ExtranetB2bCustomersPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bCustomersPostRequestWithDefaults() *V1ExtranetB2bCustomersPostRequest {
	this := V1ExtranetB2bCustomersPostRequest{}
	return &this
}

// GetInvite returns the Invite field value
func (o *V1ExtranetB2bCustomersPostRequest) GetInvite() ManaV2ExtranetServiceCustomerInvite {
	if o == nil {
		var ret ManaV2ExtranetServiceCustomerInvite
		return ret
	}

	return o.Invite
}

// GetInviteOk returns a tuple with the Invite field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bCustomersPostRequest) GetInviteOk() (*ManaV2ExtranetServiceCustomerInvite, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Invite, true
}

// SetInvite sets field value
func (o *V1ExtranetB2bCustomersPostRequest) SetInvite(v ManaV2ExtranetServiceCustomerInvite) {
	o.Invite = v
}

// GetName returns the Name field value
func (o *V1ExtranetB2bCustomersPostRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bCustomersPostRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V1ExtranetB2bCustomersPostRequest) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *V1ExtranetB2bCustomersPostRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bCustomersPostRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *V1ExtranetB2bCustomersPostRequest) SetType(v string) {
	o.Type = v
}

func (o V1ExtranetB2bCustomersPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bCustomersPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["invite"] = o.Invite
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *V1ExtranetB2bCustomersPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"invite",
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1ExtranetB2bCustomersPostRequest := _V1ExtranetB2bCustomersPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1ExtranetB2bCustomersPostRequest)

	if err != nil {
		return err
	}

	*o = V1ExtranetB2bCustomersPostRequest(varV1ExtranetB2bCustomersPostRequest)

	return err
}

type NullableV1ExtranetB2bCustomersPostRequest struct {
	value *V1ExtranetB2bCustomersPostRequest
	isSet bool
}

func (v NullableV1ExtranetB2bCustomersPostRequest) Get() *V1ExtranetB2bCustomersPostRequest {
	return v.value
}

func (v *NullableV1ExtranetB2bCustomersPostRequest) Set(val *V1ExtranetB2bCustomersPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bCustomersPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bCustomersPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bCustomersPostRequest(val *V1ExtranetB2bCustomersPostRequest) *NullableV1ExtranetB2bCustomersPostRequest {
	return &NullableV1ExtranetB2bCustomersPostRequest{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bCustomersPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bCustomersPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


