/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1PvifSummaryGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1PvifSummaryGetResponse{}

// V1PvifSummaryGetResponse struct for V1PvifSummaryGetResponse
type V1PvifSummaryGetResponse struct {
	Summary []ManaV2PublicVifSummary `json:"summary,omitempty"`
}

// NewV1PvifSummaryGetResponse instantiates a new V1PvifSummaryGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1PvifSummaryGetResponse() *V1PvifSummaryGetResponse {
	this := V1PvifSummaryGetResponse{}
	return &this
}

// NewV1PvifSummaryGetResponseWithDefaults instantiates a new V1PvifSummaryGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1PvifSummaryGetResponseWithDefaults() *V1PvifSummaryGetResponse {
	this := V1PvifSummaryGetResponse{}
	return &this
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *V1PvifSummaryGetResponse) GetSummary() []ManaV2PublicVifSummary {
	if o == nil || IsNil(o.Summary) {
		var ret []ManaV2PublicVifSummary
		return ret
	}
	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1PvifSummaryGetResponse) GetSummaryOk() ([]ManaV2PublicVifSummary, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *V1PvifSummaryGetResponse) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given []ManaV2PublicVifSummary and assigns it to the Summary field.
func (o *V1PvifSummaryGetResponse) SetSummary(v []ManaV2PublicVifSummary) {
	o.Summary = v
}

func (o V1PvifSummaryGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1PvifSummaryGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	return toSerialize, nil
}

type NullableV1PvifSummaryGetResponse struct {
	value *V1PvifSummaryGetResponse
	isSet bool
}

func (v NullableV1PvifSummaryGetResponse) Get() *V1PvifSummaryGetResponse {
	return v.value
}

func (v *NullableV1PvifSummaryGetResponse) Set(val *V1PvifSummaryGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1PvifSummaryGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1PvifSummaryGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1PvifSummaryGetResponse(val *V1PvifSummaryGetResponse) *NullableV1PvifSummaryGetResponse {
	return &NullableV1PvifSummaryGetResponse{value: val, isSet: true}
}

func (v NullableV1PvifSummaryGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1PvifSummaryGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


