/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1EnterpriseConfigurationGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1EnterpriseConfigurationGetResponse{}

// V1EnterpriseConfigurationGetResponse struct for V1EnterpriseConfigurationGetResponse
type V1EnterpriseConfigurationGetResponse struct {
	AdaptiveFecConfig *ManaV2AdaptiveFecConfiguration `json:"adaptiveFecConfig,omitempty"`
	Configuration *ManaV2EnterpriseConfiguration `json:"configuration,omitempty"`
}

// NewV1EnterpriseConfigurationGetResponse instantiates a new V1EnterpriseConfigurationGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1EnterpriseConfigurationGetResponse() *V1EnterpriseConfigurationGetResponse {
	this := V1EnterpriseConfigurationGetResponse{}
	return &this
}

// NewV1EnterpriseConfigurationGetResponseWithDefaults instantiates a new V1EnterpriseConfigurationGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1EnterpriseConfigurationGetResponseWithDefaults() *V1EnterpriseConfigurationGetResponse {
	this := V1EnterpriseConfigurationGetResponse{}
	return &this
}

// GetAdaptiveFecConfig returns the AdaptiveFecConfig field value if set, zero value otherwise.
func (o *V1EnterpriseConfigurationGetResponse) GetAdaptiveFecConfig() ManaV2AdaptiveFecConfiguration {
	if o == nil || IsNil(o.AdaptiveFecConfig) {
		var ret ManaV2AdaptiveFecConfiguration
		return ret
	}
	return *o.AdaptiveFecConfig
}

// GetAdaptiveFecConfigOk returns a tuple with the AdaptiveFecConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterpriseConfigurationGetResponse) GetAdaptiveFecConfigOk() (*ManaV2AdaptiveFecConfiguration, bool) {
	if o == nil || IsNil(o.AdaptiveFecConfig) {
		return nil, false
	}
	return o.AdaptiveFecConfig, true
}

// HasAdaptiveFecConfig returns a boolean if a field has been set.
func (o *V1EnterpriseConfigurationGetResponse) HasAdaptiveFecConfig() bool {
	if o != nil && !IsNil(o.AdaptiveFecConfig) {
		return true
	}

	return false
}

// SetAdaptiveFecConfig gets a reference to the given ManaV2AdaptiveFecConfiguration and assigns it to the AdaptiveFecConfig field.
func (o *V1EnterpriseConfigurationGetResponse) SetAdaptiveFecConfig(v ManaV2AdaptiveFecConfiguration) {
	o.AdaptiveFecConfig = &v
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *V1EnterpriseConfigurationGetResponse) GetConfiguration() ManaV2EnterpriseConfiguration {
	if o == nil || IsNil(o.Configuration) {
		var ret ManaV2EnterpriseConfiguration
		return ret
	}
	return *o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterpriseConfigurationGetResponse) GetConfigurationOk() (*ManaV2EnterpriseConfiguration, bool) {
	if o == nil || IsNil(o.Configuration) {
		return nil, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *V1EnterpriseConfigurationGetResponse) HasConfiguration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given ManaV2EnterpriseConfiguration and assigns it to the Configuration field.
func (o *V1EnterpriseConfigurationGetResponse) SetConfiguration(v ManaV2EnterpriseConfiguration) {
	o.Configuration = &v
}

func (o V1EnterpriseConfigurationGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1EnterpriseConfigurationGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdaptiveFecConfig) {
		toSerialize["adaptiveFecConfig"] = o.AdaptiveFecConfig
	}
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	return toSerialize, nil
}

type NullableV1EnterpriseConfigurationGetResponse struct {
	value *V1EnterpriseConfigurationGetResponse
	isSet bool
}

func (v NullableV1EnterpriseConfigurationGetResponse) Get() *V1EnterpriseConfigurationGetResponse {
	return v.value
}

func (v *NullableV1EnterpriseConfigurationGetResponse) Set(val *V1EnterpriseConfigurationGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1EnterpriseConfigurationGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1EnterpriseConfigurationGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1EnterpriseConfigurationGetResponse(val *V1EnterpriseConfigurationGetResponse) *NullableV1EnterpriseConfigurationGetResponse {
	return &NullableV1EnterpriseConfigurationGetResponse{value: val, isSet: true}
}

func (v NullableV1EnterpriseConfigurationGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1EnterpriseConfigurationGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


