/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetB2bCustomersIdPutResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bCustomersIdPutResponse{}

// V1ExtranetB2bCustomersIdPutResponse struct for V1ExtranetB2bCustomersIdPutResponse
type V1ExtranetB2bCustomersIdPutResponse struct {
	Invite *ManaV2ExtranetServiceCustomerInvite `json:"invite,omitempty"`
}

// NewV1ExtranetB2bCustomersIdPutResponse instantiates a new V1ExtranetB2bCustomersIdPutResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bCustomersIdPutResponse() *V1ExtranetB2bCustomersIdPutResponse {
	this := V1ExtranetB2bCustomersIdPutResponse{}
	return &this
}

// NewV1ExtranetB2bCustomersIdPutResponseWithDefaults instantiates a new V1ExtranetB2bCustomersIdPutResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bCustomersIdPutResponseWithDefaults() *V1ExtranetB2bCustomersIdPutResponse {
	this := V1ExtranetB2bCustomersIdPutResponse{}
	return &this
}

// GetInvite returns the Invite field value if set, zero value otherwise.
func (o *V1ExtranetB2bCustomersIdPutResponse) GetInvite() ManaV2ExtranetServiceCustomerInvite {
	if o == nil || IsNil(o.Invite) {
		var ret ManaV2ExtranetServiceCustomerInvite
		return ret
	}
	return *o.Invite
}

// GetInviteOk returns a tuple with the Invite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bCustomersIdPutResponse) GetInviteOk() (*ManaV2ExtranetServiceCustomerInvite, bool) {
	if o == nil || IsNil(o.Invite) {
		return nil, false
	}
	return o.Invite, true
}

// HasInvite returns a boolean if a field has been set.
func (o *V1ExtranetB2bCustomersIdPutResponse) HasInvite() bool {
	if o != nil && !IsNil(o.Invite) {
		return true
	}

	return false
}

// SetInvite gets a reference to the given ManaV2ExtranetServiceCustomerInvite and assigns it to the Invite field.
func (o *V1ExtranetB2bCustomersIdPutResponse) SetInvite(v ManaV2ExtranetServiceCustomerInvite) {
	o.Invite = &v
}

func (o V1ExtranetB2bCustomersIdPutResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bCustomersIdPutResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Invite) {
		toSerialize["invite"] = o.Invite
	}
	return toSerialize, nil
}

type NullableV1ExtranetB2bCustomersIdPutResponse struct {
	value *V1ExtranetB2bCustomersIdPutResponse
	isSet bool
}

func (v NullableV1ExtranetB2bCustomersIdPutResponse) Get() *V1ExtranetB2bCustomersIdPutResponse {
	return v.value
}

func (v *NullableV1ExtranetB2bCustomersIdPutResponse) Set(val *V1ExtranetB2bCustomersIdPutResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bCustomersIdPutResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bCustomersIdPutResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bCustomersIdPutResponse(val *V1ExtranetB2bCustomersIdPutResponse) *NullableV1ExtranetB2bCustomersIdPutResponse {
	return &NullableV1ExtranetB2bCustomersIdPutResponse{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bCustomersIdPutResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bCustomersIdPutResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


