/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V2AssuranceAiAdoptionSummaryPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2AssuranceAiAdoptionSummaryPostResponse{}

// V2AssuranceAiAdoptionSummaryPostResponse struct for V2AssuranceAiAdoptionSummaryPostResponse
type V2AssuranceAiAdoptionSummaryPostResponse struct {
	TopLevelKpi *AssuranceTopLevelKpi `json:"topLevelKpi,omitempty"`
	WhatWidget *AssuranceWhatWidget `json:"whatWidget,omitempty"`
	WhenWidget *AssuranceWhenWidget `json:"whenWidget,omitempty"`
	WhereWidget *AssuranceWhereWidget `json:"whereWidget,omitempty"`
}

// NewV2AssuranceAiAdoptionSummaryPostResponse instantiates a new V2AssuranceAiAdoptionSummaryPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2AssuranceAiAdoptionSummaryPostResponse() *V2AssuranceAiAdoptionSummaryPostResponse {
	this := V2AssuranceAiAdoptionSummaryPostResponse{}
	return &this
}

// NewV2AssuranceAiAdoptionSummaryPostResponseWithDefaults instantiates a new V2AssuranceAiAdoptionSummaryPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2AssuranceAiAdoptionSummaryPostResponseWithDefaults() *V2AssuranceAiAdoptionSummaryPostResponse {
	this := V2AssuranceAiAdoptionSummaryPostResponse{}
	return &this
}

// GetTopLevelKpi returns the TopLevelKpi field value if set, zero value otherwise.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) GetTopLevelKpi() AssuranceTopLevelKpi {
	if o == nil || IsNil(o.TopLevelKpi) {
		var ret AssuranceTopLevelKpi
		return ret
	}
	return *o.TopLevelKpi
}

// GetTopLevelKpiOk returns a tuple with the TopLevelKpi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) GetTopLevelKpiOk() (*AssuranceTopLevelKpi, bool) {
	if o == nil || IsNil(o.TopLevelKpi) {
		return nil, false
	}
	return o.TopLevelKpi, true
}

// HasTopLevelKpi returns a boolean if a field has been set.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) HasTopLevelKpi() bool {
	if o != nil && !IsNil(o.TopLevelKpi) {
		return true
	}

	return false
}

// SetTopLevelKpi gets a reference to the given AssuranceTopLevelKpi and assigns it to the TopLevelKpi field.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) SetTopLevelKpi(v AssuranceTopLevelKpi) {
	o.TopLevelKpi = &v
}

// GetWhatWidget returns the WhatWidget field value if set, zero value otherwise.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) GetWhatWidget() AssuranceWhatWidget {
	if o == nil || IsNil(o.WhatWidget) {
		var ret AssuranceWhatWidget
		return ret
	}
	return *o.WhatWidget
}

// GetWhatWidgetOk returns a tuple with the WhatWidget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) GetWhatWidgetOk() (*AssuranceWhatWidget, bool) {
	if o == nil || IsNil(o.WhatWidget) {
		return nil, false
	}
	return o.WhatWidget, true
}

// HasWhatWidget returns a boolean if a field has been set.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) HasWhatWidget() bool {
	if o != nil && !IsNil(o.WhatWidget) {
		return true
	}

	return false
}

// SetWhatWidget gets a reference to the given AssuranceWhatWidget and assigns it to the WhatWidget field.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) SetWhatWidget(v AssuranceWhatWidget) {
	o.WhatWidget = &v
}

// GetWhenWidget returns the WhenWidget field value if set, zero value otherwise.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) GetWhenWidget() AssuranceWhenWidget {
	if o == nil || IsNil(o.WhenWidget) {
		var ret AssuranceWhenWidget
		return ret
	}
	return *o.WhenWidget
}

// GetWhenWidgetOk returns a tuple with the WhenWidget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) GetWhenWidgetOk() (*AssuranceWhenWidget, bool) {
	if o == nil || IsNil(o.WhenWidget) {
		return nil, false
	}
	return o.WhenWidget, true
}

// HasWhenWidget returns a boolean if a field has been set.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) HasWhenWidget() bool {
	if o != nil && !IsNil(o.WhenWidget) {
		return true
	}

	return false
}

// SetWhenWidget gets a reference to the given AssuranceWhenWidget and assigns it to the WhenWidget field.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) SetWhenWidget(v AssuranceWhenWidget) {
	o.WhenWidget = &v
}

// GetWhereWidget returns the WhereWidget field value if set, zero value otherwise.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) GetWhereWidget() AssuranceWhereWidget {
	if o == nil || IsNil(o.WhereWidget) {
		var ret AssuranceWhereWidget
		return ret
	}
	return *o.WhereWidget
}

// GetWhereWidgetOk returns a tuple with the WhereWidget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) GetWhereWidgetOk() (*AssuranceWhereWidget, bool) {
	if o == nil || IsNil(o.WhereWidget) {
		return nil, false
	}
	return o.WhereWidget, true
}

// HasWhereWidget returns a boolean if a field has been set.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) HasWhereWidget() bool {
	if o != nil && !IsNil(o.WhereWidget) {
		return true
	}

	return false
}

// SetWhereWidget gets a reference to the given AssuranceWhereWidget and assigns it to the WhereWidget field.
func (o *V2AssuranceAiAdoptionSummaryPostResponse) SetWhereWidget(v AssuranceWhereWidget) {
	o.WhereWidget = &v
}

func (o V2AssuranceAiAdoptionSummaryPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2AssuranceAiAdoptionSummaryPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TopLevelKpi) {
		toSerialize["topLevelKpi"] = o.TopLevelKpi
	}
	if !IsNil(o.WhatWidget) {
		toSerialize["whatWidget"] = o.WhatWidget
	}
	if !IsNil(o.WhenWidget) {
		toSerialize["whenWidget"] = o.WhenWidget
	}
	if !IsNil(o.WhereWidget) {
		toSerialize["whereWidget"] = o.WhereWidget
	}
	return toSerialize, nil
}

type NullableV2AssuranceAiAdoptionSummaryPostResponse struct {
	value *V2AssuranceAiAdoptionSummaryPostResponse
	isSet bool
}

func (v NullableV2AssuranceAiAdoptionSummaryPostResponse) Get() *V2AssuranceAiAdoptionSummaryPostResponse {
	return v.value
}

func (v *NullableV2AssuranceAiAdoptionSummaryPostResponse) Set(val *V2AssuranceAiAdoptionSummaryPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AssuranceAiAdoptionSummaryPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AssuranceAiAdoptionSummaryPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AssuranceAiAdoptionSummaryPostResponse(val *V2AssuranceAiAdoptionSummaryPostResponse) *NullableV2AssuranceAiAdoptionSummaryPostResponse {
	return &NullableV2AssuranceAiAdoptionSummaryPostResponse{value: val, isSet: true}
}

func (v NullableV2AssuranceAiAdoptionSummaryPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AssuranceAiAdoptionSummaryPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


