/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetB2bConsumersIdPrefixesPutResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bConsumersIdPrefixesPutResponse{}

// V1ExtranetB2bConsumersIdPrefixesPutResponse struct for V1ExtranetB2bConsumersIdPrefixesPutResponse
type V1ExtranetB2bConsumersIdPrefixesPutResponse struct {
	ConsumerActivityId *string `json:"consumerActivityId,omitempty"`
}

// NewV1ExtranetB2bConsumersIdPrefixesPutResponse instantiates a new V1ExtranetB2bConsumersIdPrefixesPutResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bConsumersIdPrefixesPutResponse() *V1ExtranetB2bConsumersIdPrefixesPutResponse {
	this := V1ExtranetB2bConsumersIdPrefixesPutResponse{}
	return &this
}

// NewV1ExtranetB2bConsumersIdPrefixesPutResponseWithDefaults instantiates a new V1ExtranetB2bConsumersIdPrefixesPutResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bConsumersIdPrefixesPutResponseWithDefaults() *V1ExtranetB2bConsumersIdPrefixesPutResponse {
	this := V1ExtranetB2bConsumersIdPrefixesPutResponse{}
	return &this
}

// GetConsumerActivityId returns the ConsumerActivityId field value if set, zero value otherwise.
func (o *V1ExtranetB2bConsumersIdPrefixesPutResponse) GetConsumerActivityId() string {
	if o == nil || IsNil(o.ConsumerActivityId) {
		var ret string
		return ret
	}
	return *o.ConsumerActivityId
}

// GetConsumerActivityIdOk returns a tuple with the ConsumerActivityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bConsumersIdPrefixesPutResponse) GetConsumerActivityIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConsumerActivityId) {
		return nil, false
	}
	return o.ConsumerActivityId, true
}

// HasConsumerActivityId returns a boolean if a field has been set.
func (o *V1ExtranetB2bConsumersIdPrefixesPutResponse) HasConsumerActivityId() bool {
	if o != nil && !IsNil(o.ConsumerActivityId) {
		return true
	}

	return false
}

// SetConsumerActivityId gets a reference to the given string and assigns it to the ConsumerActivityId field.
func (o *V1ExtranetB2bConsumersIdPrefixesPutResponse) SetConsumerActivityId(v string) {
	o.ConsumerActivityId = &v
}

func (o V1ExtranetB2bConsumersIdPrefixesPutResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bConsumersIdPrefixesPutResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConsumerActivityId) {
		toSerialize["consumerActivityId"] = o.ConsumerActivityId
	}
	return toSerialize, nil
}

type NullableV1ExtranetB2bConsumersIdPrefixesPutResponse struct {
	value *V1ExtranetB2bConsumersIdPrefixesPutResponse
	isSet bool
}

func (v NullableV1ExtranetB2bConsumersIdPrefixesPutResponse) Get() *V1ExtranetB2bConsumersIdPrefixesPutResponse {
	return v.value
}

func (v *NullableV1ExtranetB2bConsumersIdPrefixesPutResponse) Set(val *V1ExtranetB2bConsumersIdPrefixesPutResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bConsumersIdPrefixesPutResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bConsumersIdPrefixesPutResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bConsumersIdPrefixesPutResponse(val *V1ExtranetB2bConsumersIdPrefixesPutResponse) *NullableV1ExtranetB2bConsumersIdPrefixesPutResponse {
	return &NullableV1ExtranetB2bConsumersIdPrefixesPutResponse{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bConsumersIdPrefixesPutResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bConsumersIdPrefixesPutResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


