/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the UpgradeRolloutDevice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpgradeRolloutDevice{}

// UpgradeRolloutDevice struct for UpgradeRolloutDevice
type UpgradeRolloutDevice struct {
	// Device identifier. (required)
	DeviceId *int64 `json:"deviceId,omitempty"`
	// Device hostname for display.
	Hostname *string `json:"hostname,omitempty"`
}

// NewUpgradeRolloutDevice instantiates a new UpgradeRolloutDevice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpgradeRolloutDevice() *UpgradeRolloutDevice {
	this := UpgradeRolloutDevice{}
	return &this
}

// NewUpgradeRolloutDeviceWithDefaults instantiates a new UpgradeRolloutDevice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpgradeRolloutDeviceWithDefaults() *UpgradeRolloutDevice {
	this := UpgradeRolloutDevice{}
	return &this
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *UpgradeRolloutDevice) GetDeviceId() int64 {
	if o == nil || IsNil(o.DeviceId) {
		var ret int64
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpgradeRolloutDevice) GetDeviceIdOk() (*int64, bool) {
	if o == nil || IsNil(o.DeviceId) {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *UpgradeRolloutDevice) HasDeviceId() bool {
	if o != nil && !IsNil(o.DeviceId) {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given int64 and assigns it to the DeviceId field.
func (o *UpgradeRolloutDevice) SetDeviceId(v int64) {
	o.DeviceId = &v
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *UpgradeRolloutDevice) GetHostname() string {
	if o == nil || IsNil(o.Hostname) {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpgradeRolloutDevice) GetHostnameOk() (*string, bool) {
	if o == nil || IsNil(o.Hostname) {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *UpgradeRolloutDevice) HasHostname() bool {
	if o != nil && !IsNil(o.Hostname) {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *UpgradeRolloutDevice) SetHostname(v string) {
	o.Hostname = &v
}

func (o UpgradeRolloutDevice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpgradeRolloutDevice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceId) {
		toSerialize["deviceId"] = o.DeviceId
	}
	if !IsNil(o.Hostname) {
		toSerialize["hostname"] = o.Hostname
	}
	return toSerialize, nil
}

type NullableUpgradeRolloutDevice struct {
	value *UpgradeRolloutDevice
	isSet bool
}

func (v NullableUpgradeRolloutDevice) Get() *UpgradeRolloutDevice {
	return v.value
}

func (v *NullableUpgradeRolloutDevice) Set(val *UpgradeRolloutDevice) {
	v.value = val
	v.isSet = true
}

func (v NullableUpgradeRolloutDevice) IsSet() bool {
	return v.isSet
}

func (v *NullableUpgradeRolloutDevice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpgradeRolloutDevice(val *UpgradeRolloutDevice) *NullableUpgradeRolloutDevice {
	return &NullableUpgradeRolloutDevice{value: val, isSet: true}
}

func (v NullableUpgradeRolloutDevice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpgradeRolloutDevice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


