/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetB2bMatchesPausePutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bMatchesPausePutRequest{}

// V1ExtranetB2bMatchesPausePutRequest struct for V1ExtranetB2bMatchesPausePutRequest
type V1ExtranetB2bMatchesPausePutRequest struct {
	CustomerId *int64 `json:"customerId,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewV1ExtranetB2bMatchesPausePutRequest instantiates a new V1ExtranetB2bMatchesPausePutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bMatchesPausePutRequest() *V1ExtranetB2bMatchesPausePutRequest {
	this := V1ExtranetB2bMatchesPausePutRequest{}
	return &this
}

// NewV1ExtranetB2bMatchesPausePutRequestWithDefaults instantiates a new V1ExtranetB2bMatchesPausePutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bMatchesPausePutRequestWithDefaults() *V1ExtranetB2bMatchesPausePutRequest {
	this := V1ExtranetB2bMatchesPausePutRequest{}
	return &this
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *V1ExtranetB2bMatchesPausePutRequest) GetCustomerId() int64 {
	if o == nil || IsNil(o.CustomerId) {
		var ret int64
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMatchesPausePutRequest) GetCustomerIdOk() (*int64, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *V1ExtranetB2bMatchesPausePutRequest) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given int64 and assigns it to the CustomerId field.
func (o *V1ExtranetB2bMatchesPausePutRequest) SetCustomerId(v int64) {
	o.CustomerId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1ExtranetB2bMatchesPausePutRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMatchesPausePutRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1ExtranetB2bMatchesPausePutRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1ExtranetB2bMatchesPausePutRequest) SetStatus(v string) {
	o.Status = &v
}

func (o V1ExtranetB2bMatchesPausePutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bMatchesPausePutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1ExtranetB2bMatchesPausePutRequest struct {
	value *V1ExtranetB2bMatchesPausePutRequest
	isSet bool
}

func (v NullableV1ExtranetB2bMatchesPausePutRequest) Get() *V1ExtranetB2bMatchesPausePutRequest {
	return v.value
}

func (v *NullableV1ExtranetB2bMatchesPausePutRequest) Set(val *V1ExtranetB2bMatchesPausePutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bMatchesPausePutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bMatchesPausePutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bMatchesPausePutRequest(val *V1ExtranetB2bMatchesPausePutRequest) *NullableV1ExtranetB2bMatchesPausePutRequest {
	return &NullableV1ExtranetB2bMatchesPausePutRequest{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bMatchesPausePutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bMatchesPausePutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


