/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the AssuranceWhereWidget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssuranceWhereWidget{}

// AssuranceWhereWidget struct for AssuranceWhereWidget
type AssuranceWhereWidget struct {
	TopSitesByUsers []AssuranceKpiMetric `json:"topSitesByUsers,omitempty"`
	TopUsersByDataTransferred []AssuranceUserDefinition `json:"topUsersByDataTransferred,omitempty"`
	TopVrfsByUsers []AssuranceKpiMetric `json:"topVrfsByUsers,omitempty"`
}

// NewAssuranceWhereWidget instantiates a new AssuranceWhereWidget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssuranceWhereWidget() *AssuranceWhereWidget {
	this := AssuranceWhereWidget{}
	return &this
}

// NewAssuranceWhereWidgetWithDefaults instantiates a new AssuranceWhereWidget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssuranceWhereWidgetWithDefaults() *AssuranceWhereWidget {
	this := AssuranceWhereWidget{}
	return &this
}

// GetTopSitesByUsers returns the TopSitesByUsers field value if set, zero value otherwise.
func (o *AssuranceWhereWidget) GetTopSitesByUsers() []AssuranceKpiMetric {
	if o == nil || IsNil(o.TopSitesByUsers) {
		var ret []AssuranceKpiMetric
		return ret
	}
	return o.TopSitesByUsers
}

// GetTopSitesByUsersOk returns a tuple with the TopSitesByUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceWhereWidget) GetTopSitesByUsersOk() ([]AssuranceKpiMetric, bool) {
	if o == nil || IsNil(o.TopSitesByUsers) {
		return nil, false
	}
	return o.TopSitesByUsers, true
}

// HasTopSitesByUsers returns a boolean if a field has been set.
func (o *AssuranceWhereWidget) HasTopSitesByUsers() bool {
	if o != nil && !IsNil(o.TopSitesByUsers) {
		return true
	}

	return false
}

// SetTopSitesByUsers gets a reference to the given []AssuranceKpiMetric and assigns it to the TopSitesByUsers field.
func (o *AssuranceWhereWidget) SetTopSitesByUsers(v []AssuranceKpiMetric) {
	o.TopSitesByUsers = v
}

// GetTopUsersByDataTransferred returns the TopUsersByDataTransferred field value if set, zero value otherwise.
func (o *AssuranceWhereWidget) GetTopUsersByDataTransferred() []AssuranceUserDefinition {
	if o == nil || IsNil(o.TopUsersByDataTransferred) {
		var ret []AssuranceUserDefinition
		return ret
	}
	return o.TopUsersByDataTransferred
}

// GetTopUsersByDataTransferredOk returns a tuple with the TopUsersByDataTransferred field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceWhereWidget) GetTopUsersByDataTransferredOk() ([]AssuranceUserDefinition, bool) {
	if o == nil || IsNil(o.TopUsersByDataTransferred) {
		return nil, false
	}
	return o.TopUsersByDataTransferred, true
}

// HasTopUsersByDataTransferred returns a boolean if a field has been set.
func (o *AssuranceWhereWidget) HasTopUsersByDataTransferred() bool {
	if o != nil && !IsNil(o.TopUsersByDataTransferred) {
		return true
	}

	return false
}

// SetTopUsersByDataTransferred gets a reference to the given []AssuranceUserDefinition and assigns it to the TopUsersByDataTransferred field.
func (o *AssuranceWhereWidget) SetTopUsersByDataTransferred(v []AssuranceUserDefinition) {
	o.TopUsersByDataTransferred = v
}

// GetTopVrfsByUsers returns the TopVrfsByUsers field value if set, zero value otherwise.
func (o *AssuranceWhereWidget) GetTopVrfsByUsers() []AssuranceKpiMetric {
	if o == nil || IsNil(o.TopVrfsByUsers) {
		var ret []AssuranceKpiMetric
		return ret
	}
	return o.TopVrfsByUsers
}

// GetTopVrfsByUsersOk returns a tuple with the TopVrfsByUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceWhereWidget) GetTopVrfsByUsersOk() ([]AssuranceKpiMetric, bool) {
	if o == nil || IsNil(o.TopVrfsByUsers) {
		return nil, false
	}
	return o.TopVrfsByUsers, true
}

// HasTopVrfsByUsers returns a boolean if a field has been set.
func (o *AssuranceWhereWidget) HasTopVrfsByUsers() bool {
	if o != nil && !IsNil(o.TopVrfsByUsers) {
		return true
	}

	return false
}

// SetTopVrfsByUsers gets a reference to the given []AssuranceKpiMetric and assigns it to the TopVrfsByUsers field.
func (o *AssuranceWhereWidget) SetTopVrfsByUsers(v []AssuranceKpiMetric) {
	o.TopVrfsByUsers = v
}

func (o AssuranceWhereWidget) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssuranceWhereWidget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TopSitesByUsers) {
		toSerialize["topSitesByUsers"] = o.TopSitesByUsers
	}
	if !IsNil(o.TopUsersByDataTransferred) {
		toSerialize["topUsersByDataTransferred"] = o.TopUsersByDataTransferred
	}
	if !IsNil(o.TopVrfsByUsers) {
		toSerialize["topVrfsByUsers"] = o.TopVrfsByUsers
	}
	return toSerialize, nil
}

type NullableAssuranceWhereWidget struct {
	value *AssuranceWhereWidget
	isSet bool
}

func (v NullableAssuranceWhereWidget) Get() *AssuranceWhereWidget {
	return v.value
}

func (v *NullableAssuranceWhereWidget) Set(val *AssuranceWhereWidget) {
	v.value = val
	v.isSet = true
}

func (v NullableAssuranceWhereWidget) IsSet() bool {
	return v.isSet
}

func (v *NullableAssuranceWhereWidget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssuranceWhereWidget(val *AssuranceWhereWidget) *NullableAssuranceWhereWidget {
	return &NullableAssuranceWhereWidget{value: val, isSet: true}
}

func (v NullableAssuranceWhereWidget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssuranceWhereWidget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


