/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2LanSegmentPublicInterfaceEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2LanSegmentPublicInterfaceEntry{}

// ManaV2LanSegmentPublicInterfaceEntry struct for ManaV2LanSegmentPublicInterfaceEntry
type ManaV2LanSegmentPublicInterfaceEntry struct {
	// network.interface id (required)
	InterfaceId *int64 `json:"interfaceId,omitempty"`
	Ipv4Addresses []string `json:"ipv4Addresses,omitempty"`
	// Device interface name (BGP local_interface uses this) (required)
	Name *string `json:"name,omitempty"`
	// Interface storage provider (cloud provider for gateway LAN interfaces)
	StorageProvider *string `json:"storageProvider,omitempty"`
}

// NewManaV2LanSegmentPublicInterfaceEntry instantiates a new ManaV2LanSegmentPublicInterfaceEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2LanSegmentPublicInterfaceEntry() *ManaV2LanSegmentPublicInterfaceEntry {
	this := ManaV2LanSegmentPublicInterfaceEntry{}
	return &this
}

// NewManaV2LanSegmentPublicInterfaceEntryWithDefaults instantiates a new ManaV2LanSegmentPublicInterfaceEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2LanSegmentPublicInterfaceEntryWithDefaults() *ManaV2LanSegmentPublicInterfaceEntry {
	this := ManaV2LanSegmentPublicInterfaceEntry{}
	return &this
}

// GetInterfaceId returns the InterfaceId field value if set, zero value otherwise.
func (o *ManaV2LanSegmentPublicInterfaceEntry) GetInterfaceId() int64 {
	if o == nil || IsNil(o.InterfaceId) {
		var ret int64
		return ret
	}
	return *o.InterfaceId
}

// GetInterfaceIdOk returns a tuple with the InterfaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2LanSegmentPublicInterfaceEntry) GetInterfaceIdOk() (*int64, bool) {
	if o == nil || IsNil(o.InterfaceId) {
		return nil, false
	}
	return o.InterfaceId, true
}

// HasInterfaceId returns a boolean if a field has been set.
func (o *ManaV2LanSegmentPublicInterfaceEntry) HasInterfaceId() bool {
	if o != nil && !IsNil(o.InterfaceId) {
		return true
	}

	return false
}

// SetInterfaceId gets a reference to the given int64 and assigns it to the InterfaceId field.
func (o *ManaV2LanSegmentPublicInterfaceEntry) SetInterfaceId(v int64) {
	o.InterfaceId = &v
}

// GetIpv4Addresses returns the Ipv4Addresses field value if set, zero value otherwise.
func (o *ManaV2LanSegmentPublicInterfaceEntry) GetIpv4Addresses() []string {
	if o == nil || IsNil(o.Ipv4Addresses) {
		var ret []string
		return ret
	}
	return o.Ipv4Addresses
}

// GetIpv4AddressesOk returns a tuple with the Ipv4Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2LanSegmentPublicInterfaceEntry) GetIpv4AddressesOk() ([]string, bool) {
	if o == nil || IsNil(o.Ipv4Addresses) {
		return nil, false
	}
	return o.Ipv4Addresses, true
}

// HasIpv4Addresses returns a boolean if a field has been set.
func (o *ManaV2LanSegmentPublicInterfaceEntry) HasIpv4Addresses() bool {
	if o != nil && !IsNil(o.Ipv4Addresses) {
		return true
	}

	return false
}

// SetIpv4Addresses gets a reference to the given []string and assigns it to the Ipv4Addresses field.
func (o *ManaV2LanSegmentPublicInterfaceEntry) SetIpv4Addresses(v []string) {
	o.Ipv4Addresses = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ManaV2LanSegmentPublicInterfaceEntry) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2LanSegmentPublicInterfaceEntry) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ManaV2LanSegmentPublicInterfaceEntry) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ManaV2LanSegmentPublicInterfaceEntry) SetName(v string) {
	o.Name = &v
}

// GetStorageProvider returns the StorageProvider field value if set, zero value otherwise.
func (o *ManaV2LanSegmentPublicInterfaceEntry) GetStorageProvider() string {
	if o == nil || IsNil(o.StorageProvider) {
		var ret string
		return ret
	}
	return *o.StorageProvider
}

// GetStorageProviderOk returns a tuple with the StorageProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2LanSegmentPublicInterfaceEntry) GetStorageProviderOk() (*string, bool) {
	if o == nil || IsNil(o.StorageProvider) {
		return nil, false
	}
	return o.StorageProvider, true
}

// HasStorageProvider returns a boolean if a field has been set.
func (o *ManaV2LanSegmentPublicInterfaceEntry) HasStorageProvider() bool {
	if o != nil && !IsNil(o.StorageProvider) {
		return true
	}

	return false
}

// SetStorageProvider gets a reference to the given string and assigns it to the StorageProvider field.
func (o *ManaV2LanSegmentPublicInterfaceEntry) SetStorageProvider(v string) {
	o.StorageProvider = &v
}

func (o ManaV2LanSegmentPublicInterfaceEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2LanSegmentPublicInterfaceEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InterfaceId) {
		toSerialize["interfaceId"] = o.InterfaceId
	}
	if !IsNil(o.Ipv4Addresses) {
		toSerialize["ipv4Addresses"] = o.Ipv4Addresses
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.StorageProvider) {
		toSerialize["storageProvider"] = o.StorageProvider
	}
	return toSerialize, nil
}

type NullableManaV2LanSegmentPublicInterfaceEntry struct {
	value *ManaV2LanSegmentPublicInterfaceEntry
	isSet bool
}

func (v NullableManaV2LanSegmentPublicInterfaceEntry) Get() *ManaV2LanSegmentPublicInterfaceEntry {
	return v.value
}

func (v *NullableManaV2LanSegmentPublicInterfaceEntry) Set(val *ManaV2LanSegmentPublicInterfaceEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2LanSegmentPublicInterfaceEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2LanSegmentPublicInterfaceEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2LanSegmentPublicInterfaceEntry(val *ManaV2LanSegmentPublicInterfaceEntry) *NullableManaV2LanSegmentPublicInterfaceEntry {
	return &NullableManaV2LanSegmentPublicInterfaceEntry{value: val, isSet: true}
}

func (v NullableManaV2LanSegmentPublicInterfaceEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2LanSegmentPublicInterfaceEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


