/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2AssuranceUpdateAiAdoptionApproveEntryPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2AssuranceUpdateAiAdoptionApproveEntryPostRequest{}

// V2AssuranceUpdateAiAdoptionApproveEntryPostRequest struct for V2AssuranceUpdateAiAdoptionApproveEntryPostRequest
type V2AssuranceUpdateAiAdoptionApproveEntryPostRequest struct {
	ApprovedAppEntry AssuranceApprovedAppEntryRequest `json:"approvedAppEntry"`
}

type _V2AssuranceUpdateAiAdoptionApproveEntryPostRequest V2AssuranceUpdateAiAdoptionApproveEntryPostRequest

// NewV2AssuranceUpdateAiAdoptionApproveEntryPostRequest instantiates a new V2AssuranceUpdateAiAdoptionApproveEntryPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2AssuranceUpdateAiAdoptionApproveEntryPostRequest(approvedAppEntry AssuranceApprovedAppEntryRequest) *V2AssuranceUpdateAiAdoptionApproveEntryPostRequest {
	this := V2AssuranceUpdateAiAdoptionApproveEntryPostRequest{}
	this.ApprovedAppEntry = approvedAppEntry
	return &this
}

// NewV2AssuranceUpdateAiAdoptionApproveEntryPostRequestWithDefaults instantiates a new V2AssuranceUpdateAiAdoptionApproveEntryPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2AssuranceUpdateAiAdoptionApproveEntryPostRequestWithDefaults() *V2AssuranceUpdateAiAdoptionApproveEntryPostRequest {
	this := V2AssuranceUpdateAiAdoptionApproveEntryPostRequest{}
	return &this
}

// GetApprovedAppEntry returns the ApprovedAppEntry field value
func (o *V2AssuranceUpdateAiAdoptionApproveEntryPostRequest) GetApprovedAppEntry() AssuranceApprovedAppEntryRequest {
	if o == nil {
		var ret AssuranceApprovedAppEntryRequest
		return ret
	}

	return o.ApprovedAppEntry
}

// GetApprovedAppEntryOk returns a tuple with the ApprovedAppEntry field value
// and a boolean to check if the value has been set.
func (o *V2AssuranceUpdateAiAdoptionApproveEntryPostRequest) GetApprovedAppEntryOk() (*AssuranceApprovedAppEntryRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApprovedAppEntry, true
}

// SetApprovedAppEntry sets field value
func (o *V2AssuranceUpdateAiAdoptionApproveEntryPostRequest) SetApprovedAppEntry(v AssuranceApprovedAppEntryRequest) {
	o.ApprovedAppEntry = v
}

func (o V2AssuranceUpdateAiAdoptionApproveEntryPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2AssuranceUpdateAiAdoptionApproveEntryPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["approvedAppEntry"] = o.ApprovedAppEntry
	return toSerialize, nil
}

func (o *V2AssuranceUpdateAiAdoptionApproveEntryPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"approvedAppEntry",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2AssuranceUpdateAiAdoptionApproveEntryPostRequest := _V2AssuranceUpdateAiAdoptionApproveEntryPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2AssuranceUpdateAiAdoptionApproveEntryPostRequest)

	if err != nil {
		return err
	}

	*o = V2AssuranceUpdateAiAdoptionApproveEntryPostRequest(varV2AssuranceUpdateAiAdoptionApproveEntryPostRequest)

	return err
}

type NullableV2AssuranceUpdateAiAdoptionApproveEntryPostRequest struct {
	value *V2AssuranceUpdateAiAdoptionApproveEntryPostRequest
	isSet bool
}

func (v NullableV2AssuranceUpdateAiAdoptionApproveEntryPostRequest) Get() *V2AssuranceUpdateAiAdoptionApproveEntryPostRequest {
	return v.value
}

func (v *NullableV2AssuranceUpdateAiAdoptionApproveEntryPostRequest) Set(val *V2AssuranceUpdateAiAdoptionApproveEntryPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AssuranceUpdateAiAdoptionApproveEntryPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AssuranceUpdateAiAdoptionApproveEntryPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AssuranceUpdateAiAdoptionApproveEntryPostRequest(val *V2AssuranceUpdateAiAdoptionApproveEntryPostRequest) *NullableV2AssuranceUpdateAiAdoptionApproveEntryPostRequest {
	return &NullableV2AssuranceUpdateAiAdoptionApproveEntryPostRequest{value: val, isSet: true}
}

func (v NullableV2AssuranceUpdateAiAdoptionApproveEntryPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AssuranceUpdateAiAdoptionApproveEntryPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


