/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2PublicVifFixedNat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2PublicVifFixedNat{}

// ManaV2PublicVifFixedNat struct for ManaV2PublicVifFixedNat
type ManaV2PublicVifFixedNat struct {
	OutsideNatPrefix *string `json:"outsideNatPrefix,omitempty"`
	ServicePrefix *string `json:"servicePrefix,omitempty"`
}

// NewManaV2PublicVifFixedNat instantiates a new ManaV2PublicVifFixedNat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2PublicVifFixedNat() *ManaV2PublicVifFixedNat {
	this := ManaV2PublicVifFixedNat{}
	return &this
}

// NewManaV2PublicVifFixedNatWithDefaults instantiates a new ManaV2PublicVifFixedNat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2PublicVifFixedNatWithDefaults() *ManaV2PublicVifFixedNat {
	this := ManaV2PublicVifFixedNat{}
	return &this
}

// GetOutsideNatPrefix returns the OutsideNatPrefix field value if set, zero value otherwise.
func (o *ManaV2PublicVifFixedNat) GetOutsideNatPrefix() string {
	if o == nil || IsNil(o.OutsideNatPrefix) {
		var ret string
		return ret
	}
	return *o.OutsideNatPrefix
}

// GetOutsideNatPrefixOk returns a tuple with the OutsideNatPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifFixedNat) GetOutsideNatPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.OutsideNatPrefix) {
		return nil, false
	}
	return o.OutsideNatPrefix, true
}

// HasOutsideNatPrefix returns a boolean if a field has been set.
func (o *ManaV2PublicVifFixedNat) HasOutsideNatPrefix() bool {
	if o != nil && !IsNil(o.OutsideNatPrefix) {
		return true
	}

	return false
}

// SetOutsideNatPrefix gets a reference to the given string and assigns it to the OutsideNatPrefix field.
func (o *ManaV2PublicVifFixedNat) SetOutsideNatPrefix(v string) {
	o.OutsideNatPrefix = &v
}

// GetServicePrefix returns the ServicePrefix field value if set, zero value otherwise.
func (o *ManaV2PublicVifFixedNat) GetServicePrefix() string {
	if o == nil || IsNil(o.ServicePrefix) {
		var ret string
		return ret
	}
	return *o.ServicePrefix
}

// GetServicePrefixOk returns a tuple with the ServicePrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifFixedNat) GetServicePrefixOk() (*string, bool) {
	if o == nil || IsNil(o.ServicePrefix) {
		return nil, false
	}
	return o.ServicePrefix, true
}

// HasServicePrefix returns a boolean if a field has been set.
func (o *ManaV2PublicVifFixedNat) HasServicePrefix() bool {
	if o != nil && !IsNil(o.ServicePrefix) {
		return true
	}

	return false
}

// SetServicePrefix gets a reference to the given string and assigns it to the ServicePrefix field.
func (o *ManaV2PublicVifFixedNat) SetServicePrefix(v string) {
	o.ServicePrefix = &v
}

func (o ManaV2PublicVifFixedNat) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2PublicVifFixedNat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OutsideNatPrefix) {
		toSerialize["outsideNatPrefix"] = o.OutsideNatPrefix
	}
	if !IsNil(o.ServicePrefix) {
		toSerialize["servicePrefix"] = o.ServicePrefix
	}
	return toSerialize, nil
}

type NullableManaV2PublicVifFixedNat struct {
	value *ManaV2PublicVifFixedNat
	isSet bool
}

func (v NullableManaV2PublicVifFixedNat) Get() *ManaV2PublicVifFixedNat {
	return v.value
}

func (v *NullableManaV2PublicVifFixedNat) Set(val *ManaV2PublicVifFixedNat) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2PublicVifFixedNat) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2PublicVifFixedNat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2PublicVifFixedNat(val *ManaV2PublicVifFixedNat) *NullableManaV2PublicVifFixedNat {
	return &NullableManaV2PublicVifFixedNat{value: val, isSet: true}
}

func (v NullableManaV2PublicVifFixedNat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2PublicVifFixedNat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


