/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AlertserviceZendeskDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertserviceZendeskDetails{}

// AlertserviceZendeskDetails struct for AlertserviceZendeskDetails
type AlertserviceZendeskDetails struct {
	// zendesk api token (deprecated, use zendesk_client_secret)
	ZendeskApiToken *string `json:"zendeskApiToken,omitempty"`
	// zendesk assignee id (required)
	ZendeskAssigneeId string `json:"zendeskAssigneeId"`
	// zendesk base url (required)
	ZendeskBaseUrl string `json:"zendeskBaseUrl"`
	// zendesk oauth client id (required)
	ZendeskClientId string `json:"zendeskClientId"`
	// zendesk oauth client secret (required)
	ZendeskClientSecret string `json:"zendeskClientSecret"`
	// zendesk email (deprecated, use zendesk_client_id)
	ZendeskEmail *string `json:"zendeskEmail,omitempty"`
}

type _AlertserviceZendeskDetails AlertserviceZendeskDetails

// NewAlertserviceZendeskDetails instantiates a new AlertserviceZendeskDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertserviceZendeskDetails(zendeskAssigneeId string, zendeskBaseUrl string, zendeskClientId string, zendeskClientSecret string) *AlertserviceZendeskDetails {
	this := AlertserviceZendeskDetails{}
	this.ZendeskAssigneeId = zendeskAssigneeId
	this.ZendeskBaseUrl = zendeskBaseUrl
	this.ZendeskClientId = zendeskClientId
	this.ZendeskClientSecret = zendeskClientSecret
	return &this
}

// NewAlertserviceZendeskDetailsWithDefaults instantiates a new AlertserviceZendeskDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertserviceZendeskDetailsWithDefaults() *AlertserviceZendeskDetails {
	this := AlertserviceZendeskDetails{}
	return &this
}

// GetZendeskApiToken returns the ZendeskApiToken field value if set, zero value otherwise.
func (o *AlertserviceZendeskDetails) GetZendeskApiToken() string {
	if o == nil || IsNil(o.ZendeskApiToken) {
		var ret string
		return ret
	}
	return *o.ZendeskApiToken
}

// GetZendeskApiTokenOk returns a tuple with the ZendeskApiToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertserviceZendeskDetails) GetZendeskApiTokenOk() (*string, bool) {
	if o == nil || IsNil(o.ZendeskApiToken) {
		return nil, false
	}
	return o.ZendeskApiToken, true
}

// HasZendeskApiToken returns a boolean if a field has been set.
func (o *AlertserviceZendeskDetails) HasZendeskApiToken() bool {
	if o != nil && !IsNil(o.ZendeskApiToken) {
		return true
	}

	return false
}

// SetZendeskApiToken gets a reference to the given string and assigns it to the ZendeskApiToken field.
func (o *AlertserviceZendeskDetails) SetZendeskApiToken(v string) {
	o.ZendeskApiToken = &v
}

// GetZendeskAssigneeId returns the ZendeskAssigneeId field value
func (o *AlertserviceZendeskDetails) GetZendeskAssigneeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZendeskAssigneeId
}

// GetZendeskAssigneeIdOk returns a tuple with the ZendeskAssigneeId field value
// and a boolean to check if the value has been set.
func (o *AlertserviceZendeskDetails) GetZendeskAssigneeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZendeskAssigneeId, true
}

// SetZendeskAssigneeId sets field value
func (o *AlertserviceZendeskDetails) SetZendeskAssigneeId(v string) {
	o.ZendeskAssigneeId = v
}

// GetZendeskBaseUrl returns the ZendeskBaseUrl field value
func (o *AlertserviceZendeskDetails) GetZendeskBaseUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZendeskBaseUrl
}

// GetZendeskBaseUrlOk returns a tuple with the ZendeskBaseUrl field value
// and a boolean to check if the value has been set.
func (o *AlertserviceZendeskDetails) GetZendeskBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZendeskBaseUrl, true
}

// SetZendeskBaseUrl sets field value
func (o *AlertserviceZendeskDetails) SetZendeskBaseUrl(v string) {
	o.ZendeskBaseUrl = v
}

// GetZendeskClientId returns the ZendeskClientId field value
func (o *AlertserviceZendeskDetails) GetZendeskClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZendeskClientId
}

// GetZendeskClientIdOk returns a tuple with the ZendeskClientId field value
// and a boolean to check if the value has been set.
func (o *AlertserviceZendeskDetails) GetZendeskClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZendeskClientId, true
}

// SetZendeskClientId sets field value
func (o *AlertserviceZendeskDetails) SetZendeskClientId(v string) {
	o.ZendeskClientId = v
}

// GetZendeskClientSecret returns the ZendeskClientSecret field value
func (o *AlertserviceZendeskDetails) GetZendeskClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZendeskClientSecret
}

// GetZendeskClientSecretOk returns a tuple with the ZendeskClientSecret field value
// and a boolean to check if the value has been set.
func (o *AlertserviceZendeskDetails) GetZendeskClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZendeskClientSecret, true
}

// SetZendeskClientSecret sets field value
func (o *AlertserviceZendeskDetails) SetZendeskClientSecret(v string) {
	o.ZendeskClientSecret = v
}

// GetZendeskEmail returns the ZendeskEmail field value if set, zero value otherwise.
func (o *AlertserviceZendeskDetails) GetZendeskEmail() string {
	if o == nil || IsNil(o.ZendeskEmail) {
		var ret string
		return ret
	}
	return *o.ZendeskEmail
}

// GetZendeskEmailOk returns a tuple with the ZendeskEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertserviceZendeskDetails) GetZendeskEmailOk() (*string, bool) {
	if o == nil || IsNil(o.ZendeskEmail) {
		return nil, false
	}
	return o.ZendeskEmail, true
}

// HasZendeskEmail returns a boolean if a field has been set.
func (o *AlertserviceZendeskDetails) HasZendeskEmail() bool {
	if o != nil && !IsNil(o.ZendeskEmail) {
		return true
	}

	return false
}

// SetZendeskEmail gets a reference to the given string and assigns it to the ZendeskEmail field.
func (o *AlertserviceZendeskDetails) SetZendeskEmail(v string) {
	o.ZendeskEmail = &v
}

func (o AlertserviceZendeskDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertserviceZendeskDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ZendeskApiToken) {
		toSerialize["zendeskApiToken"] = o.ZendeskApiToken
	}
	toSerialize["zendeskAssigneeId"] = o.ZendeskAssigneeId
	toSerialize["zendeskBaseUrl"] = o.ZendeskBaseUrl
	toSerialize["zendeskClientId"] = o.ZendeskClientId
	toSerialize["zendeskClientSecret"] = o.ZendeskClientSecret
	if !IsNil(o.ZendeskEmail) {
		toSerialize["zendeskEmail"] = o.ZendeskEmail
	}
	return toSerialize, nil
}

func (o *AlertserviceZendeskDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"zendeskAssigneeId",
		"zendeskBaseUrl",
		"zendeskClientId",
		"zendeskClientSecret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlertserviceZendeskDetails := _AlertserviceZendeskDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAlertserviceZendeskDetails)

	if err != nil {
		return err
	}

	*o = AlertserviceZendeskDetails(varAlertserviceZendeskDetails)

	return err
}

type NullableAlertserviceZendeskDetails struct {
	value *AlertserviceZendeskDetails
	isSet bool
}

func (v NullableAlertserviceZendeskDetails) Get() *AlertserviceZendeskDetails {
	return v.value
}

func (v *NullableAlertserviceZendeskDetails) Set(val *AlertserviceZendeskDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertserviceZendeskDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertserviceZendeskDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertserviceZendeskDetails(val *AlertserviceZendeskDetails) *NullableAlertserviceZendeskDetails {
	return &NullableAlertserviceZendeskDetails{value: val, isSet: true}
}

func (v NullableAlertserviceZendeskDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertserviceZendeskDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


