/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SoftwareRolloutsIdGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SoftwareRolloutsIdGetResponse{}

// V1SoftwareRolloutsIdGetResponse struct for V1SoftwareRolloutsIdGetResponse
type V1SoftwareRolloutsIdGetResponse struct {
	Rollout *UpgradeRollout `json:"rollout,omitempty"`
}

// NewV1SoftwareRolloutsIdGetResponse instantiates a new V1SoftwareRolloutsIdGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SoftwareRolloutsIdGetResponse() *V1SoftwareRolloutsIdGetResponse {
	this := V1SoftwareRolloutsIdGetResponse{}
	return &this
}

// NewV1SoftwareRolloutsIdGetResponseWithDefaults instantiates a new V1SoftwareRolloutsIdGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SoftwareRolloutsIdGetResponseWithDefaults() *V1SoftwareRolloutsIdGetResponse {
	this := V1SoftwareRolloutsIdGetResponse{}
	return &this
}

// GetRollout returns the Rollout field value if set, zero value otherwise.
func (o *V1SoftwareRolloutsIdGetResponse) GetRollout() UpgradeRollout {
	if o == nil || IsNil(o.Rollout) {
		var ret UpgradeRollout
		return ret
	}
	return *o.Rollout
}

// GetRolloutOk returns a tuple with the Rollout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SoftwareRolloutsIdGetResponse) GetRolloutOk() (*UpgradeRollout, bool) {
	if o == nil || IsNil(o.Rollout) {
		return nil, false
	}
	return o.Rollout, true
}

// HasRollout returns a boolean if a field has been set.
func (o *V1SoftwareRolloutsIdGetResponse) HasRollout() bool {
	if o != nil && !IsNil(o.Rollout) {
		return true
	}

	return false
}

// SetRollout gets a reference to the given UpgradeRollout and assigns it to the Rollout field.
func (o *V1SoftwareRolloutsIdGetResponse) SetRollout(v UpgradeRollout) {
	o.Rollout = &v
}

func (o V1SoftwareRolloutsIdGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SoftwareRolloutsIdGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rollout) {
		toSerialize["rollout"] = o.Rollout
	}
	return toSerialize, nil
}

type NullableV1SoftwareRolloutsIdGetResponse struct {
	value *V1SoftwareRolloutsIdGetResponse
	isSet bool
}

func (v NullableV1SoftwareRolloutsIdGetResponse) Get() *V1SoftwareRolloutsIdGetResponse {
	return v.value
}

func (v *NullableV1SoftwareRolloutsIdGetResponse) Set(val *V1SoftwareRolloutsIdGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SoftwareRolloutsIdGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SoftwareRolloutsIdGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SoftwareRolloutsIdGetResponse(val *V1SoftwareRolloutsIdGetResponse) *NullableV1SoftwareRolloutsIdGetResponse {
	return &NullableV1SoftwareRolloutsIdGetResponse{value: val, isSet: true}
}

func (v NullableV1SoftwareRolloutsIdGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SoftwareRolloutsIdGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


