/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ManaV2PublicVifConsumerLanSegment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2PublicVifConsumerLanSegment{}

// ManaV2PublicVifConsumerLanSegment struct for ManaV2PublicVifConsumerLanSegment
type ManaV2PublicVifConsumerLanSegment struct {
	AllowedPrefixes []string `json:"allowedPrefixes"`
	// LAN segment ID for the service (required)
	ServiceLanSegment int64 `json:"serviceLanSegment"`
}

type _ManaV2PublicVifConsumerLanSegment ManaV2PublicVifConsumerLanSegment

// NewManaV2PublicVifConsumerLanSegment instantiates a new ManaV2PublicVifConsumerLanSegment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2PublicVifConsumerLanSegment(allowedPrefixes []string, serviceLanSegment int64) *ManaV2PublicVifConsumerLanSegment {
	this := ManaV2PublicVifConsumerLanSegment{}
	this.AllowedPrefixes = allowedPrefixes
	this.ServiceLanSegment = serviceLanSegment
	return &this
}

// NewManaV2PublicVifConsumerLanSegmentWithDefaults instantiates a new ManaV2PublicVifConsumerLanSegment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2PublicVifConsumerLanSegmentWithDefaults() *ManaV2PublicVifConsumerLanSegment {
	this := ManaV2PublicVifConsumerLanSegment{}
	return &this
}

// GetAllowedPrefixes returns the AllowedPrefixes field value
func (o *ManaV2PublicVifConsumerLanSegment) GetAllowedPrefixes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AllowedPrefixes
}

// GetAllowedPrefixesOk returns a tuple with the AllowedPrefixes field value
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifConsumerLanSegment) GetAllowedPrefixesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AllowedPrefixes, true
}

// SetAllowedPrefixes sets field value
func (o *ManaV2PublicVifConsumerLanSegment) SetAllowedPrefixes(v []string) {
	o.AllowedPrefixes = v
}

// GetServiceLanSegment returns the ServiceLanSegment field value
func (o *ManaV2PublicVifConsumerLanSegment) GetServiceLanSegment() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ServiceLanSegment
}

// GetServiceLanSegmentOk returns a tuple with the ServiceLanSegment field value
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifConsumerLanSegment) GetServiceLanSegmentOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceLanSegment, true
}

// SetServiceLanSegment sets field value
func (o *ManaV2PublicVifConsumerLanSegment) SetServiceLanSegment(v int64) {
	o.ServiceLanSegment = v
}

func (o ManaV2PublicVifConsumerLanSegment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2PublicVifConsumerLanSegment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["allowedPrefixes"] = o.AllowedPrefixes
	toSerialize["serviceLanSegment"] = o.ServiceLanSegment
	return toSerialize, nil
}

func (o *ManaV2PublicVifConsumerLanSegment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"allowedPrefixes",
		"serviceLanSegment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManaV2PublicVifConsumerLanSegment := _ManaV2PublicVifConsumerLanSegment{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManaV2PublicVifConsumerLanSegment)

	if err != nil {
		return err
	}

	*o = ManaV2PublicVifConsumerLanSegment(varManaV2PublicVifConsumerLanSegment)

	return err
}

type NullableManaV2PublicVifConsumerLanSegment struct {
	value *ManaV2PublicVifConsumerLanSegment
	isSet bool
}

func (v NullableManaV2PublicVifConsumerLanSegment) Get() *ManaV2PublicVifConsumerLanSegment {
	return v.value
}

func (v *NullableManaV2PublicVifConsumerLanSegment) Set(val *ManaV2PublicVifConsumerLanSegment) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2PublicVifConsumerLanSegment) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2PublicVifConsumerLanSegment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2PublicVifConsumerLanSegment(val *ManaV2PublicVifConsumerLanSegment) *NullableManaV2PublicVifConsumerLanSegment {
	return &NullableManaV2PublicVifConsumerLanSegment{value: val, isSet: true}
}

func (v NullableManaV2PublicVifConsumerLanSegment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2PublicVifConsumerLanSegment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


