/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2PublicVifConsumerPolicyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2PublicVifConsumerPolicyResponse{}

// ManaV2PublicVifConsumerPolicyResponse struct for ManaV2PublicVifConsumerPolicyResponse
type ManaV2PublicVifConsumerPolicyResponse struct {
	ConsumerServiceId *int64 `json:"consumerServiceId,omitempty"`
	LanSegments []ManaV2PublicVifConsumerLanSegmentResponse `json:"lanSegments,omitempty"`
	Sites *ManaV2SiteInformation `json:"sites,omitempty"`
}

// NewManaV2PublicVifConsumerPolicyResponse instantiates a new ManaV2PublicVifConsumerPolicyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2PublicVifConsumerPolicyResponse() *ManaV2PublicVifConsumerPolicyResponse {
	this := ManaV2PublicVifConsumerPolicyResponse{}
	return &this
}

// NewManaV2PublicVifConsumerPolicyResponseWithDefaults instantiates a new ManaV2PublicVifConsumerPolicyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2PublicVifConsumerPolicyResponseWithDefaults() *ManaV2PublicVifConsumerPolicyResponse {
	this := ManaV2PublicVifConsumerPolicyResponse{}
	return &this
}

// GetConsumerServiceId returns the ConsumerServiceId field value if set, zero value otherwise.
func (o *ManaV2PublicVifConsumerPolicyResponse) GetConsumerServiceId() int64 {
	if o == nil || IsNil(o.ConsumerServiceId) {
		var ret int64
		return ret
	}
	return *o.ConsumerServiceId
}

// GetConsumerServiceIdOk returns a tuple with the ConsumerServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifConsumerPolicyResponse) GetConsumerServiceIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ConsumerServiceId) {
		return nil, false
	}
	return o.ConsumerServiceId, true
}

// HasConsumerServiceId returns a boolean if a field has been set.
func (o *ManaV2PublicVifConsumerPolicyResponse) HasConsumerServiceId() bool {
	if o != nil && !IsNil(o.ConsumerServiceId) {
		return true
	}

	return false
}

// SetConsumerServiceId gets a reference to the given int64 and assigns it to the ConsumerServiceId field.
func (o *ManaV2PublicVifConsumerPolicyResponse) SetConsumerServiceId(v int64) {
	o.ConsumerServiceId = &v
}

// GetLanSegments returns the LanSegments field value if set, zero value otherwise.
func (o *ManaV2PublicVifConsumerPolicyResponse) GetLanSegments() []ManaV2PublicVifConsumerLanSegmentResponse {
	if o == nil || IsNil(o.LanSegments) {
		var ret []ManaV2PublicVifConsumerLanSegmentResponse
		return ret
	}
	return o.LanSegments
}

// GetLanSegmentsOk returns a tuple with the LanSegments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifConsumerPolicyResponse) GetLanSegmentsOk() ([]ManaV2PublicVifConsumerLanSegmentResponse, bool) {
	if o == nil || IsNil(o.LanSegments) {
		return nil, false
	}
	return o.LanSegments, true
}

// HasLanSegments returns a boolean if a field has been set.
func (o *ManaV2PublicVifConsumerPolicyResponse) HasLanSegments() bool {
	if o != nil && !IsNil(o.LanSegments) {
		return true
	}

	return false
}

// SetLanSegments gets a reference to the given []ManaV2PublicVifConsumerLanSegmentResponse and assigns it to the LanSegments field.
func (o *ManaV2PublicVifConsumerPolicyResponse) SetLanSegments(v []ManaV2PublicVifConsumerLanSegmentResponse) {
	o.LanSegments = v
}

// GetSites returns the Sites field value if set, zero value otherwise.
func (o *ManaV2PublicVifConsumerPolicyResponse) GetSites() ManaV2SiteInformation {
	if o == nil || IsNil(o.Sites) {
		var ret ManaV2SiteInformation
		return ret
	}
	return *o.Sites
}

// GetSitesOk returns a tuple with the Sites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifConsumerPolicyResponse) GetSitesOk() (*ManaV2SiteInformation, bool) {
	if o == nil || IsNil(o.Sites) {
		return nil, false
	}
	return o.Sites, true
}

// HasSites returns a boolean if a field has been set.
func (o *ManaV2PublicVifConsumerPolicyResponse) HasSites() bool {
	if o != nil && !IsNil(o.Sites) {
		return true
	}

	return false
}

// SetSites gets a reference to the given ManaV2SiteInformation and assigns it to the Sites field.
func (o *ManaV2PublicVifConsumerPolicyResponse) SetSites(v ManaV2SiteInformation) {
	o.Sites = &v
}

func (o ManaV2PublicVifConsumerPolicyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2PublicVifConsumerPolicyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConsumerServiceId) {
		toSerialize["consumerServiceId"] = o.ConsumerServiceId
	}
	if !IsNil(o.LanSegments) {
		toSerialize["lanSegments"] = o.LanSegments
	}
	if !IsNil(o.Sites) {
		toSerialize["sites"] = o.Sites
	}
	return toSerialize, nil
}

type NullableManaV2PublicVifConsumerPolicyResponse struct {
	value *ManaV2PublicVifConsumerPolicyResponse
	isSet bool
}

func (v NullableManaV2PublicVifConsumerPolicyResponse) Get() *ManaV2PublicVifConsumerPolicyResponse {
	return v.value
}

func (v *NullableManaV2PublicVifConsumerPolicyResponse) Set(val *ManaV2PublicVifConsumerPolicyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2PublicVifConsumerPolicyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2PublicVifConsumerPolicyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2PublicVifConsumerPolicyResponse(val *ManaV2PublicVifConsumerPolicyResponse) *NullableManaV2PublicVifConsumerPolicyResponse {
	return &NullableManaV2PublicVifConsumerPolicyResponse{value: val, isSet: true}
}

func (v NullableManaV2PublicVifConsumerPolicyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2PublicVifConsumerPolicyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


