/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2ZeroTrustConsumptionSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2ZeroTrustConsumptionSummary{}

// ManaV2ZeroTrustConsumptionSummary struct for ManaV2ZeroTrustConsumptionSummary
type ManaV2ZeroTrustConsumptionSummary struct {
	// Number of devices that have been installed with the zero trust agent
	UserAgentCredits *float32 `json:"userAgentCredits,omitempty"`
}

// NewManaV2ZeroTrustConsumptionSummary instantiates a new ManaV2ZeroTrustConsumptionSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2ZeroTrustConsumptionSummary() *ManaV2ZeroTrustConsumptionSummary {
	this := ManaV2ZeroTrustConsumptionSummary{}
	return &this
}

// NewManaV2ZeroTrustConsumptionSummaryWithDefaults instantiates a new ManaV2ZeroTrustConsumptionSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2ZeroTrustConsumptionSummaryWithDefaults() *ManaV2ZeroTrustConsumptionSummary {
	this := ManaV2ZeroTrustConsumptionSummary{}
	return &this
}

// GetUserAgentCredits returns the UserAgentCredits field value if set, zero value otherwise.
func (o *ManaV2ZeroTrustConsumptionSummary) GetUserAgentCredits() float32 {
	if o == nil || IsNil(o.UserAgentCredits) {
		var ret float32
		return ret
	}
	return *o.UserAgentCredits
}

// GetUserAgentCreditsOk returns a tuple with the UserAgentCredits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ZeroTrustConsumptionSummary) GetUserAgentCreditsOk() (*float32, bool) {
	if o == nil || IsNil(o.UserAgentCredits) {
		return nil, false
	}
	return o.UserAgentCredits, true
}

// HasUserAgentCredits returns a boolean if a field has been set.
func (o *ManaV2ZeroTrustConsumptionSummary) HasUserAgentCredits() bool {
	if o != nil && !IsNil(o.UserAgentCredits) {
		return true
	}

	return false
}

// SetUserAgentCredits gets a reference to the given float32 and assigns it to the UserAgentCredits field.
func (o *ManaV2ZeroTrustConsumptionSummary) SetUserAgentCredits(v float32) {
	o.UserAgentCredits = &v
}

func (o ManaV2ZeroTrustConsumptionSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2ZeroTrustConsumptionSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserAgentCredits) {
		toSerialize["userAgentCredits"] = o.UserAgentCredits
	}
	return toSerialize, nil
}

type NullableManaV2ZeroTrustConsumptionSummary struct {
	value *ManaV2ZeroTrustConsumptionSummary
	isSet bool
}

func (v NullableManaV2ZeroTrustConsumptionSummary) Get() *ManaV2ZeroTrustConsumptionSummary {
	return v.value
}

func (v *NullableManaV2ZeroTrustConsumptionSummary) Set(val *ManaV2ZeroTrustConsumptionSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2ZeroTrustConsumptionSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2ZeroTrustConsumptionSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2ZeroTrustConsumptionSummary(val *ManaV2ZeroTrustConsumptionSummary) *NullableManaV2ZeroTrustConsumptionSummary {
	return &NullableManaV2ZeroTrustConsumptionSummary{value: val, isSet: true}
}

func (v NullableManaV2ZeroTrustConsumptionSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2ZeroTrustConsumptionSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


