/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V2AssuranceReadAiAdoptionApproveEntriesGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2AssuranceReadAiAdoptionApproveEntriesGetResponse{}

// V2AssuranceReadAiAdoptionApproveEntriesGetResponse struct for V2AssuranceReadAiAdoptionApproveEntriesGetResponse
type V2AssuranceReadAiAdoptionApproveEntriesGetResponse struct {
	ApprovedAppList []AssuranceApprovedAppEntry `json:"approvedAppList,omitempty"`
}

// NewV2AssuranceReadAiAdoptionApproveEntriesGetResponse instantiates a new V2AssuranceReadAiAdoptionApproveEntriesGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2AssuranceReadAiAdoptionApproveEntriesGetResponse() *V2AssuranceReadAiAdoptionApproveEntriesGetResponse {
	this := V2AssuranceReadAiAdoptionApproveEntriesGetResponse{}
	return &this
}

// NewV2AssuranceReadAiAdoptionApproveEntriesGetResponseWithDefaults instantiates a new V2AssuranceReadAiAdoptionApproveEntriesGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2AssuranceReadAiAdoptionApproveEntriesGetResponseWithDefaults() *V2AssuranceReadAiAdoptionApproveEntriesGetResponse {
	this := V2AssuranceReadAiAdoptionApproveEntriesGetResponse{}
	return &this
}

// GetApprovedAppList returns the ApprovedAppList field value if set, zero value otherwise.
func (o *V2AssuranceReadAiAdoptionApproveEntriesGetResponse) GetApprovedAppList() []AssuranceApprovedAppEntry {
	if o == nil || IsNil(o.ApprovedAppList) {
		var ret []AssuranceApprovedAppEntry
		return ret
	}
	return o.ApprovedAppList
}

// GetApprovedAppListOk returns a tuple with the ApprovedAppList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceReadAiAdoptionApproveEntriesGetResponse) GetApprovedAppListOk() ([]AssuranceApprovedAppEntry, bool) {
	if o == nil || IsNil(o.ApprovedAppList) {
		return nil, false
	}
	return o.ApprovedAppList, true
}

// HasApprovedAppList returns a boolean if a field has been set.
func (o *V2AssuranceReadAiAdoptionApproveEntriesGetResponse) HasApprovedAppList() bool {
	if o != nil && !IsNil(o.ApprovedAppList) {
		return true
	}

	return false
}

// SetApprovedAppList gets a reference to the given []AssuranceApprovedAppEntry and assigns it to the ApprovedAppList field.
func (o *V2AssuranceReadAiAdoptionApproveEntriesGetResponse) SetApprovedAppList(v []AssuranceApprovedAppEntry) {
	o.ApprovedAppList = v
}

func (o V2AssuranceReadAiAdoptionApproveEntriesGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2AssuranceReadAiAdoptionApproveEntriesGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApprovedAppList) {
		toSerialize["approvedAppList"] = o.ApprovedAppList
	}
	return toSerialize, nil
}

type NullableV2AssuranceReadAiAdoptionApproveEntriesGetResponse struct {
	value *V2AssuranceReadAiAdoptionApproveEntriesGetResponse
	isSet bool
}

func (v NullableV2AssuranceReadAiAdoptionApproveEntriesGetResponse) Get() *V2AssuranceReadAiAdoptionApproveEntriesGetResponse {
	return v.value
}

func (v *NullableV2AssuranceReadAiAdoptionApproveEntriesGetResponse) Set(val *V2AssuranceReadAiAdoptionApproveEntriesGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AssuranceReadAiAdoptionApproveEntriesGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AssuranceReadAiAdoptionApproveEntriesGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AssuranceReadAiAdoptionApproveEntriesGetResponse(val *V2AssuranceReadAiAdoptionApproveEntriesGetResponse) *NullableV2AssuranceReadAiAdoptionApproveEntriesGetResponse {
	return &NullableV2AssuranceReadAiAdoptionApproveEntriesGetResponse{value: val, isSet: true}
}

func (v NullableV2AssuranceReadAiAdoptionApproveEntriesGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AssuranceReadAiAdoptionApproveEntriesGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


