/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2NullableOspfAuthenticationConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2NullableOspfAuthenticationConfig{}

// ManaV2NullableOspfAuthenticationConfig struct for ManaV2NullableOspfAuthenticationConfig
type ManaV2NullableOspfAuthenticationConfig struct {
	Authentication map[string]interface{} `json:"authentication,omitempty"`
}

// NewManaV2NullableOspfAuthenticationConfig instantiates a new ManaV2NullableOspfAuthenticationConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2NullableOspfAuthenticationConfig() *ManaV2NullableOspfAuthenticationConfig {
	this := ManaV2NullableOspfAuthenticationConfig{}
	return &this
}

// NewManaV2NullableOspfAuthenticationConfigWithDefaults instantiates a new ManaV2NullableOspfAuthenticationConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2NullableOspfAuthenticationConfigWithDefaults() *ManaV2NullableOspfAuthenticationConfig {
	this := ManaV2NullableOspfAuthenticationConfig{}
	return &this
}

// GetAuthentication returns the Authentication field value if set, zero value otherwise.
func (o *ManaV2NullableOspfAuthenticationConfig) GetAuthentication() map[string]interface{} {
	if o == nil || IsNil(o.Authentication) {
		var ret map[string]interface{}
		return ret
	}
	return o.Authentication
}

// GetAuthenticationOk returns a tuple with the Authentication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2NullableOspfAuthenticationConfig) GetAuthenticationOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Authentication) {
		return map[string]interface{}{}, false
	}
	return o.Authentication, true
}

// HasAuthentication returns a boolean if a field has been set.
func (o *ManaV2NullableOspfAuthenticationConfig) HasAuthentication() bool {
	if o != nil && !IsNil(o.Authentication) {
		return true
	}

	return false
}

// SetAuthentication gets a reference to the given map[string]interface{} and assigns it to the Authentication field.
func (o *ManaV2NullableOspfAuthenticationConfig) SetAuthentication(v map[string]interface{}) {
	o.Authentication = v
}

func (o ManaV2NullableOspfAuthenticationConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2NullableOspfAuthenticationConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Authentication) {
		toSerialize["authentication"] = o.Authentication
	}
	return toSerialize, nil
}

type NullableManaV2NullableOspfAuthenticationConfig struct {
	value *ManaV2NullableOspfAuthenticationConfig
	isSet bool
}

func (v NullableManaV2NullableOspfAuthenticationConfig) Get() *ManaV2NullableOspfAuthenticationConfig {
	return v.value
}

func (v *NullableManaV2NullableOspfAuthenticationConfig) Set(val *ManaV2NullableOspfAuthenticationConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2NullableOspfAuthenticationConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2NullableOspfAuthenticationConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2NullableOspfAuthenticationConfig(val *ManaV2NullableOspfAuthenticationConfig) *NullableManaV2NullableOspfAuthenticationConfig {
	return &NullableManaV2NullableOspfAuthenticationConfig{value: val, isSet: true}
}

func (v NullableManaV2NullableOspfAuthenticationConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2NullableOspfAuthenticationConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


