/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2ExtranetServicePolicyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2ExtranetServicePolicyResponse{}

// ManaV2ExtranetServicePolicyResponse struct for ManaV2ExtranetServicePolicyResponse
type ManaV2ExtranetServicePolicyResponse struct {
	Policy *ManaV2ExtranetServiceProducerPolicy `json:"policy,omitempty"`
	ServiceName *string `json:"serviceName,omitempty"`
	ServiceType *string `json:"serviceType,omitempty"`
}

// NewManaV2ExtranetServicePolicyResponse instantiates a new ManaV2ExtranetServicePolicyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2ExtranetServicePolicyResponse() *ManaV2ExtranetServicePolicyResponse {
	this := ManaV2ExtranetServicePolicyResponse{}
	return &this
}

// NewManaV2ExtranetServicePolicyResponseWithDefaults instantiates a new ManaV2ExtranetServicePolicyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2ExtranetServicePolicyResponseWithDefaults() *ManaV2ExtranetServicePolicyResponse {
	this := ManaV2ExtranetServicePolicyResponse{}
	return &this
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *ManaV2ExtranetServicePolicyResponse) GetPolicy() ManaV2ExtranetServiceProducerPolicy {
	if o == nil || IsNil(o.Policy) {
		var ret ManaV2ExtranetServiceProducerPolicy
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServicePolicyResponse) GetPolicyOk() (*ManaV2ExtranetServiceProducerPolicy, bool) {
	if o == nil || IsNil(o.Policy) {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *ManaV2ExtranetServicePolicyResponse) HasPolicy() bool {
	if o != nil && !IsNil(o.Policy) {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given ManaV2ExtranetServiceProducerPolicy and assigns it to the Policy field.
func (o *ManaV2ExtranetServicePolicyResponse) SetPolicy(v ManaV2ExtranetServiceProducerPolicy) {
	o.Policy = &v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise.
func (o *ManaV2ExtranetServicePolicyResponse) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName) {
		var ret string
		return ret
	}
	return *o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServicePolicyResponse) GetServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceName) {
		return nil, false
	}
	return o.ServiceName, true
}

// HasServiceName returns a boolean if a field has been set.
func (o *ManaV2ExtranetServicePolicyResponse) HasServiceName() bool {
	if o != nil && !IsNil(o.ServiceName) {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given string and assigns it to the ServiceName field.
func (o *ManaV2ExtranetServicePolicyResponse) SetServiceName(v string) {
	o.ServiceName = &v
}

// GetServiceType returns the ServiceType field value if set, zero value otherwise.
func (o *ManaV2ExtranetServicePolicyResponse) GetServiceType() string {
	if o == nil || IsNil(o.ServiceType) {
		var ret string
		return ret
	}
	return *o.ServiceType
}

// GetServiceTypeOk returns a tuple with the ServiceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServicePolicyResponse) GetServiceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceType) {
		return nil, false
	}
	return o.ServiceType, true
}

// HasServiceType returns a boolean if a field has been set.
func (o *ManaV2ExtranetServicePolicyResponse) HasServiceType() bool {
	if o != nil && !IsNil(o.ServiceType) {
		return true
	}

	return false
}

// SetServiceType gets a reference to the given string and assigns it to the ServiceType field.
func (o *ManaV2ExtranetServicePolicyResponse) SetServiceType(v string) {
	o.ServiceType = &v
}

func (o ManaV2ExtranetServicePolicyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2ExtranetServicePolicyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Policy) {
		toSerialize["policy"] = o.Policy
	}
	if !IsNil(o.ServiceName) {
		toSerialize["serviceName"] = o.ServiceName
	}
	if !IsNil(o.ServiceType) {
		toSerialize["serviceType"] = o.ServiceType
	}
	return toSerialize, nil
}

type NullableManaV2ExtranetServicePolicyResponse struct {
	value *ManaV2ExtranetServicePolicyResponse
	isSet bool
}

func (v NullableManaV2ExtranetServicePolicyResponse) Get() *ManaV2ExtranetServicePolicyResponse {
	return v.value
}

func (v *NullableManaV2ExtranetServicePolicyResponse) Set(val *ManaV2ExtranetServicePolicyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2ExtranetServicePolicyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2ExtranetServicePolicyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2ExtranetServicePolicyResponse(val *ManaV2ExtranetServicePolicyResponse) *NullableManaV2ExtranetServicePolicyResponse {
	return &NullableManaV2ExtranetServicePolicyResponse{value: val, isSet: true}
}

func (v NullableManaV2ExtranetServicePolicyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2ExtranetServicePolicyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


