/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2GlobalContentFilterConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2GlobalContentFilterConfig{}

// ManaV2GlobalContentFilterConfig struct for ManaV2GlobalContentFilterConfig
type ManaV2GlobalContentFilterConfig struct {
	LanNames []string `json:"lanNames,omitempty"`
	// Display name for this global content filter configuration.
	Name *string `json:"name,omitempty"`
	Rules []ManaV2GlobalContentFilterRule `json:"rules,omitempty"`
	// Site list whose members this content filter applies to; omit the oneof when no site scope is set.
	SiteListId *int64 `json:"siteListId,omitempty"`
	// When true, the filter applies to all sites in the tenant (must be the constant true).
	UseAllSites *bool `json:"useAllSites,omitempty"`
}

// NewManaV2GlobalContentFilterConfig instantiates a new ManaV2GlobalContentFilterConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2GlobalContentFilterConfig() *ManaV2GlobalContentFilterConfig {
	this := ManaV2GlobalContentFilterConfig{}
	return &this
}

// NewManaV2GlobalContentFilterConfigWithDefaults instantiates a new ManaV2GlobalContentFilterConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2GlobalContentFilterConfigWithDefaults() *ManaV2GlobalContentFilterConfig {
	this := ManaV2GlobalContentFilterConfig{}
	return &this
}

// GetLanNames returns the LanNames field value if set, zero value otherwise.
func (o *ManaV2GlobalContentFilterConfig) GetLanNames() []string {
	if o == nil || IsNil(o.LanNames) {
		var ret []string
		return ret
	}
	return o.LanNames
}

// GetLanNamesOk returns a tuple with the LanNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2GlobalContentFilterConfig) GetLanNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.LanNames) {
		return nil, false
	}
	return o.LanNames, true
}

// HasLanNames returns a boolean if a field has been set.
func (o *ManaV2GlobalContentFilterConfig) HasLanNames() bool {
	if o != nil && !IsNil(o.LanNames) {
		return true
	}

	return false
}

// SetLanNames gets a reference to the given []string and assigns it to the LanNames field.
func (o *ManaV2GlobalContentFilterConfig) SetLanNames(v []string) {
	o.LanNames = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ManaV2GlobalContentFilterConfig) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2GlobalContentFilterConfig) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ManaV2GlobalContentFilterConfig) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ManaV2GlobalContentFilterConfig) SetName(v string) {
	o.Name = &v
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *ManaV2GlobalContentFilterConfig) GetRules() []ManaV2GlobalContentFilterRule {
	if o == nil || IsNil(o.Rules) {
		var ret []ManaV2GlobalContentFilterRule
		return ret
	}
	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2GlobalContentFilterConfig) GetRulesOk() ([]ManaV2GlobalContentFilterRule, bool) {
	if o == nil || IsNil(o.Rules) {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *ManaV2GlobalContentFilterConfig) HasRules() bool {
	if o != nil && !IsNil(o.Rules) {
		return true
	}

	return false
}

// SetRules gets a reference to the given []ManaV2GlobalContentFilterRule and assigns it to the Rules field.
func (o *ManaV2GlobalContentFilterConfig) SetRules(v []ManaV2GlobalContentFilterRule) {
	o.Rules = v
}

// GetSiteListId returns the SiteListId field value if set, zero value otherwise.
func (o *ManaV2GlobalContentFilterConfig) GetSiteListId() int64 {
	if o == nil || IsNil(o.SiteListId) {
		var ret int64
		return ret
	}
	return *o.SiteListId
}

// GetSiteListIdOk returns a tuple with the SiteListId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2GlobalContentFilterConfig) GetSiteListIdOk() (*int64, bool) {
	if o == nil || IsNil(o.SiteListId) {
		return nil, false
	}
	return o.SiteListId, true
}

// HasSiteListId returns a boolean if a field has been set.
func (o *ManaV2GlobalContentFilterConfig) HasSiteListId() bool {
	if o != nil && !IsNil(o.SiteListId) {
		return true
	}

	return false
}

// SetSiteListId gets a reference to the given int64 and assigns it to the SiteListId field.
func (o *ManaV2GlobalContentFilterConfig) SetSiteListId(v int64) {
	o.SiteListId = &v
}

// GetUseAllSites returns the UseAllSites field value if set, zero value otherwise.
func (o *ManaV2GlobalContentFilterConfig) GetUseAllSites() bool {
	if o == nil || IsNil(o.UseAllSites) {
		var ret bool
		return ret
	}
	return *o.UseAllSites
}

// GetUseAllSitesOk returns a tuple with the UseAllSites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2GlobalContentFilterConfig) GetUseAllSitesOk() (*bool, bool) {
	if o == nil || IsNil(o.UseAllSites) {
		return nil, false
	}
	return o.UseAllSites, true
}

// HasUseAllSites returns a boolean if a field has been set.
func (o *ManaV2GlobalContentFilterConfig) HasUseAllSites() bool {
	if o != nil && !IsNil(o.UseAllSites) {
		return true
	}

	return false
}

// SetUseAllSites gets a reference to the given bool and assigns it to the UseAllSites field.
func (o *ManaV2GlobalContentFilterConfig) SetUseAllSites(v bool) {
	o.UseAllSites = &v
}

func (o ManaV2GlobalContentFilterConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2GlobalContentFilterConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LanNames) {
		toSerialize["lanNames"] = o.LanNames
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Rules) {
		toSerialize["rules"] = o.Rules
	}
	if !IsNil(o.SiteListId) {
		toSerialize["siteListId"] = o.SiteListId
	}
	if !IsNil(o.UseAllSites) {
		toSerialize["useAllSites"] = o.UseAllSites
	}
	return toSerialize, nil
}

type NullableManaV2GlobalContentFilterConfig struct {
	value *ManaV2GlobalContentFilterConfig
	isSet bool
}

func (v NullableManaV2GlobalContentFilterConfig) Get() *ManaV2GlobalContentFilterConfig {
	return v.value
}

func (v *NullableManaV2GlobalContentFilterConfig) Set(val *ManaV2GlobalContentFilterConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2GlobalContentFilterConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2GlobalContentFilterConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2GlobalContentFilterConfig(val *ManaV2GlobalContentFilterConfig) *NullableManaV2GlobalContentFilterConfig {
	return &NullableManaV2GlobalContentFilterConfig{value: val, isSet: true}
}

func (v NullableManaV2GlobalContentFilterConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2GlobalContentFilterConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


