/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SitesMapDetailsGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SitesMapDetailsGetResponse{}

// V1SitesMapDetailsGetResponse struct for V1SitesMapDetailsGetResponse
type V1SitesMapDetailsGetResponse struct {
	LanSegmentIds *map[string]ManaV2LanSegmentSitesMap `json:"lanSegmentIds,omitempty"`
}

// NewV1SitesMapDetailsGetResponse instantiates a new V1SitesMapDetailsGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SitesMapDetailsGetResponse() *V1SitesMapDetailsGetResponse {
	this := V1SitesMapDetailsGetResponse{}
	return &this
}

// NewV1SitesMapDetailsGetResponseWithDefaults instantiates a new V1SitesMapDetailsGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SitesMapDetailsGetResponseWithDefaults() *V1SitesMapDetailsGetResponse {
	this := V1SitesMapDetailsGetResponse{}
	return &this
}

// GetLanSegmentIds returns the LanSegmentIds field value if set, zero value otherwise.
func (o *V1SitesMapDetailsGetResponse) GetLanSegmentIds() map[string]ManaV2LanSegmentSitesMap {
	if o == nil || IsNil(o.LanSegmentIds) {
		var ret map[string]ManaV2LanSegmentSitesMap
		return ret
	}
	return *o.LanSegmentIds
}

// GetLanSegmentIdsOk returns a tuple with the LanSegmentIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SitesMapDetailsGetResponse) GetLanSegmentIdsOk() (*map[string]ManaV2LanSegmentSitesMap, bool) {
	if o == nil || IsNil(o.LanSegmentIds) {
		return nil, false
	}
	return o.LanSegmentIds, true
}

// HasLanSegmentIds returns a boolean if a field has been set.
func (o *V1SitesMapDetailsGetResponse) HasLanSegmentIds() bool {
	if o != nil && !IsNil(o.LanSegmentIds) {
		return true
	}

	return false
}

// SetLanSegmentIds gets a reference to the given map[string]ManaV2LanSegmentSitesMap and assigns it to the LanSegmentIds field.
func (o *V1SitesMapDetailsGetResponse) SetLanSegmentIds(v map[string]ManaV2LanSegmentSitesMap) {
	o.LanSegmentIds = &v
}

func (o V1SitesMapDetailsGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SitesMapDetailsGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LanSegmentIds) {
		toSerialize["lanSegmentIds"] = o.LanSegmentIds
	}
	return toSerialize, nil
}

type NullableV1SitesMapDetailsGetResponse struct {
	value *V1SitesMapDetailsGetResponse
	isSet bool
}

func (v NullableV1SitesMapDetailsGetResponse) Get() *V1SitesMapDetailsGetResponse {
	return v.value
}

func (v *NullableV1SitesMapDetailsGetResponse) Set(val *V1SitesMapDetailsGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SitesMapDetailsGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SitesMapDetailsGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SitesMapDetailsGetResponse(val *V1SitesMapDetailsGetResponse) *NullableV1SitesMapDetailsGetResponse {
	return &NullableV1SitesMapDetailsGetResponse{value: val, isSet: true}
}

func (v NullableV1SitesMapDetailsGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SitesMapDetailsGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


