/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1GlobalContentFiltersGlobalContentFilterIdPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1GlobalContentFiltersGlobalContentFilterIdPutRequest{}

// V1GlobalContentFiltersGlobalContentFilterIdPutRequest struct for V1GlobalContentFiltersGlobalContentFilterIdPutRequest
type V1GlobalContentFiltersGlobalContentFilterIdPutRequest struct {
	Config *ManaV2GlobalContentFilterConfig `json:"config,omitempty"`
}

// NewV1GlobalContentFiltersGlobalContentFilterIdPutRequest instantiates a new V1GlobalContentFiltersGlobalContentFilterIdPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1GlobalContentFiltersGlobalContentFilterIdPutRequest() *V1GlobalContentFiltersGlobalContentFilterIdPutRequest {
	this := V1GlobalContentFiltersGlobalContentFilterIdPutRequest{}
	return &this
}

// NewV1GlobalContentFiltersGlobalContentFilterIdPutRequestWithDefaults instantiates a new V1GlobalContentFiltersGlobalContentFilterIdPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1GlobalContentFiltersGlobalContentFilterIdPutRequestWithDefaults() *V1GlobalContentFiltersGlobalContentFilterIdPutRequest {
	this := V1GlobalContentFiltersGlobalContentFilterIdPutRequest{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *V1GlobalContentFiltersGlobalContentFilterIdPutRequest) GetConfig() ManaV2GlobalContentFilterConfig {
	if o == nil || IsNil(o.Config) {
		var ret ManaV2GlobalContentFilterConfig
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1GlobalContentFiltersGlobalContentFilterIdPutRequest) GetConfigOk() (*ManaV2GlobalContentFilterConfig, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *V1GlobalContentFiltersGlobalContentFilterIdPutRequest) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given ManaV2GlobalContentFilterConfig and assigns it to the Config field.
func (o *V1GlobalContentFiltersGlobalContentFilterIdPutRequest) SetConfig(v ManaV2GlobalContentFilterConfig) {
	o.Config = &v
}

func (o V1GlobalContentFiltersGlobalContentFilterIdPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1GlobalContentFiltersGlobalContentFilterIdPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return toSerialize, nil
}

type NullableV1GlobalContentFiltersGlobalContentFilterIdPutRequest struct {
	value *V1GlobalContentFiltersGlobalContentFilterIdPutRequest
	isSet bool
}

func (v NullableV1GlobalContentFiltersGlobalContentFilterIdPutRequest) Get() *V1GlobalContentFiltersGlobalContentFilterIdPutRequest {
	return v.value
}

func (v *NullableV1GlobalContentFiltersGlobalContentFilterIdPutRequest) Set(val *V1GlobalContentFiltersGlobalContentFilterIdPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1GlobalContentFiltersGlobalContentFilterIdPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1GlobalContentFiltersGlobalContentFilterIdPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1GlobalContentFiltersGlobalContentFilterIdPutRequest(val *V1GlobalContentFiltersGlobalContentFilterIdPutRequest) *NullableV1GlobalContentFiltersGlobalContentFilterIdPutRequest {
	return &NullableV1GlobalContentFiltersGlobalContentFilterIdPutRequest{value: val, isSet: true}
}

func (v NullableV1GlobalContentFiltersGlobalContentFilterIdPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1GlobalContentFiltersGlobalContentFilterIdPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


