/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2SiteInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2SiteInformation{}

// ManaV2SiteInformation struct for ManaV2SiteInformation
type ManaV2SiteInformation struct {
	SiteLists []int64 `json:"siteLists,omitempty"`
	Sites []int64 `json:"sites,omitempty"`
}

// NewManaV2SiteInformation instantiates a new ManaV2SiteInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2SiteInformation() *ManaV2SiteInformation {
	this := ManaV2SiteInformation{}
	return &this
}

// NewManaV2SiteInformationWithDefaults instantiates a new ManaV2SiteInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2SiteInformationWithDefaults() *ManaV2SiteInformation {
	this := ManaV2SiteInformation{}
	return &this
}

// GetSiteLists returns the SiteLists field value if set, zero value otherwise.
func (o *ManaV2SiteInformation) GetSiteLists() []int64 {
	if o == nil || IsNil(o.SiteLists) {
		var ret []int64
		return ret
	}
	return o.SiteLists
}

// GetSiteListsOk returns a tuple with the SiteLists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2SiteInformation) GetSiteListsOk() ([]int64, bool) {
	if o == nil || IsNil(o.SiteLists) {
		return nil, false
	}
	return o.SiteLists, true
}

// HasSiteLists returns a boolean if a field has been set.
func (o *ManaV2SiteInformation) HasSiteLists() bool {
	if o != nil && !IsNil(o.SiteLists) {
		return true
	}

	return false
}

// SetSiteLists gets a reference to the given []int64 and assigns it to the SiteLists field.
func (o *ManaV2SiteInformation) SetSiteLists(v []int64) {
	o.SiteLists = v
}

// GetSites returns the Sites field value if set, zero value otherwise.
func (o *ManaV2SiteInformation) GetSites() []int64 {
	if o == nil || IsNil(o.Sites) {
		var ret []int64
		return ret
	}
	return o.Sites
}

// GetSitesOk returns a tuple with the Sites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2SiteInformation) GetSitesOk() ([]int64, bool) {
	if o == nil || IsNil(o.Sites) {
		return nil, false
	}
	return o.Sites, true
}

// HasSites returns a boolean if a field has been set.
func (o *ManaV2SiteInformation) HasSites() bool {
	if o != nil && !IsNil(o.Sites) {
		return true
	}

	return false
}

// SetSites gets a reference to the given []int64 and assigns it to the Sites field.
func (o *ManaV2SiteInformation) SetSites(v []int64) {
	o.Sites = v
}

func (o ManaV2SiteInformation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2SiteInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SiteLists) {
		toSerialize["siteLists"] = o.SiteLists
	}
	if !IsNil(o.Sites) {
		toSerialize["sites"] = o.Sites
	}
	return toSerialize, nil
}

type NullableManaV2SiteInformation struct {
	value *ManaV2SiteInformation
	isSet bool
}

func (v NullableManaV2SiteInformation) Get() *ManaV2SiteInformation {
	return v.value
}

func (v *NullableManaV2SiteInformation) Set(val *ManaV2SiteInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2SiteInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2SiteInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2SiteInformation(val *ManaV2SiteInformation) *NullableManaV2SiteInformation {
	return &NullableManaV2SiteInformation{value: val, isSet: true}
}

func (v NullableManaV2SiteInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2SiteInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


