/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2B2bExtranetMatchConsumerDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2B2bExtranetMatchConsumerDetails{}

// ManaV2B2bExtranetMatchConsumerDetails struct for ManaV2B2bExtranetMatchConsumerDetails
type ManaV2B2bExtranetMatchConsumerDetails struct {
	ConsumerId *int64 `json:"consumerId,omitempty"`
	ConsumerPrefixes []string `json:"consumerPrefixes,omitempty"`
	Customer *ManaV2B2BExtranetMatchConsumerDetailsCustomer `json:"customer,omitempty"`
	OldConsumerPrefixes []string `json:"oldConsumerPrefixes,omitempty"`
	OldServicePrefixes []ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix `json:"oldServicePrefixes,omitempty"`
	Service *ManaV2B2BExtranetMatchConsumerDetailsService `json:"service,omitempty"`
	ServicePrefixes []ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix `json:"servicePrefixes,omitempty"`
}

// NewManaV2B2bExtranetMatchConsumerDetails instantiates a new ManaV2B2bExtranetMatchConsumerDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2B2bExtranetMatchConsumerDetails() *ManaV2B2bExtranetMatchConsumerDetails {
	this := ManaV2B2bExtranetMatchConsumerDetails{}
	return &this
}

// NewManaV2B2bExtranetMatchConsumerDetailsWithDefaults instantiates a new ManaV2B2bExtranetMatchConsumerDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2B2bExtranetMatchConsumerDetailsWithDefaults() *ManaV2B2bExtranetMatchConsumerDetails {
	this := ManaV2B2bExtranetMatchConsumerDetails{}
	return &this
}

// GetConsumerId returns the ConsumerId field value if set, zero value otherwise.
func (o *ManaV2B2bExtranetMatchConsumerDetails) GetConsumerId() int64 {
	if o == nil || IsNil(o.ConsumerId) {
		var ret int64
		return ret
	}
	return *o.ConsumerId
}

// GetConsumerIdOk returns a tuple with the ConsumerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2B2bExtranetMatchConsumerDetails) GetConsumerIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ConsumerId) {
		return nil, false
	}
	return o.ConsumerId, true
}

// HasConsumerId returns a boolean if a field has been set.
func (o *ManaV2B2bExtranetMatchConsumerDetails) HasConsumerId() bool {
	if o != nil && !IsNil(o.ConsumerId) {
		return true
	}

	return false
}

// SetConsumerId gets a reference to the given int64 and assigns it to the ConsumerId field.
func (o *ManaV2B2bExtranetMatchConsumerDetails) SetConsumerId(v int64) {
	o.ConsumerId = &v
}

// GetConsumerPrefixes returns the ConsumerPrefixes field value if set, zero value otherwise.
func (o *ManaV2B2bExtranetMatchConsumerDetails) GetConsumerPrefixes() []string {
	if o == nil || IsNil(o.ConsumerPrefixes) {
		var ret []string
		return ret
	}
	return o.ConsumerPrefixes
}

// GetConsumerPrefixesOk returns a tuple with the ConsumerPrefixes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2B2bExtranetMatchConsumerDetails) GetConsumerPrefixesOk() ([]string, bool) {
	if o == nil || IsNil(o.ConsumerPrefixes) {
		return nil, false
	}
	return o.ConsumerPrefixes, true
}

// HasConsumerPrefixes returns a boolean if a field has been set.
func (o *ManaV2B2bExtranetMatchConsumerDetails) HasConsumerPrefixes() bool {
	if o != nil && !IsNil(o.ConsumerPrefixes) {
		return true
	}

	return false
}

// SetConsumerPrefixes gets a reference to the given []string and assigns it to the ConsumerPrefixes field.
func (o *ManaV2B2bExtranetMatchConsumerDetails) SetConsumerPrefixes(v []string) {
	o.ConsumerPrefixes = v
}

// GetCustomer returns the Customer field value if set, zero value otherwise.
func (o *ManaV2B2bExtranetMatchConsumerDetails) GetCustomer() ManaV2B2BExtranetMatchConsumerDetailsCustomer {
	if o == nil || IsNil(o.Customer) {
		var ret ManaV2B2BExtranetMatchConsumerDetailsCustomer
		return ret
	}
	return *o.Customer
}

// GetCustomerOk returns a tuple with the Customer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2B2bExtranetMatchConsumerDetails) GetCustomerOk() (*ManaV2B2BExtranetMatchConsumerDetailsCustomer, bool) {
	if o == nil || IsNil(o.Customer) {
		return nil, false
	}
	return o.Customer, true
}

// HasCustomer returns a boolean if a field has been set.
func (o *ManaV2B2bExtranetMatchConsumerDetails) HasCustomer() bool {
	if o != nil && !IsNil(o.Customer) {
		return true
	}

	return false
}

// SetCustomer gets a reference to the given ManaV2B2BExtranetMatchConsumerDetailsCustomer and assigns it to the Customer field.
func (o *ManaV2B2bExtranetMatchConsumerDetails) SetCustomer(v ManaV2B2BExtranetMatchConsumerDetailsCustomer) {
	o.Customer = &v
}

// GetOldConsumerPrefixes returns the OldConsumerPrefixes field value if set, zero value otherwise.
func (o *ManaV2B2bExtranetMatchConsumerDetails) GetOldConsumerPrefixes() []string {
	if o == nil || IsNil(o.OldConsumerPrefixes) {
		var ret []string
		return ret
	}
	return o.OldConsumerPrefixes
}

// GetOldConsumerPrefixesOk returns a tuple with the OldConsumerPrefixes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2B2bExtranetMatchConsumerDetails) GetOldConsumerPrefixesOk() ([]string, bool) {
	if o == nil || IsNil(o.OldConsumerPrefixes) {
		return nil, false
	}
	return o.OldConsumerPrefixes, true
}

// HasOldConsumerPrefixes returns a boolean if a field has been set.
func (o *ManaV2B2bExtranetMatchConsumerDetails) HasOldConsumerPrefixes() bool {
	if o != nil && !IsNil(o.OldConsumerPrefixes) {
		return true
	}

	return false
}

// SetOldConsumerPrefixes gets a reference to the given []string and assigns it to the OldConsumerPrefixes field.
func (o *ManaV2B2bExtranetMatchConsumerDetails) SetOldConsumerPrefixes(v []string) {
	o.OldConsumerPrefixes = v
}

// GetOldServicePrefixes returns the OldServicePrefixes field value if set, zero value otherwise.
func (o *ManaV2B2bExtranetMatchConsumerDetails) GetOldServicePrefixes() []ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix {
	if o == nil || IsNil(o.OldServicePrefixes) {
		var ret []ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix
		return ret
	}
	return o.OldServicePrefixes
}

// GetOldServicePrefixesOk returns a tuple with the OldServicePrefixes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2B2bExtranetMatchConsumerDetails) GetOldServicePrefixesOk() ([]ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix, bool) {
	if o == nil || IsNil(o.OldServicePrefixes) {
		return nil, false
	}
	return o.OldServicePrefixes, true
}

// HasOldServicePrefixes returns a boolean if a field has been set.
func (o *ManaV2B2bExtranetMatchConsumerDetails) HasOldServicePrefixes() bool {
	if o != nil && !IsNil(o.OldServicePrefixes) {
		return true
	}

	return false
}

// SetOldServicePrefixes gets a reference to the given []ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix and assigns it to the OldServicePrefixes field.
func (o *ManaV2B2bExtranetMatchConsumerDetails) SetOldServicePrefixes(v []ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix) {
	o.OldServicePrefixes = v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *ManaV2B2bExtranetMatchConsumerDetails) GetService() ManaV2B2BExtranetMatchConsumerDetailsService {
	if o == nil || IsNil(o.Service) {
		var ret ManaV2B2BExtranetMatchConsumerDetailsService
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2B2bExtranetMatchConsumerDetails) GetServiceOk() (*ManaV2B2BExtranetMatchConsumerDetailsService, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *ManaV2B2bExtranetMatchConsumerDetails) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given ManaV2B2BExtranetMatchConsumerDetailsService and assigns it to the Service field.
func (o *ManaV2B2bExtranetMatchConsumerDetails) SetService(v ManaV2B2BExtranetMatchConsumerDetailsService) {
	o.Service = &v
}

// GetServicePrefixes returns the ServicePrefixes field value if set, zero value otherwise.
func (o *ManaV2B2bExtranetMatchConsumerDetails) GetServicePrefixes() []ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix {
	if o == nil || IsNil(o.ServicePrefixes) {
		var ret []ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix
		return ret
	}
	return o.ServicePrefixes
}

// GetServicePrefixesOk returns a tuple with the ServicePrefixes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2B2bExtranetMatchConsumerDetails) GetServicePrefixesOk() ([]ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix, bool) {
	if o == nil || IsNil(o.ServicePrefixes) {
		return nil, false
	}
	return o.ServicePrefixes, true
}

// HasServicePrefixes returns a boolean if a field has been set.
func (o *ManaV2B2bExtranetMatchConsumerDetails) HasServicePrefixes() bool {
	if o != nil && !IsNil(o.ServicePrefixes) {
		return true
	}

	return false
}

// SetServicePrefixes gets a reference to the given []ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix and assigns it to the ServicePrefixes field.
func (o *ManaV2B2bExtranetMatchConsumerDetails) SetServicePrefixes(v []ManaV2B2BExtranetMatchConsumerDetailsProducerPrefix) {
	o.ServicePrefixes = v
}

func (o ManaV2B2bExtranetMatchConsumerDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2B2bExtranetMatchConsumerDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConsumerId) {
		toSerialize["consumerId"] = o.ConsumerId
	}
	if !IsNil(o.ConsumerPrefixes) {
		toSerialize["consumerPrefixes"] = o.ConsumerPrefixes
	}
	if !IsNil(o.Customer) {
		toSerialize["customer"] = o.Customer
	}
	if !IsNil(o.OldConsumerPrefixes) {
		toSerialize["oldConsumerPrefixes"] = o.OldConsumerPrefixes
	}
	if !IsNil(o.OldServicePrefixes) {
		toSerialize["oldServicePrefixes"] = o.OldServicePrefixes
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.ServicePrefixes) {
		toSerialize["servicePrefixes"] = o.ServicePrefixes
	}
	return toSerialize, nil
}

type NullableManaV2B2bExtranetMatchConsumerDetails struct {
	value *ManaV2B2bExtranetMatchConsumerDetails
	isSet bool
}

func (v NullableManaV2B2bExtranetMatchConsumerDetails) Get() *ManaV2B2bExtranetMatchConsumerDetails {
	return v.value
}

func (v *NullableManaV2B2bExtranetMatchConsumerDetails) Set(val *ManaV2B2bExtranetMatchConsumerDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2B2bExtranetMatchConsumerDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2B2bExtranetMatchConsumerDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2B2bExtranetMatchConsumerDetails(val *ManaV2B2bExtranetMatchConsumerDetails) *NullableManaV2B2bExtranetMatchConsumerDetails {
	return &NullableManaV2B2bExtranetMatchConsumerDetails{value: val, isSet: true}
}

func (v NullableManaV2B2bExtranetMatchConsumerDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2B2bExtranetMatchConsumerDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


