/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1GlobalContentFiltersGetResponseRowLanEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1GlobalContentFiltersGetResponseRowLanEntry{}

// V1GlobalContentFiltersGetResponseRowLanEntry struct for V1GlobalContentFiltersGetResponseRowLanEntry
type V1GlobalContentFiltersGetResponseRowLanEntry struct {
	// Name of a LAN segment that the filter is applied on.
	LanName *string `json:"lanName,omitempty"`
}

// NewV1GlobalContentFiltersGetResponseRowLanEntry instantiates a new V1GlobalContentFiltersGetResponseRowLanEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1GlobalContentFiltersGetResponseRowLanEntry() *V1GlobalContentFiltersGetResponseRowLanEntry {
	this := V1GlobalContentFiltersGetResponseRowLanEntry{}
	return &this
}

// NewV1GlobalContentFiltersGetResponseRowLanEntryWithDefaults instantiates a new V1GlobalContentFiltersGetResponseRowLanEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1GlobalContentFiltersGetResponseRowLanEntryWithDefaults() *V1GlobalContentFiltersGetResponseRowLanEntry {
	this := V1GlobalContentFiltersGetResponseRowLanEntry{}
	return &this
}

// GetLanName returns the LanName field value if set, zero value otherwise.
func (o *V1GlobalContentFiltersGetResponseRowLanEntry) GetLanName() string {
	if o == nil || IsNil(o.LanName) {
		var ret string
		return ret
	}
	return *o.LanName
}

// GetLanNameOk returns a tuple with the LanName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1GlobalContentFiltersGetResponseRowLanEntry) GetLanNameOk() (*string, bool) {
	if o == nil || IsNil(o.LanName) {
		return nil, false
	}
	return o.LanName, true
}

// HasLanName returns a boolean if a field has been set.
func (o *V1GlobalContentFiltersGetResponseRowLanEntry) HasLanName() bool {
	if o != nil && !IsNil(o.LanName) {
		return true
	}

	return false
}

// SetLanName gets a reference to the given string and assigns it to the LanName field.
func (o *V1GlobalContentFiltersGetResponseRowLanEntry) SetLanName(v string) {
	o.LanName = &v
}

func (o V1GlobalContentFiltersGetResponseRowLanEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1GlobalContentFiltersGetResponseRowLanEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LanName) {
		toSerialize["lanName"] = o.LanName
	}
	return toSerialize, nil
}

type NullableV1GlobalContentFiltersGetResponseRowLanEntry struct {
	value *V1GlobalContentFiltersGetResponseRowLanEntry
	isSet bool
}

func (v NullableV1GlobalContentFiltersGetResponseRowLanEntry) Get() *V1GlobalContentFiltersGetResponseRowLanEntry {
	return v.value
}

func (v *NullableV1GlobalContentFiltersGetResponseRowLanEntry) Set(val *V1GlobalContentFiltersGetResponseRowLanEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableV1GlobalContentFiltersGetResponseRowLanEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableV1GlobalContentFiltersGetResponseRowLanEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1GlobalContentFiltersGetResponseRowLanEntry(val *V1GlobalContentFiltersGetResponseRowLanEntry) *NullableV1GlobalContentFiltersGetResponseRowLanEntry {
	return &NullableV1GlobalContentFiltersGetResponseRowLanEntry{value: val, isSet: true}
}

func (v NullableV1GlobalContentFiltersGetResponseRowLanEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1GlobalContentFiltersGetResponseRowLanEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


