/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2OspfAuthentication type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2OspfAuthentication{}

// ManaV2OspfAuthentication struct for ManaV2OspfAuthentication
type ManaV2OspfAuthentication struct {
	// Shared secret for OSPFv2 MD5 authentication on this interface
	Key *string `json:"key,omitempty"`
	// Identifier of the OSPFv2 MD5 authentication key configured on this interface
	KeyId *int32 `json:"keyId,omitempty"`
}

// NewManaV2OspfAuthentication instantiates a new ManaV2OspfAuthentication object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2OspfAuthentication() *ManaV2OspfAuthentication {
	this := ManaV2OspfAuthentication{}
	return &this
}

// NewManaV2OspfAuthenticationWithDefaults instantiates a new ManaV2OspfAuthentication object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2OspfAuthenticationWithDefaults() *ManaV2OspfAuthentication {
	this := ManaV2OspfAuthentication{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ManaV2OspfAuthentication) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2OspfAuthentication) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ManaV2OspfAuthentication) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ManaV2OspfAuthentication) SetKey(v string) {
	o.Key = &v
}

// GetKeyId returns the KeyId field value if set, zero value otherwise.
func (o *ManaV2OspfAuthentication) GetKeyId() int32 {
	if o == nil || IsNil(o.KeyId) {
		var ret int32
		return ret
	}
	return *o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2OspfAuthentication) GetKeyIdOk() (*int32, bool) {
	if o == nil || IsNil(o.KeyId) {
		return nil, false
	}
	return o.KeyId, true
}

// HasKeyId returns a boolean if a field has been set.
func (o *ManaV2OspfAuthentication) HasKeyId() bool {
	if o != nil && !IsNil(o.KeyId) {
		return true
	}

	return false
}

// SetKeyId gets a reference to the given int32 and assigns it to the KeyId field.
func (o *ManaV2OspfAuthentication) SetKeyId(v int32) {
	o.KeyId = &v
}

func (o ManaV2OspfAuthentication) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2OspfAuthentication) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.KeyId) {
		toSerialize["keyId"] = o.KeyId
	}
	return toSerialize, nil
}

type NullableManaV2OspfAuthentication struct {
	value *ManaV2OspfAuthentication
	isSet bool
}

func (v NullableManaV2OspfAuthentication) Get() *ManaV2OspfAuthentication {
	return v.value
}

func (v *NullableManaV2OspfAuthentication) Set(val *ManaV2OspfAuthentication) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2OspfAuthentication) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2OspfAuthentication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2OspfAuthentication(val *ManaV2OspfAuthentication) *NullableManaV2OspfAuthentication {
	return &NullableManaV2OspfAuthentication{value: val, isSet: true}
}

func (v NullableManaV2OspfAuthentication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2OspfAuthentication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


