/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2ExtranetNatTranslationMode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2ExtranetNatTranslationMode{}

// ManaV2ExtranetNatTranslationMode struct for ManaV2ExtranetNatTranslationMode
type ManaV2ExtranetNatTranslationMode struct {
	Centralized *ManaV2ExtranetNatTranslationCentralized `json:"centralized,omitempty"`
	Decentralized *ManaV2ExtranetNatTranslationDecentralized `json:"decentralized,omitempty"`
	PeerToPeer *ManaV2ExtranetNatTranslationPeerToPeer `json:"peerToPeer,omitempty"`
}

// NewManaV2ExtranetNatTranslationMode instantiates a new ManaV2ExtranetNatTranslationMode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2ExtranetNatTranslationMode() *ManaV2ExtranetNatTranslationMode {
	this := ManaV2ExtranetNatTranslationMode{}
	return &this
}

// NewManaV2ExtranetNatTranslationModeWithDefaults instantiates a new ManaV2ExtranetNatTranslationMode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2ExtranetNatTranslationModeWithDefaults() *ManaV2ExtranetNatTranslationMode {
	this := ManaV2ExtranetNatTranslationMode{}
	return &this
}

// GetCentralized returns the Centralized field value if set, zero value otherwise.
func (o *ManaV2ExtranetNatTranslationMode) GetCentralized() ManaV2ExtranetNatTranslationCentralized {
	if o == nil || IsNil(o.Centralized) {
		var ret ManaV2ExtranetNatTranslationCentralized
		return ret
	}
	return *o.Centralized
}

// GetCentralizedOk returns a tuple with the Centralized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetNatTranslationMode) GetCentralizedOk() (*ManaV2ExtranetNatTranslationCentralized, bool) {
	if o == nil || IsNil(o.Centralized) {
		return nil, false
	}
	return o.Centralized, true
}

// HasCentralized returns a boolean if a field has been set.
func (o *ManaV2ExtranetNatTranslationMode) HasCentralized() bool {
	if o != nil && !IsNil(o.Centralized) {
		return true
	}

	return false
}

// SetCentralized gets a reference to the given ManaV2ExtranetNatTranslationCentralized and assigns it to the Centralized field.
func (o *ManaV2ExtranetNatTranslationMode) SetCentralized(v ManaV2ExtranetNatTranslationCentralized) {
	o.Centralized = &v
}

// GetDecentralized returns the Decentralized field value if set, zero value otherwise.
func (o *ManaV2ExtranetNatTranslationMode) GetDecentralized() ManaV2ExtranetNatTranslationDecentralized {
	if o == nil || IsNil(o.Decentralized) {
		var ret ManaV2ExtranetNatTranslationDecentralized
		return ret
	}
	return *o.Decentralized
}

// GetDecentralizedOk returns a tuple with the Decentralized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetNatTranslationMode) GetDecentralizedOk() (*ManaV2ExtranetNatTranslationDecentralized, bool) {
	if o == nil || IsNil(o.Decentralized) {
		return nil, false
	}
	return o.Decentralized, true
}

// HasDecentralized returns a boolean if a field has been set.
func (o *ManaV2ExtranetNatTranslationMode) HasDecentralized() bool {
	if o != nil && !IsNil(o.Decentralized) {
		return true
	}

	return false
}

// SetDecentralized gets a reference to the given ManaV2ExtranetNatTranslationDecentralized and assigns it to the Decentralized field.
func (o *ManaV2ExtranetNatTranslationMode) SetDecentralized(v ManaV2ExtranetNatTranslationDecentralized) {
	o.Decentralized = &v
}

// GetPeerToPeer returns the PeerToPeer field value if set, zero value otherwise.
func (o *ManaV2ExtranetNatTranslationMode) GetPeerToPeer() ManaV2ExtranetNatTranslationPeerToPeer {
	if o == nil || IsNil(o.PeerToPeer) {
		var ret ManaV2ExtranetNatTranslationPeerToPeer
		return ret
	}
	return *o.PeerToPeer
}

// GetPeerToPeerOk returns a tuple with the PeerToPeer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetNatTranslationMode) GetPeerToPeerOk() (*ManaV2ExtranetNatTranslationPeerToPeer, bool) {
	if o == nil || IsNil(o.PeerToPeer) {
		return nil, false
	}
	return o.PeerToPeer, true
}

// HasPeerToPeer returns a boolean if a field has been set.
func (o *ManaV2ExtranetNatTranslationMode) HasPeerToPeer() bool {
	if o != nil && !IsNil(o.PeerToPeer) {
		return true
	}

	return false
}

// SetPeerToPeer gets a reference to the given ManaV2ExtranetNatTranslationPeerToPeer and assigns it to the PeerToPeer field.
func (o *ManaV2ExtranetNatTranslationMode) SetPeerToPeer(v ManaV2ExtranetNatTranslationPeerToPeer) {
	o.PeerToPeer = &v
}

func (o ManaV2ExtranetNatTranslationMode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2ExtranetNatTranslationMode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Centralized) {
		toSerialize["centralized"] = o.Centralized
	}
	if !IsNil(o.Decentralized) {
		toSerialize["decentralized"] = o.Decentralized
	}
	if !IsNil(o.PeerToPeer) {
		toSerialize["peerToPeer"] = o.PeerToPeer
	}
	return toSerialize, nil
}

type NullableManaV2ExtranetNatTranslationMode struct {
	value *ManaV2ExtranetNatTranslationMode
	isSet bool
}

func (v NullableManaV2ExtranetNatTranslationMode) Get() *ManaV2ExtranetNatTranslationMode {
	return v.value
}

func (v *NullableManaV2ExtranetNatTranslationMode) Set(val *ManaV2ExtranetNatTranslationMode) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2ExtranetNatTranslationMode) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2ExtranetNatTranslationMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2ExtranetNatTranslationMode(val *ManaV2ExtranetNatTranslationMode) *NullableManaV2ExtranetNatTranslationMode {
	return &NullableManaV2ExtranetNatTranslationMode{value: val, isSet: true}
}

func (v NullableManaV2ExtranetNatTranslationMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2ExtranetNatTranslationMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


