/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetB2bProducerIdDeviceStatusGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bProducerIdDeviceStatusGetResponse{}

// V1ExtranetB2bProducerIdDeviceStatusGetResponse struct for V1ExtranetB2bProducerIdDeviceStatusGetResponse
type V1ExtranetB2bProducerIdDeviceStatusGetResponse struct {
	Summary []ManaV2B2bExtranetStatusSummary `json:"summary,omitempty"`
}

// NewV1ExtranetB2bProducerIdDeviceStatusGetResponse instantiates a new V1ExtranetB2bProducerIdDeviceStatusGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bProducerIdDeviceStatusGetResponse() *V1ExtranetB2bProducerIdDeviceStatusGetResponse {
	this := V1ExtranetB2bProducerIdDeviceStatusGetResponse{}
	return &this
}

// NewV1ExtranetB2bProducerIdDeviceStatusGetResponseWithDefaults instantiates a new V1ExtranetB2bProducerIdDeviceStatusGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bProducerIdDeviceStatusGetResponseWithDefaults() *V1ExtranetB2bProducerIdDeviceStatusGetResponse {
	this := V1ExtranetB2bProducerIdDeviceStatusGetResponse{}
	return &this
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *V1ExtranetB2bProducerIdDeviceStatusGetResponse) GetSummary() []ManaV2B2bExtranetStatusSummary {
	if o == nil || IsNil(o.Summary) {
		var ret []ManaV2B2bExtranetStatusSummary
		return ret
	}
	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bProducerIdDeviceStatusGetResponse) GetSummaryOk() ([]ManaV2B2bExtranetStatusSummary, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *V1ExtranetB2bProducerIdDeviceStatusGetResponse) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given []ManaV2B2bExtranetStatusSummary and assigns it to the Summary field.
func (o *V1ExtranetB2bProducerIdDeviceStatusGetResponse) SetSummary(v []ManaV2B2bExtranetStatusSummary) {
	o.Summary = v
}

func (o V1ExtranetB2bProducerIdDeviceStatusGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bProducerIdDeviceStatusGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	return toSerialize, nil
}

type NullableV1ExtranetB2bProducerIdDeviceStatusGetResponse struct {
	value *V1ExtranetB2bProducerIdDeviceStatusGetResponse
	isSet bool
}

func (v NullableV1ExtranetB2bProducerIdDeviceStatusGetResponse) Get() *V1ExtranetB2bProducerIdDeviceStatusGetResponse {
	return v.value
}

func (v *NullableV1ExtranetB2bProducerIdDeviceStatusGetResponse) Set(val *V1ExtranetB2bProducerIdDeviceStatusGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bProducerIdDeviceStatusGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bProducerIdDeviceStatusGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bProducerIdDeviceStatusGetResponse(val *V1ExtranetB2bProducerIdDeviceStatusGetResponse) *NullableV1ExtranetB2bProducerIdDeviceStatusGetResponse {
	return &NullableV1ExtranetB2bProducerIdDeviceStatusGetResponse{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bProducerIdDeviceStatusGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bProducerIdDeviceStatusGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


