/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpgradeRecurringSchedule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpgradeRecurringSchedule{}

// UpgradeRecurringSchedule struct for UpgradeRecurringSchedule
type UpgradeRecurringSchedule struct {
	Monthly *UpgradeMonthlyRecurrence `json:"monthly,omitempty"`
	StartsAtTs GoogleProtobufTimestamp `json:"startsAtTs"`
	Weekly *UpgradeWeeklyRecurrence `json:"weekly,omitempty"`
	Yearly *UpgradeYearlyRecurrence `json:"yearly,omitempty"`
}

type _UpgradeRecurringSchedule UpgradeRecurringSchedule

// NewUpgradeRecurringSchedule instantiates a new UpgradeRecurringSchedule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpgradeRecurringSchedule(startsAtTs GoogleProtobufTimestamp) *UpgradeRecurringSchedule {
	this := UpgradeRecurringSchedule{}
	this.StartsAtTs = startsAtTs
	return &this
}

// NewUpgradeRecurringScheduleWithDefaults instantiates a new UpgradeRecurringSchedule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpgradeRecurringScheduleWithDefaults() *UpgradeRecurringSchedule {
	this := UpgradeRecurringSchedule{}
	return &this
}

// GetMonthly returns the Monthly field value if set, zero value otherwise.
func (o *UpgradeRecurringSchedule) GetMonthly() UpgradeMonthlyRecurrence {
	if o == nil || IsNil(o.Monthly) {
		var ret UpgradeMonthlyRecurrence
		return ret
	}
	return *o.Monthly
}

// GetMonthlyOk returns a tuple with the Monthly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpgradeRecurringSchedule) GetMonthlyOk() (*UpgradeMonthlyRecurrence, bool) {
	if o == nil || IsNil(o.Monthly) {
		return nil, false
	}
	return o.Monthly, true
}

// HasMonthly returns a boolean if a field has been set.
func (o *UpgradeRecurringSchedule) HasMonthly() bool {
	if o != nil && !IsNil(o.Monthly) {
		return true
	}

	return false
}

// SetMonthly gets a reference to the given UpgradeMonthlyRecurrence and assigns it to the Monthly field.
func (o *UpgradeRecurringSchedule) SetMonthly(v UpgradeMonthlyRecurrence) {
	o.Monthly = &v
}

// GetStartsAtTs returns the StartsAtTs field value
func (o *UpgradeRecurringSchedule) GetStartsAtTs() GoogleProtobufTimestamp {
	if o == nil {
		var ret GoogleProtobufTimestamp
		return ret
	}

	return o.StartsAtTs
}

// GetStartsAtTsOk returns a tuple with the StartsAtTs field value
// and a boolean to check if the value has been set.
func (o *UpgradeRecurringSchedule) GetStartsAtTsOk() (*GoogleProtobufTimestamp, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartsAtTs, true
}

// SetStartsAtTs sets field value
func (o *UpgradeRecurringSchedule) SetStartsAtTs(v GoogleProtobufTimestamp) {
	o.StartsAtTs = v
}

// GetWeekly returns the Weekly field value if set, zero value otherwise.
func (o *UpgradeRecurringSchedule) GetWeekly() UpgradeWeeklyRecurrence {
	if o == nil || IsNil(o.Weekly) {
		var ret UpgradeWeeklyRecurrence
		return ret
	}
	return *o.Weekly
}

// GetWeeklyOk returns a tuple with the Weekly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpgradeRecurringSchedule) GetWeeklyOk() (*UpgradeWeeklyRecurrence, bool) {
	if o == nil || IsNil(o.Weekly) {
		return nil, false
	}
	return o.Weekly, true
}

// HasWeekly returns a boolean if a field has been set.
func (o *UpgradeRecurringSchedule) HasWeekly() bool {
	if o != nil && !IsNil(o.Weekly) {
		return true
	}

	return false
}

// SetWeekly gets a reference to the given UpgradeWeeklyRecurrence and assigns it to the Weekly field.
func (o *UpgradeRecurringSchedule) SetWeekly(v UpgradeWeeklyRecurrence) {
	o.Weekly = &v
}

// GetYearly returns the Yearly field value if set, zero value otherwise.
func (o *UpgradeRecurringSchedule) GetYearly() UpgradeYearlyRecurrence {
	if o == nil || IsNil(o.Yearly) {
		var ret UpgradeYearlyRecurrence
		return ret
	}
	return *o.Yearly
}

// GetYearlyOk returns a tuple with the Yearly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpgradeRecurringSchedule) GetYearlyOk() (*UpgradeYearlyRecurrence, bool) {
	if o == nil || IsNil(o.Yearly) {
		return nil, false
	}
	return o.Yearly, true
}

// HasYearly returns a boolean if a field has been set.
func (o *UpgradeRecurringSchedule) HasYearly() bool {
	if o != nil && !IsNil(o.Yearly) {
		return true
	}

	return false
}

// SetYearly gets a reference to the given UpgradeYearlyRecurrence and assigns it to the Yearly field.
func (o *UpgradeRecurringSchedule) SetYearly(v UpgradeYearlyRecurrence) {
	o.Yearly = &v
}

func (o UpgradeRecurringSchedule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpgradeRecurringSchedule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Monthly) {
		toSerialize["monthly"] = o.Monthly
	}
	toSerialize["startsAtTs"] = o.StartsAtTs
	if !IsNil(o.Weekly) {
		toSerialize["weekly"] = o.Weekly
	}
	if !IsNil(o.Yearly) {
		toSerialize["yearly"] = o.Yearly
	}
	return toSerialize, nil
}

func (o *UpgradeRecurringSchedule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"startsAtTs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpgradeRecurringSchedule := _UpgradeRecurringSchedule{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpgradeRecurringSchedule)

	if err != nil {
		return err
	}

	*o = UpgradeRecurringSchedule(varUpgradeRecurringSchedule)

	return err
}

type NullableUpgradeRecurringSchedule struct {
	value *UpgradeRecurringSchedule
	isSet bool
}

func (v NullableUpgradeRecurringSchedule) Get() *UpgradeRecurringSchedule {
	return v.value
}

func (v *NullableUpgradeRecurringSchedule) Set(val *UpgradeRecurringSchedule) {
	v.value = val
	v.isSet = true
}

func (v NullableUpgradeRecurringSchedule) IsSet() bool {
	return v.isSet
}

func (v *NullableUpgradeRecurringSchedule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpgradeRecurringSchedule(val *UpgradeRecurringSchedule) *NullableUpgradeRecurringSchedule {
	return &NullableUpgradeRecurringSchedule{value: val, isSet: true}
}

func (v NullableUpgradeRecurringSchedule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpgradeRecurringSchedule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


