/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V2MonitoringMacsecDeviceIdStatusGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2MonitoringMacsecDeviceIdStatusGetResponse{}

// V2MonitoringMacsecDeviceIdStatusGetResponse struct for V2MonitoringMacsecDeviceIdStatusGetResponse
type V2MonitoringMacsecDeviceIdStatusGetResponse struct {
	MacsecStatuses []V2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus `json:"macsecStatuses,omitempty"`
}

// NewV2MonitoringMacsecDeviceIdStatusGetResponse instantiates a new V2MonitoringMacsecDeviceIdStatusGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2MonitoringMacsecDeviceIdStatusGetResponse() *V2MonitoringMacsecDeviceIdStatusGetResponse {
	this := V2MonitoringMacsecDeviceIdStatusGetResponse{}
	return &this
}

// NewV2MonitoringMacsecDeviceIdStatusGetResponseWithDefaults instantiates a new V2MonitoringMacsecDeviceIdStatusGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2MonitoringMacsecDeviceIdStatusGetResponseWithDefaults() *V2MonitoringMacsecDeviceIdStatusGetResponse {
	this := V2MonitoringMacsecDeviceIdStatusGetResponse{}
	return &this
}

// GetMacsecStatuses returns the MacsecStatuses field value if set, zero value otherwise.
func (o *V2MonitoringMacsecDeviceIdStatusGetResponse) GetMacsecStatuses() []V2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus {
	if o == nil || IsNil(o.MacsecStatuses) {
		var ret []V2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus
		return ret
	}
	return o.MacsecStatuses
}

// GetMacsecStatusesOk returns a tuple with the MacsecStatuses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2MonitoringMacsecDeviceIdStatusGetResponse) GetMacsecStatusesOk() ([]V2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus, bool) {
	if o == nil || IsNil(o.MacsecStatuses) {
		return nil, false
	}
	return o.MacsecStatuses, true
}

// HasMacsecStatuses returns a boolean if a field has been set.
func (o *V2MonitoringMacsecDeviceIdStatusGetResponse) HasMacsecStatuses() bool {
	if o != nil && !IsNil(o.MacsecStatuses) {
		return true
	}

	return false
}

// SetMacsecStatuses gets a reference to the given []V2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus and assigns it to the MacsecStatuses field.
func (o *V2MonitoringMacsecDeviceIdStatusGetResponse) SetMacsecStatuses(v []V2MonitoringMacsecDeviceIdStatusGetResponseMaCsecStatus) {
	o.MacsecStatuses = v
}

func (o V2MonitoringMacsecDeviceIdStatusGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2MonitoringMacsecDeviceIdStatusGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MacsecStatuses) {
		toSerialize["macsecStatuses"] = o.MacsecStatuses
	}
	return toSerialize, nil
}

type NullableV2MonitoringMacsecDeviceIdStatusGetResponse struct {
	value *V2MonitoringMacsecDeviceIdStatusGetResponse
	isSet bool
}

func (v NullableV2MonitoringMacsecDeviceIdStatusGetResponse) Get() *V2MonitoringMacsecDeviceIdStatusGetResponse {
	return v.value
}

func (v *NullableV2MonitoringMacsecDeviceIdStatusGetResponse) Set(val *V2MonitoringMacsecDeviceIdStatusGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV2MonitoringMacsecDeviceIdStatusGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV2MonitoringMacsecDeviceIdStatusGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2MonitoringMacsecDeviceIdStatusGetResponse(val *V2MonitoringMacsecDeviceIdStatusGetResponse) *NullableV2MonitoringMacsecDeviceIdStatusGetResponse {
	return &NullableV2MonitoringMacsecDeviceIdStatusGetResponse{value: val, isSet: true}
}

func (v NullableV2MonitoringMacsecDeviceIdStatusGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2MonitoringMacsecDeviceIdStatusGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


