/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2ExtranetServiceProducerPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2ExtranetServiceProducerPolicy{}

// ManaV2ExtranetServiceProducerPolicy struct for ManaV2ExtranetServiceProducerPolicy
type ManaV2ExtranetServiceProducerPolicy struct {
	Description *string `json:"description,omitempty"`
	GlobalObjectDeviceSummaries *map[string]ManaV2GlobalObjectServiceSummaries `json:"globalObjectDeviceSummaries,omitempty"`
	GlobalObjectOps *map[string]ManaV2GlobalObjectServiceOps `json:"globalObjectOps,omitempty"`
	NatTranslationMode *ManaV2ExtranetNatTranslationMode `json:"natTranslationMode,omitempty"`
	PrefixTags []ManaV2B2bExtranetPrefixTag `json:"prefixTags,omitempty"`
	// LAN segment ID for the service
	ServiceLanSegment *int64 `json:"serviceLanSegment,omitempty"`
	Sites []ManaV2B2bSiteInformation `json:"sites,omitempty"`
}

// NewManaV2ExtranetServiceProducerPolicy instantiates a new ManaV2ExtranetServiceProducerPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2ExtranetServiceProducerPolicy() *ManaV2ExtranetServiceProducerPolicy {
	this := ManaV2ExtranetServiceProducerPolicy{}
	return &this
}

// NewManaV2ExtranetServiceProducerPolicyWithDefaults instantiates a new ManaV2ExtranetServiceProducerPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2ExtranetServiceProducerPolicyWithDefaults() *ManaV2ExtranetServiceProducerPolicy {
	this := ManaV2ExtranetServiceProducerPolicy{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ManaV2ExtranetServiceProducerPolicy) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServiceProducerPolicy) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ManaV2ExtranetServiceProducerPolicy) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ManaV2ExtranetServiceProducerPolicy) SetDescription(v string) {
	o.Description = &v
}

// GetGlobalObjectDeviceSummaries returns the GlobalObjectDeviceSummaries field value if set, zero value otherwise.
func (o *ManaV2ExtranetServiceProducerPolicy) GetGlobalObjectDeviceSummaries() map[string]ManaV2GlobalObjectServiceSummaries {
	if o == nil || IsNil(o.GlobalObjectDeviceSummaries) {
		var ret map[string]ManaV2GlobalObjectServiceSummaries
		return ret
	}
	return *o.GlobalObjectDeviceSummaries
}

// GetGlobalObjectDeviceSummariesOk returns a tuple with the GlobalObjectDeviceSummaries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServiceProducerPolicy) GetGlobalObjectDeviceSummariesOk() (*map[string]ManaV2GlobalObjectServiceSummaries, bool) {
	if o == nil || IsNil(o.GlobalObjectDeviceSummaries) {
		return nil, false
	}
	return o.GlobalObjectDeviceSummaries, true
}

// HasGlobalObjectDeviceSummaries returns a boolean if a field has been set.
func (o *ManaV2ExtranetServiceProducerPolicy) HasGlobalObjectDeviceSummaries() bool {
	if o != nil && !IsNil(o.GlobalObjectDeviceSummaries) {
		return true
	}

	return false
}

// SetGlobalObjectDeviceSummaries gets a reference to the given map[string]ManaV2GlobalObjectServiceSummaries and assigns it to the GlobalObjectDeviceSummaries field.
func (o *ManaV2ExtranetServiceProducerPolicy) SetGlobalObjectDeviceSummaries(v map[string]ManaV2GlobalObjectServiceSummaries) {
	o.GlobalObjectDeviceSummaries = &v
}

// GetGlobalObjectOps returns the GlobalObjectOps field value if set, zero value otherwise.
func (o *ManaV2ExtranetServiceProducerPolicy) GetGlobalObjectOps() map[string]ManaV2GlobalObjectServiceOps {
	if o == nil || IsNil(o.GlobalObjectOps) {
		var ret map[string]ManaV2GlobalObjectServiceOps
		return ret
	}
	return *o.GlobalObjectOps
}

// GetGlobalObjectOpsOk returns a tuple with the GlobalObjectOps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServiceProducerPolicy) GetGlobalObjectOpsOk() (*map[string]ManaV2GlobalObjectServiceOps, bool) {
	if o == nil || IsNil(o.GlobalObjectOps) {
		return nil, false
	}
	return o.GlobalObjectOps, true
}

// HasGlobalObjectOps returns a boolean if a field has been set.
func (o *ManaV2ExtranetServiceProducerPolicy) HasGlobalObjectOps() bool {
	if o != nil && !IsNil(o.GlobalObjectOps) {
		return true
	}

	return false
}

// SetGlobalObjectOps gets a reference to the given map[string]ManaV2GlobalObjectServiceOps and assigns it to the GlobalObjectOps field.
func (o *ManaV2ExtranetServiceProducerPolicy) SetGlobalObjectOps(v map[string]ManaV2GlobalObjectServiceOps) {
	o.GlobalObjectOps = &v
}

// GetNatTranslationMode returns the NatTranslationMode field value if set, zero value otherwise.
func (o *ManaV2ExtranetServiceProducerPolicy) GetNatTranslationMode() ManaV2ExtranetNatTranslationMode {
	if o == nil || IsNil(o.NatTranslationMode) {
		var ret ManaV2ExtranetNatTranslationMode
		return ret
	}
	return *o.NatTranslationMode
}

// GetNatTranslationModeOk returns a tuple with the NatTranslationMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServiceProducerPolicy) GetNatTranslationModeOk() (*ManaV2ExtranetNatTranslationMode, bool) {
	if o == nil || IsNil(o.NatTranslationMode) {
		return nil, false
	}
	return o.NatTranslationMode, true
}

// HasNatTranslationMode returns a boolean if a field has been set.
func (o *ManaV2ExtranetServiceProducerPolicy) HasNatTranslationMode() bool {
	if o != nil && !IsNil(o.NatTranslationMode) {
		return true
	}

	return false
}

// SetNatTranslationMode gets a reference to the given ManaV2ExtranetNatTranslationMode and assigns it to the NatTranslationMode field.
func (o *ManaV2ExtranetServiceProducerPolicy) SetNatTranslationMode(v ManaV2ExtranetNatTranslationMode) {
	o.NatTranslationMode = &v
}

// GetPrefixTags returns the PrefixTags field value if set, zero value otherwise.
func (o *ManaV2ExtranetServiceProducerPolicy) GetPrefixTags() []ManaV2B2bExtranetPrefixTag {
	if o == nil || IsNil(o.PrefixTags) {
		var ret []ManaV2B2bExtranetPrefixTag
		return ret
	}
	return o.PrefixTags
}

// GetPrefixTagsOk returns a tuple with the PrefixTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServiceProducerPolicy) GetPrefixTagsOk() ([]ManaV2B2bExtranetPrefixTag, bool) {
	if o == nil || IsNil(o.PrefixTags) {
		return nil, false
	}
	return o.PrefixTags, true
}

// HasPrefixTags returns a boolean if a field has been set.
func (o *ManaV2ExtranetServiceProducerPolicy) HasPrefixTags() bool {
	if o != nil && !IsNil(o.PrefixTags) {
		return true
	}

	return false
}

// SetPrefixTags gets a reference to the given []ManaV2B2bExtranetPrefixTag and assigns it to the PrefixTags field.
func (o *ManaV2ExtranetServiceProducerPolicy) SetPrefixTags(v []ManaV2B2bExtranetPrefixTag) {
	o.PrefixTags = v
}

// GetServiceLanSegment returns the ServiceLanSegment field value if set, zero value otherwise.
func (o *ManaV2ExtranetServiceProducerPolicy) GetServiceLanSegment() int64 {
	if o == nil || IsNil(o.ServiceLanSegment) {
		var ret int64
		return ret
	}
	return *o.ServiceLanSegment
}

// GetServiceLanSegmentOk returns a tuple with the ServiceLanSegment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServiceProducerPolicy) GetServiceLanSegmentOk() (*int64, bool) {
	if o == nil || IsNil(o.ServiceLanSegment) {
		return nil, false
	}
	return o.ServiceLanSegment, true
}

// HasServiceLanSegment returns a boolean if a field has been set.
func (o *ManaV2ExtranetServiceProducerPolicy) HasServiceLanSegment() bool {
	if o != nil && !IsNil(o.ServiceLanSegment) {
		return true
	}

	return false
}

// SetServiceLanSegment gets a reference to the given int64 and assigns it to the ServiceLanSegment field.
func (o *ManaV2ExtranetServiceProducerPolicy) SetServiceLanSegment(v int64) {
	o.ServiceLanSegment = &v
}

// GetSites returns the Sites field value if set, zero value otherwise.
func (o *ManaV2ExtranetServiceProducerPolicy) GetSites() []ManaV2B2bSiteInformation {
	if o == nil || IsNil(o.Sites) {
		var ret []ManaV2B2bSiteInformation
		return ret
	}
	return o.Sites
}

// GetSitesOk returns a tuple with the Sites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetServiceProducerPolicy) GetSitesOk() ([]ManaV2B2bSiteInformation, bool) {
	if o == nil || IsNil(o.Sites) {
		return nil, false
	}
	return o.Sites, true
}

// HasSites returns a boolean if a field has been set.
func (o *ManaV2ExtranetServiceProducerPolicy) HasSites() bool {
	if o != nil && !IsNil(o.Sites) {
		return true
	}

	return false
}

// SetSites gets a reference to the given []ManaV2B2bSiteInformation and assigns it to the Sites field.
func (o *ManaV2ExtranetServiceProducerPolicy) SetSites(v []ManaV2B2bSiteInformation) {
	o.Sites = v
}

func (o ManaV2ExtranetServiceProducerPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2ExtranetServiceProducerPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.GlobalObjectDeviceSummaries) {
		toSerialize["globalObjectDeviceSummaries"] = o.GlobalObjectDeviceSummaries
	}
	if !IsNil(o.GlobalObjectOps) {
		toSerialize["globalObjectOps"] = o.GlobalObjectOps
	}
	if !IsNil(o.NatTranslationMode) {
		toSerialize["natTranslationMode"] = o.NatTranslationMode
	}
	if !IsNil(o.PrefixTags) {
		toSerialize["prefixTags"] = o.PrefixTags
	}
	if !IsNil(o.ServiceLanSegment) {
		toSerialize["serviceLanSegment"] = o.ServiceLanSegment
	}
	if !IsNil(o.Sites) {
		toSerialize["sites"] = o.Sites
	}
	return toSerialize, nil
}

type NullableManaV2ExtranetServiceProducerPolicy struct {
	value *ManaV2ExtranetServiceProducerPolicy
	isSet bool
}

func (v NullableManaV2ExtranetServiceProducerPolicy) Get() *ManaV2ExtranetServiceProducerPolicy {
	return v.value
}

func (v *NullableManaV2ExtranetServiceProducerPolicy) Set(val *ManaV2ExtranetServiceProducerPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2ExtranetServiceProducerPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2ExtranetServiceProducerPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2ExtranetServiceProducerPolicy(val *ManaV2ExtranetServiceProducerPolicy) *NullableManaV2ExtranetServiceProducerPolicy {
	return &NullableManaV2ExtranetServiceProducerPolicy{value: val, isSet: true}
}

func (v NullableManaV2ExtranetServiceProducerPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2ExtranetServiceProducerPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


