/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the AssuranceTopLevelKpi type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssuranceTopLevelKpi{}

// AssuranceTopLevelKpi struct for AssuranceTopLevelKpi
type AssuranceTopLevelKpi struct {
	DataTransferredKbpsMetric *AssuranceKpiMetric `json:"dataTransferredKbpsMetric,omitempty"`
	ShadowAiToolsMetric *AssuranceKpiMetric `json:"shadowAiToolsMetric,omitempty"`
	ToolsMetric *AssuranceKpiMetric `json:"toolsMetric,omitempty"`
	UsersMetric *AssuranceKpiMetric `json:"usersMetric,omitempty"`
}

// NewAssuranceTopLevelKpi instantiates a new AssuranceTopLevelKpi object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssuranceTopLevelKpi() *AssuranceTopLevelKpi {
	this := AssuranceTopLevelKpi{}
	return &this
}

// NewAssuranceTopLevelKpiWithDefaults instantiates a new AssuranceTopLevelKpi object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssuranceTopLevelKpiWithDefaults() *AssuranceTopLevelKpi {
	this := AssuranceTopLevelKpi{}
	return &this
}

// GetDataTransferredKbpsMetric returns the DataTransferredKbpsMetric field value if set, zero value otherwise.
func (o *AssuranceTopLevelKpi) GetDataTransferredKbpsMetric() AssuranceKpiMetric {
	if o == nil || IsNil(o.DataTransferredKbpsMetric) {
		var ret AssuranceKpiMetric
		return ret
	}
	return *o.DataTransferredKbpsMetric
}

// GetDataTransferredKbpsMetricOk returns a tuple with the DataTransferredKbpsMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceTopLevelKpi) GetDataTransferredKbpsMetricOk() (*AssuranceKpiMetric, bool) {
	if o == nil || IsNil(o.DataTransferredKbpsMetric) {
		return nil, false
	}
	return o.DataTransferredKbpsMetric, true
}

// HasDataTransferredKbpsMetric returns a boolean if a field has been set.
func (o *AssuranceTopLevelKpi) HasDataTransferredKbpsMetric() bool {
	if o != nil && !IsNil(o.DataTransferredKbpsMetric) {
		return true
	}

	return false
}

// SetDataTransferredKbpsMetric gets a reference to the given AssuranceKpiMetric and assigns it to the DataTransferredKbpsMetric field.
func (o *AssuranceTopLevelKpi) SetDataTransferredKbpsMetric(v AssuranceKpiMetric) {
	o.DataTransferredKbpsMetric = &v
}

// GetShadowAiToolsMetric returns the ShadowAiToolsMetric field value if set, zero value otherwise.
func (o *AssuranceTopLevelKpi) GetShadowAiToolsMetric() AssuranceKpiMetric {
	if o == nil || IsNil(o.ShadowAiToolsMetric) {
		var ret AssuranceKpiMetric
		return ret
	}
	return *o.ShadowAiToolsMetric
}

// GetShadowAiToolsMetricOk returns a tuple with the ShadowAiToolsMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceTopLevelKpi) GetShadowAiToolsMetricOk() (*AssuranceKpiMetric, bool) {
	if o == nil || IsNil(o.ShadowAiToolsMetric) {
		return nil, false
	}
	return o.ShadowAiToolsMetric, true
}

// HasShadowAiToolsMetric returns a boolean if a field has been set.
func (o *AssuranceTopLevelKpi) HasShadowAiToolsMetric() bool {
	if o != nil && !IsNil(o.ShadowAiToolsMetric) {
		return true
	}

	return false
}

// SetShadowAiToolsMetric gets a reference to the given AssuranceKpiMetric and assigns it to the ShadowAiToolsMetric field.
func (o *AssuranceTopLevelKpi) SetShadowAiToolsMetric(v AssuranceKpiMetric) {
	o.ShadowAiToolsMetric = &v
}

// GetToolsMetric returns the ToolsMetric field value if set, zero value otherwise.
func (o *AssuranceTopLevelKpi) GetToolsMetric() AssuranceKpiMetric {
	if o == nil || IsNil(o.ToolsMetric) {
		var ret AssuranceKpiMetric
		return ret
	}
	return *o.ToolsMetric
}

// GetToolsMetricOk returns a tuple with the ToolsMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceTopLevelKpi) GetToolsMetricOk() (*AssuranceKpiMetric, bool) {
	if o == nil || IsNil(o.ToolsMetric) {
		return nil, false
	}
	return o.ToolsMetric, true
}

// HasToolsMetric returns a boolean if a field has been set.
func (o *AssuranceTopLevelKpi) HasToolsMetric() bool {
	if o != nil && !IsNil(o.ToolsMetric) {
		return true
	}

	return false
}

// SetToolsMetric gets a reference to the given AssuranceKpiMetric and assigns it to the ToolsMetric field.
func (o *AssuranceTopLevelKpi) SetToolsMetric(v AssuranceKpiMetric) {
	o.ToolsMetric = &v
}

// GetUsersMetric returns the UsersMetric field value if set, zero value otherwise.
func (o *AssuranceTopLevelKpi) GetUsersMetric() AssuranceKpiMetric {
	if o == nil || IsNil(o.UsersMetric) {
		var ret AssuranceKpiMetric
		return ret
	}
	return *o.UsersMetric
}

// GetUsersMetricOk returns a tuple with the UsersMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceTopLevelKpi) GetUsersMetricOk() (*AssuranceKpiMetric, bool) {
	if o == nil || IsNil(o.UsersMetric) {
		return nil, false
	}
	return o.UsersMetric, true
}

// HasUsersMetric returns a boolean if a field has been set.
func (o *AssuranceTopLevelKpi) HasUsersMetric() bool {
	if o != nil && !IsNil(o.UsersMetric) {
		return true
	}

	return false
}

// SetUsersMetric gets a reference to the given AssuranceKpiMetric and assigns it to the UsersMetric field.
func (o *AssuranceTopLevelKpi) SetUsersMetric(v AssuranceKpiMetric) {
	o.UsersMetric = &v
}

func (o AssuranceTopLevelKpi) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssuranceTopLevelKpi) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DataTransferredKbpsMetric) {
		toSerialize["dataTransferredKbpsMetric"] = o.DataTransferredKbpsMetric
	}
	if !IsNil(o.ShadowAiToolsMetric) {
		toSerialize["shadowAiToolsMetric"] = o.ShadowAiToolsMetric
	}
	if !IsNil(o.ToolsMetric) {
		toSerialize["toolsMetric"] = o.ToolsMetric
	}
	if !IsNil(o.UsersMetric) {
		toSerialize["usersMetric"] = o.UsersMetric
	}
	return toSerialize, nil
}

type NullableAssuranceTopLevelKpi struct {
	value *AssuranceTopLevelKpi
	isSet bool
}

func (v NullableAssuranceTopLevelKpi) Get() *AssuranceTopLevelKpi {
	return v.value
}

func (v *NullableAssuranceTopLevelKpi) Set(val *AssuranceTopLevelKpi) {
	v.value = val
	v.isSet = true
}

func (v NullableAssuranceTopLevelKpi) IsSet() bool {
	return v.isSet
}

func (v *NullableAssuranceTopLevelKpi) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssuranceTopLevelKpi(val *AssuranceTopLevelKpi) *NullableAssuranceTopLevelKpi {
	return &NullableAssuranceTopLevelKpi{value: val, isSet: true}
}

func (v NullableAssuranceTopLevelKpi) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssuranceTopLevelKpi) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


