/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1GlobalDomainCategoriesGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1GlobalDomainCategoriesGetResponse{}

// V1GlobalDomainCategoriesGetResponse struct for V1GlobalDomainCategoriesGetResponse
type V1GlobalDomainCategoriesGetResponse struct {
	DomainCategories []ManaV2DomainCategory `json:"domainCategories,omitempty"`
}

// NewV1GlobalDomainCategoriesGetResponse instantiates a new V1GlobalDomainCategoriesGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1GlobalDomainCategoriesGetResponse() *V1GlobalDomainCategoriesGetResponse {
	this := V1GlobalDomainCategoriesGetResponse{}
	return &this
}

// NewV1GlobalDomainCategoriesGetResponseWithDefaults instantiates a new V1GlobalDomainCategoriesGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1GlobalDomainCategoriesGetResponseWithDefaults() *V1GlobalDomainCategoriesGetResponse {
	this := V1GlobalDomainCategoriesGetResponse{}
	return &this
}

// GetDomainCategories returns the DomainCategories field value if set, zero value otherwise.
func (o *V1GlobalDomainCategoriesGetResponse) GetDomainCategories() []ManaV2DomainCategory {
	if o == nil || IsNil(o.DomainCategories) {
		var ret []ManaV2DomainCategory
		return ret
	}
	return o.DomainCategories
}

// GetDomainCategoriesOk returns a tuple with the DomainCategories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1GlobalDomainCategoriesGetResponse) GetDomainCategoriesOk() ([]ManaV2DomainCategory, bool) {
	if o == nil || IsNil(o.DomainCategories) {
		return nil, false
	}
	return o.DomainCategories, true
}

// HasDomainCategories returns a boolean if a field has been set.
func (o *V1GlobalDomainCategoriesGetResponse) HasDomainCategories() bool {
	if o != nil && !IsNil(o.DomainCategories) {
		return true
	}

	return false
}

// SetDomainCategories gets a reference to the given []ManaV2DomainCategory and assigns it to the DomainCategories field.
func (o *V1GlobalDomainCategoriesGetResponse) SetDomainCategories(v []ManaV2DomainCategory) {
	o.DomainCategories = v
}

func (o V1GlobalDomainCategoriesGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1GlobalDomainCategoriesGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DomainCategories) {
		toSerialize["domainCategories"] = o.DomainCategories
	}
	return toSerialize, nil
}

type NullableV1GlobalDomainCategoriesGetResponse struct {
	value *V1GlobalDomainCategoriesGetResponse
	isSet bool
}

func (v NullableV1GlobalDomainCategoriesGetResponse) Get() *V1GlobalDomainCategoriesGetResponse {
	return v.value
}

func (v *NullableV1GlobalDomainCategoriesGetResponse) Set(val *V1GlobalDomainCategoriesGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1GlobalDomainCategoriesGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1GlobalDomainCategoriesGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1GlobalDomainCategoriesGetResponse(val *V1GlobalDomainCategoriesGetResponse) *NullableV1GlobalDomainCategoriesGetResponse {
	return &NullableV1GlobalDomainCategoriesGetResponse{value: val, isSet: true}
}

func (v NullableV1GlobalDomainCategoriesGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1GlobalDomainCategoriesGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


