/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetB2bMatchesMatchIdStatusPutResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bMatchesMatchIdStatusPutResponse{}

// V1ExtranetB2bMatchesMatchIdStatusPutResponse struct for V1ExtranetB2bMatchesMatchIdStatusPutResponse
type V1ExtranetB2bMatchesMatchIdStatusPutResponse struct {
	Status *string `json:"status,omitempty"`
}

// NewV1ExtranetB2bMatchesMatchIdStatusPutResponse instantiates a new V1ExtranetB2bMatchesMatchIdStatusPutResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bMatchesMatchIdStatusPutResponse() *V1ExtranetB2bMatchesMatchIdStatusPutResponse {
	this := V1ExtranetB2bMatchesMatchIdStatusPutResponse{}
	return &this
}

// NewV1ExtranetB2bMatchesMatchIdStatusPutResponseWithDefaults instantiates a new V1ExtranetB2bMatchesMatchIdStatusPutResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bMatchesMatchIdStatusPutResponseWithDefaults() *V1ExtranetB2bMatchesMatchIdStatusPutResponse {
	this := V1ExtranetB2bMatchesMatchIdStatusPutResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1ExtranetB2bMatchesMatchIdStatusPutResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMatchesMatchIdStatusPutResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1ExtranetB2bMatchesMatchIdStatusPutResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1ExtranetB2bMatchesMatchIdStatusPutResponse) SetStatus(v string) {
	o.Status = &v
}

func (o V1ExtranetB2bMatchesMatchIdStatusPutResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bMatchesMatchIdStatusPutResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1ExtranetB2bMatchesMatchIdStatusPutResponse struct {
	value *V1ExtranetB2bMatchesMatchIdStatusPutResponse
	isSet bool
}

func (v NullableV1ExtranetB2bMatchesMatchIdStatusPutResponse) Get() *V1ExtranetB2bMatchesMatchIdStatusPutResponse {
	return v.value
}

func (v *NullableV1ExtranetB2bMatchesMatchIdStatusPutResponse) Set(val *V1ExtranetB2bMatchesMatchIdStatusPutResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bMatchesMatchIdStatusPutResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bMatchesMatchIdStatusPutResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bMatchesMatchIdStatusPutResponse(val *V1ExtranetB2bMatchesMatchIdStatusPutResponse) *NullableV1ExtranetB2bMatchesMatchIdStatusPutResponse {
	return &NullableV1ExtranetB2bMatchesMatchIdStatusPutResponse{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bMatchesMatchIdStatusPutResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bMatchesMatchIdStatusPutResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


