/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetB2bProducerIdStatusPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bProducerIdStatusPutRequest{}

// V1ExtranetB2bProducerIdStatusPutRequest struct for V1ExtranetB2bProducerIdStatusPutRequest
type V1ExtranetB2bProducerIdStatusPutRequest struct {
	Status *string `json:"status,omitempty"`
}

// NewV1ExtranetB2bProducerIdStatusPutRequest instantiates a new V1ExtranetB2bProducerIdStatusPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bProducerIdStatusPutRequest() *V1ExtranetB2bProducerIdStatusPutRequest {
	this := V1ExtranetB2bProducerIdStatusPutRequest{}
	return &this
}

// NewV1ExtranetB2bProducerIdStatusPutRequestWithDefaults instantiates a new V1ExtranetB2bProducerIdStatusPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bProducerIdStatusPutRequestWithDefaults() *V1ExtranetB2bProducerIdStatusPutRequest {
	this := V1ExtranetB2bProducerIdStatusPutRequest{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1ExtranetB2bProducerIdStatusPutRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bProducerIdStatusPutRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1ExtranetB2bProducerIdStatusPutRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1ExtranetB2bProducerIdStatusPutRequest) SetStatus(v string) {
	o.Status = &v
}

func (o V1ExtranetB2bProducerIdStatusPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bProducerIdStatusPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1ExtranetB2bProducerIdStatusPutRequest struct {
	value *V1ExtranetB2bProducerIdStatusPutRequest
	isSet bool
}

func (v NullableV1ExtranetB2bProducerIdStatusPutRequest) Get() *V1ExtranetB2bProducerIdStatusPutRequest {
	return v.value
}

func (v *NullableV1ExtranetB2bProducerIdStatusPutRequest) Set(val *V1ExtranetB2bProducerIdStatusPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bProducerIdStatusPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bProducerIdStatusPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bProducerIdStatusPutRequest(val *V1ExtranetB2bProducerIdStatusPutRequest) *NullableV1ExtranetB2bProducerIdStatusPutRequest {
	return &NullableV1ExtranetB2bProducerIdStatusPutRequest{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bProducerIdStatusPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bProducerIdStatusPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


