/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetPublicVifGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetPublicVifGetResponse{}

// V1ExtranetPublicVifGetResponse struct for V1ExtranetPublicVifGetResponse
type V1ExtranetPublicVifGetResponse struct {
	Summary []ManaV2PublicVifSummary `json:"summary,omitempty"`
}

// NewV1ExtranetPublicVifGetResponse instantiates a new V1ExtranetPublicVifGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetPublicVifGetResponse() *V1ExtranetPublicVifGetResponse {
	this := V1ExtranetPublicVifGetResponse{}
	return &this
}

// NewV1ExtranetPublicVifGetResponseWithDefaults instantiates a new V1ExtranetPublicVifGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetPublicVifGetResponseWithDefaults() *V1ExtranetPublicVifGetResponse {
	this := V1ExtranetPublicVifGetResponse{}
	return &this
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *V1ExtranetPublicVifGetResponse) GetSummary() []ManaV2PublicVifSummary {
	if o == nil || IsNil(o.Summary) {
		var ret []ManaV2PublicVifSummary
		return ret
	}
	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetPublicVifGetResponse) GetSummaryOk() ([]ManaV2PublicVifSummary, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *V1ExtranetPublicVifGetResponse) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given []ManaV2PublicVifSummary and assigns it to the Summary field.
func (o *V1ExtranetPublicVifGetResponse) SetSummary(v []ManaV2PublicVifSummary) {
	o.Summary = v
}

func (o V1ExtranetPublicVifGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetPublicVifGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	return toSerialize, nil
}

type NullableV1ExtranetPublicVifGetResponse struct {
	value *V1ExtranetPublicVifGetResponse
	isSet bool
}

func (v NullableV1ExtranetPublicVifGetResponse) Get() *V1ExtranetPublicVifGetResponse {
	return v.value
}

func (v *NullableV1ExtranetPublicVifGetResponse) Set(val *V1ExtranetPublicVifGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetPublicVifGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetPublicVifGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetPublicVifGetResponse(val *V1ExtranetPublicVifGetResponse) *NullableV1ExtranetPublicVifGetResponse {
	return &NullableV1ExtranetPublicVifGetResponse{value: val, isSet: true}
}

func (v NullableV1ExtranetPublicVifGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetPublicVifGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


