/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetPublicVifCheckPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetPublicVifCheckPostResponse{}

// V1ExtranetPublicVifCheckPostResponse struct for V1ExtranetPublicVifCheckPostResponse
type V1ExtranetPublicVifCheckPostResponse struct {
	ConsumerPolicy *ManaV2PublicVifConsumerPolicyResponse `json:"consumerPolicy,omitempty"`
	Id *int64 `json:"id,omitempty"`
	ProducerPolicy *ManaV2PublicVifProducerPolicyResponse `json:"producerPolicy,omitempty"`
	ServiceName *string `json:"serviceName,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewV1ExtranetPublicVifCheckPostResponse instantiates a new V1ExtranetPublicVifCheckPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetPublicVifCheckPostResponse() *V1ExtranetPublicVifCheckPostResponse {
	this := V1ExtranetPublicVifCheckPostResponse{}
	return &this
}

// NewV1ExtranetPublicVifCheckPostResponseWithDefaults instantiates a new V1ExtranetPublicVifCheckPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetPublicVifCheckPostResponseWithDefaults() *V1ExtranetPublicVifCheckPostResponse {
	this := V1ExtranetPublicVifCheckPostResponse{}
	return &this
}

// GetConsumerPolicy returns the ConsumerPolicy field value if set, zero value otherwise.
func (o *V1ExtranetPublicVifCheckPostResponse) GetConsumerPolicy() ManaV2PublicVifConsumerPolicyResponse {
	if o == nil || IsNil(o.ConsumerPolicy) {
		var ret ManaV2PublicVifConsumerPolicyResponse
		return ret
	}
	return *o.ConsumerPolicy
}

// GetConsumerPolicyOk returns a tuple with the ConsumerPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetPublicVifCheckPostResponse) GetConsumerPolicyOk() (*ManaV2PublicVifConsumerPolicyResponse, bool) {
	if o == nil || IsNil(o.ConsumerPolicy) {
		return nil, false
	}
	return o.ConsumerPolicy, true
}

// HasConsumerPolicy returns a boolean if a field has been set.
func (o *V1ExtranetPublicVifCheckPostResponse) HasConsumerPolicy() bool {
	if o != nil && !IsNil(o.ConsumerPolicy) {
		return true
	}

	return false
}

// SetConsumerPolicy gets a reference to the given ManaV2PublicVifConsumerPolicyResponse and assigns it to the ConsumerPolicy field.
func (o *V1ExtranetPublicVifCheckPostResponse) SetConsumerPolicy(v ManaV2PublicVifConsumerPolicyResponse) {
	o.ConsumerPolicy = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V1ExtranetPublicVifCheckPostResponse) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetPublicVifCheckPostResponse) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V1ExtranetPublicVifCheckPostResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *V1ExtranetPublicVifCheckPostResponse) SetId(v int64) {
	o.Id = &v
}

// GetProducerPolicy returns the ProducerPolicy field value if set, zero value otherwise.
func (o *V1ExtranetPublicVifCheckPostResponse) GetProducerPolicy() ManaV2PublicVifProducerPolicyResponse {
	if o == nil || IsNil(o.ProducerPolicy) {
		var ret ManaV2PublicVifProducerPolicyResponse
		return ret
	}
	return *o.ProducerPolicy
}

// GetProducerPolicyOk returns a tuple with the ProducerPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetPublicVifCheckPostResponse) GetProducerPolicyOk() (*ManaV2PublicVifProducerPolicyResponse, bool) {
	if o == nil || IsNil(o.ProducerPolicy) {
		return nil, false
	}
	return o.ProducerPolicy, true
}

// HasProducerPolicy returns a boolean if a field has been set.
func (o *V1ExtranetPublicVifCheckPostResponse) HasProducerPolicy() bool {
	if o != nil && !IsNil(o.ProducerPolicy) {
		return true
	}

	return false
}

// SetProducerPolicy gets a reference to the given ManaV2PublicVifProducerPolicyResponse and assigns it to the ProducerPolicy field.
func (o *V1ExtranetPublicVifCheckPostResponse) SetProducerPolicy(v ManaV2PublicVifProducerPolicyResponse) {
	o.ProducerPolicy = &v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise.
func (o *V1ExtranetPublicVifCheckPostResponse) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName) {
		var ret string
		return ret
	}
	return *o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetPublicVifCheckPostResponse) GetServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceName) {
		return nil, false
	}
	return o.ServiceName, true
}

// HasServiceName returns a boolean if a field has been set.
func (o *V1ExtranetPublicVifCheckPostResponse) HasServiceName() bool {
	if o != nil && !IsNil(o.ServiceName) {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given string and assigns it to the ServiceName field.
func (o *V1ExtranetPublicVifCheckPostResponse) SetServiceName(v string) {
	o.ServiceName = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *V1ExtranetPublicVifCheckPostResponse) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetPublicVifCheckPostResponse) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *V1ExtranetPublicVifCheckPostResponse) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *V1ExtranetPublicVifCheckPostResponse) SetType(v string) {
	o.Type = &v
}

func (o V1ExtranetPublicVifCheckPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetPublicVifCheckPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConsumerPolicy) {
		toSerialize["consumerPolicy"] = o.ConsumerPolicy
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ProducerPolicy) {
		toSerialize["producerPolicy"] = o.ProducerPolicy
	}
	if !IsNil(o.ServiceName) {
		toSerialize["serviceName"] = o.ServiceName
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableV1ExtranetPublicVifCheckPostResponse struct {
	value *V1ExtranetPublicVifCheckPostResponse
	isSet bool
}

func (v NullableV1ExtranetPublicVifCheckPostResponse) Get() *V1ExtranetPublicVifCheckPostResponse {
	return v.value
}

func (v *NullableV1ExtranetPublicVifCheckPostResponse) Set(val *V1ExtranetPublicVifCheckPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetPublicVifCheckPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetPublicVifCheckPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetPublicVifCheckPostResponse(val *V1ExtranetPublicVifCheckPostResponse) *NullableV1ExtranetPublicVifCheckPostResponse {
	return &NullableV1ExtranetPublicVifCheckPostResponse{value: val, isSet: true}
}

func (v NullableV1ExtranetPublicVifCheckPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetPublicVifCheckPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


