/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2NullableMaCsecRekeyInterval type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2NullableMaCsecRekeyInterval{}

// ManaV2NullableMaCsecRekeyInterval struct for ManaV2NullableMaCsecRekeyInterval
type ManaV2NullableMaCsecRekeyInterval struct {
	RekeyInterval *int64 `json:"rekeyInterval,omitempty"`
}

// NewManaV2NullableMaCsecRekeyInterval instantiates a new ManaV2NullableMaCsecRekeyInterval object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2NullableMaCsecRekeyInterval() *ManaV2NullableMaCsecRekeyInterval {
	this := ManaV2NullableMaCsecRekeyInterval{}
	return &this
}

// NewManaV2NullableMaCsecRekeyIntervalWithDefaults instantiates a new ManaV2NullableMaCsecRekeyInterval object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2NullableMaCsecRekeyIntervalWithDefaults() *ManaV2NullableMaCsecRekeyInterval {
	this := ManaV2NullableMaCsecRekeyInterval{}
	return &this
}

// GetRekeyInterval returns the RekeyInterval field value if set, zero value otherwise.
func (o *ManaV2NullableMaCsecRekeyInterval) GetRekeyInterval() int64 {
	if o == nil || IsNil(o.RekeyInterval) {
		var ret int64
		return ret
	}
	return *o.RekeyInterval
}

// GetRekeyIntervalOk returns a tuple with the RekeyInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2NullableMaCsecRekeyInterval) GetRekeyIntervalOk() (*int64, bool) {
	if o == nil || IsNil(o.RekeyInterval) {
		return nil, false
	}
	return o.RekeyInterval, true
}

// HasRekeyInterval returns a boolean if a field has been set.
func (o *ManaV2NullableMaCsecRekeyInterval) HasRekeyInterval() bool {
	if o != nil && !IsNil(o.RekeyInterval) {
		return true
	}

	return false
}

// SetRekeyInterval gets a reference to the given int64 and assigns it to the RekeyInterval field.
func (o *ManaV2NullableMaCsecRekeyInterval) SetRekeyInterval(v int64) {
	o.RekeyInterval = &v
}

func (o ManaV2NullableMaCsecRekeyInterval) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2NullableMaCsecRekeyInterval) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RekeyInterval) {
		toSerialize["rekeyInterval"] = o.RekeyInterval
	}
	return toSerialize, nil
}

type NullableManaV2NullableMaCsecRekeyInterval struct {
	value *ManaV2NullableMaCsecRekeyInterval
	isSet bool
}

func (v NullableManaV2NullableMaCsecRekeyInterval) Get() *ManaV2NullableMaCsecRekeyInterval {
	return v.value
}

func (v *NullableManaV2NullableMaCsecRekeyInterval) Set(val *ManaV2NullableMaCsecRekeyInterval) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2NullableMaCsecRekeyInterval) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2NullableMaCsecRekeyInterval) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2NullableMaCsecRekeyInterval(val *ManaV2NullableMaCsecRekeyInterval) *NullableManaV2NullableMaCsecRekeyInterval {
	return &NullableManaV2NullableMaCsecRekeyInterval{value: val, isSet: true}
}

func (v NullableManaV2NullableMaCsecRekeyInterval) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2NullableMaCsecRekeyInterval) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


