/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ManaV2PublicVifGatewayDecentralizedPrefixes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2PublicVifGatewayDecentralizedPrefixes{}

// ManaV2PublicVifGatewayDecentralizedPrefixes struct for ManaV2PublicVifGatewayDecentralizedPrefixes
type ManaV2PublicVifGatewayDecentralizedPrefixes struct {
	Prefixes map[string]string `json:"prefixes"`
}

type _ManaV2PublicVifGatewayDecentralizedPrefixes ManaV2PublicVifGatewayDecentralizedPrefixes

// NewManaV2PublicVifGatewayDecentralizedPrefixes instantiates a new ManaV2PublicVifGatewayDecentralizedPrefixes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2PublicVifGatewayDecentralizedPrefixes(prefixes map[string]string) *ManaV2PublicVifGatewayDecentralizedPrefixes {
	this := ManaV2PublicVifGatewayDecentralizedPrefixes{}
	this.Prefixes = prefixes
	return &this
}

// NewManaV2PublicVifGatewayDecentralizedPrefixesWithDefaults instantiates a new ManaV2PublicVifGatewayDecentralizedPrefixes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2PublicVifGatewayDecentralizedPrefixesWithDefaults() *ManaV2PublicVifGatewayDecentralizedPrefixes {
	this := ManaV2PublicVifGatewayDecentralizedPrefixes{}
	return &this
}

// GetPrefixes returns the Prefixes field value
func (o *ManaV2PublicVifGatewayDecentralizedPrefixes) GetPrefixes() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Prefixes
}

// GetPrefixesOk returns a tuple with the Prefixes field value
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifGatewayDecentralizedPrefixes) GetPrefixesOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prefixes, true
}

// SetPrefixes sets field value
func (o *ManaV2PublicVifGatewayDecentralizedPrefixes) SetPrefixes(v map[string]string) {
	o.Prefixes = v
}

func (o ManaV2PublicVifGatewayDecentralizedPrefixes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2PublicVifGatewayDecentralizedPrefixes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["prefixes"] = o.Prefixes
	return toSerialize, nil
}

func (o *ManaV2PublicVifGatewayDecentralizedPrefixes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"prefixes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManaV2PublicVifGatewayDecentralizedPrefixes := _ManaV2PublicVifGatewayDecentralizedPrefixes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManaV2PublicVifGatewayDecentralizedPrefixes)

	if err != nil {
		return err
	}

	*o = ManaV2PublicVifGatewayDecentralizedPrefixes(varManaV2PublicVifGatewayDecentralizedPrefixes)

	return err
}

type NullableManaV2PublicVifGatewayDecentralizedPrefixes struct {
	value *ManaV2PublicVifGatewayDecentralizedPrefixes
	isSet bool
}

func (v NullableManaV2PublicVifGatewayDecentralizedPrefixes) Get() *ManaV2PublicVifGatewayDecentralizedPrefixes {
	return v.value
}

func (v *NullableManaV2PublicVifGatewayDecentralizedPrefixes) Set(val *ManaV2PublicVifGatewayDecentralizedPrefixes) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2PublicVifGatewayDecentralizedPrefixes) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2PublicVifGatewayDecentralizedPrefixes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2PublicVifGatewayDecentralizedPrefixes(val *ManaV2PublicVifGatewayDecentralizedPrefixes) *NullableManaV2PublicVifGatewayDecentralizedPrefixes {
	return &NullableManaV2PublicVifGatewayDecentralizedPrefixes{value: val, isSet: true}
}

func (v NullableManaV2PublicVifGatewayDecentralizedPrefixes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2PublicVifGatewayDecentralizedPrefixes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


