/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the AssuranceWhenWidget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssuranceWhenWidget{}

// AssuranceWhenWidget struct for AssuranceWhenWidget
type AssuranceWhenWidget struct {
	DayOfWeek []AssuranceKpiMetric `json:"dayOfWeek,omitempty"`
	HourOfDay []AssuranceKpiMetric `json:"hourOfDay,omitempty"`
	MonthlyActiveUsers []AssuranceKpiMetric `json:"monthlyActiveUsers,omitempty"`
	MonthlyBandwidthTransferred []AssuranceKpiMetric `json:"monthlyBandwidthTransferred,omitempty"`
}

// NewAssuranceWhenWidget instantiates a new AssuranceWhenWidget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssuranceWhenWidget() *AssuranceWhenWidget {
	this := AssuranceWhenWidget{}
	return &this
}

// NewAssuranceWhenWidgetWithDefaults instantiates a new AssuranceWhenWidget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssuranceWhenWidgetWithDefaults() *AssuranceWhenWidget {
	this := AssuranceWhenWidget{}
	return &this
}

// GetDayOfWeek returns the DayOfWeek field value if set, zero value otherwise.
func (o *AssuranceWhenWidget) GetDayOfWeek() []AssuranceKpiMetric {
	if o == nil || IsNil(o.DayOfWeek) {
		var ret []AssuranceKpiMetric
		return ret
	}
	return o.DayOfWeek
}

// GetDayOfWeekOk returns a tuple with the DayOfWeek field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceWhenWidget) GetDayOfWeekOk() ([]AssuranceKpiMetric, bool) {
	if o == nil || IsNil(o.DayOfWeek) {
		return nil, false
	}
	return o.DayOfWeek, true
}

// HasDayOfWeek returns a boolean if a field has been set.
func (o *AssuranceWhenWidget) HasDayOfWeek() bool {
	if o != nil && !IsNil(o.DayOfWeek) {
		return true
	}

	return false
}

// SetDayOfWeek gets a reference to the given []AssuranceKpiMetric and assigns it to the DayOfWeek field.
func (o *AssuranceWhenWidget) SetDayOfWeek(v []AssuranceKpiMetric) {
	o.DayOfWeek = v
}

// GetHourOfDay returns the HourOfDay field value if set, zero value otherwise.
func (o *AssuranceWhenWidget) GetHourOfDay() []AssuranceKpiMetric {
	if o == nil || IsNil(o.HourOfDay) {
		var ret []AssuranceKpiMetric
		return ret
	}
	return o.HourOfDay
}

// GetHourOfDayOk returns a tuple with the HourOfDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceWhenWidget) GetHourOfDayOk() ([]AssuranceKpiMetric, bool) {
	if o == nil || IsNil(o.HourOfDay) {
		return nil, false
	}
	return o.HourOfDay, true
}

// HasHourOfDay returns a boolean if a field has been set.
func (o *AssuranceWhenWidget) HasHourOfDay() bool {
	if o != nil && !IsNil(o.HourOfDay) {
		return true
	}

	return false
}

// SetHourOfDay gets a reference to the given []AssuranceKpiMetric and assigns it to the HourOfDay field.
func (o *AssuranceWhenWidget) SetHourOfDay(v []AssuranceKpiMetric) {
	o.HourOfDay = v
}

// GetMonthlyActiveUsers returns the MonthlyActiveUsers field value if set, zero value otherwise.
func (o *AssuranceWhenWidget) GetMonthlyActiveUsers() []AssuranceKpiMetric {
	if o == nil || IsNil(o.MonthlyActiveUsers) {
		var ret []AssuranceKpiMetric
		return ret
	}
	return o.MonthlyActiveUsers
}

// GetMonthlyActiveUsersOk returns a tuple with the MonthlyActiveUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceWhenWidget) GetMonthlyActiveUsersOk() ([]AssuranceKpiMetric, bool) {
	if o == nil || IsNil(o.MonthlyActiveUsers) {
		return nil, false
	}
	return o.MonthlyActiveUsers, true
}

// HasMonthlyActiveUsers returns a boolean if a field has been set.
func (o *AssuranceWhenWidget) HasMonthlyActiveUsers() bool {
	if o != nil && !IsNil(o.MonthlyActiveUsers) {
		return true
	}

	return false
}

// SetMonthlyActiveUsers gets a reference to the given []AssuranceKpiMetric and assigns it to the MonthlyActiveUsers field.
func (o *AssuranceWhenWidget) SetMonthlyActiveUsers(v []AssuranceKpiMetric) {
	o.MonthlyActiveUsers = v
}

// GetMonthlyBandwidthTransferred returns the MonthlyBandwidthTransferred field value if set, zero value otherwise.
func (o *AssuranceWhenWidget) GetMonthlyBandwidthTransferred() []AssuranceKpiMetric {
	if o == nil || IsNil(o.MonthlyBandwidthTransferred) {
		var ret []AssuranceKpiMetric
		return ret
	}
	return o.MonthlyBandwidthTransferred
}

// GetMonthlyBandwidthTransferredOk returns a tuple with the MonthlyBandwidthTransferred field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceWhenWidget) GetMonthlyBandwidthTransferredOk() ([]AssuranceKpiMetric, bool) {
	if o == nil || IsNil(o.MonthlyBandwidthTransferred) {
		return nil, false
	}
	return o.MonthlyBandwidthTransferred, true
}

// HasMonthlyBandwidthTransferred returns a boolean if a field has been set.
func (o *AssuranceWhenWidget) HasMonthlyBandwidthTransferred() bool {
	if o != nil && !IsNil(o.MonthlyBandwidthTransferred) {
		return true
	}

	return false
}

// SetMonthlyBandwidthTransferred gets a reference to the given []AssuranceKpiMetric and assigns it to the MonthlyBandwidthTransferred field.
func (o *AssuranceWhenWidget) SetMonthlyBandwidthTransferred(v []AssuranceKpiMetric) {
	o.MonthlyBandwidthTransferred = v
}

func (o AssuranceWhenWidget) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssuranceWhenWidget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DayOfWeek) {
		toSerialize["dayOfWeek"] = o.DayOfWeek
	}
	if !IsNil(o.HourOfDay) {
		toSerialize["hourOfDay"] = o.HourOfDay
	}
	if !IsNil(o.MonthlyActiveUsers) {
		toSerialize["monthlyActiveUsers"] = o.MonthlyActiveUsers
	}
	if !IsNil(o.MonthlyBandwidthTransferred) {
		toSerialize["monthlyBandwidthTransferred"] = o.MonthlyBandwidthTransferred
	}
	return toSerialize, nil
}

type NullableAssuranceWhenWidget struct {
	value *AssuranceWhenWidget
	isSet bool
}

func (v NullableAssuranceWhenWidget) Get() *AssuranceWhenWidget {
	return v.value
}

func (v *NullableAssuranceWhenWidget) Set(val *AssuranceWhenWidget) {
	v.value = val
	v.isSet = true
}

func (v NullableAssuranceWhenWidget) IsSet() bool {
	return v.isSet
}

func (v *NullableAssuranceWhenWidget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssuranceWhenWidget(val *AssuranceWhenWidget) *NullableAssuranceWhenWidget {
	return &NullableAssuranceWhenWidget{value: val, isSet: true}
}

func (v NullableAssuranceWhenWidget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssuranceWhenWidget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


