/*
Graphiant APIs

**To use the APIs:**  1) Login using `/api/v1/auth/login`   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: `Bearer <your token>`   5) Click \"Authorize\"   6) All requests are now authorized.  **Token valid for 2 hours. If expired:**   - Login again, click \"Authorize\", paste new token.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1HealthcheckDevicesGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1HealthcheckDevicesGet200Response{}

// V1HealthcheckDevicesGet200Response struct for V1HealthcheckDevicesGet200Response
type V1HealthcheckDevicesGet200Response struct {
	Details []V1HealthcheckDevicesGet200ResponseDetailsInner `json:"details,omitempty"`
}

// NewV1HealthcheckDevicesGet200Response instantiates a new V1HealthcheckDevicesGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1HealthcheckDevicesGet200Response() *V1HealthcheckDevicesGet200Response {
	this := V1HealthcheckDevicesGet200Response{}
	return &this
}

// NewV1HealthcheckDevicesGet200ResponseWithDefaults instantiates a new V1HealthcheckDevicesGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1HealthcheckDevicesGet200ResponseWithDefaults() *V1HealthcheckDevicesGet200Response {
	this := V1HealthcheckDevicesGet200Response{}
	return &this
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *V1HealthcheckDevicesGet200Response) GetDetails() []V1HealthcheckDevicesGet200ResponseDetailsInner {
	if o == nil || IsNil(o.Details) {
		var ret []V1HealthcheckDevicesGet200ResponseDetailsInner
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1HealthcheckDevicesGet200Response) GetDetailsOk() ([]V1HealthcheckDevicesGet200ResponseDetailsInner, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *V1HealthcheckDevicesGet200Response) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given []V1HealthcheckDevicesGet200ResponseDetailsInner and assigns it to the Details field.
func (o *V1HealthcheckDevicesGet200Response) SetDetails(v []V1HealthcheckDevicesGet200ResponseDetailsInner) {
	o.Details = v
}

func (o V1HealthcheckDevicesGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1HealthcheckDevicesGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	return toSerialize, nil
}

type NullableV1HealthcheckDevicesGet200Response struct {
	value *V1HealthcheckDevicesGet200Response
	isSet bool
}

func (v NullableV1HealthcheckDevicesGet200Response) Get() *V1HealthcheckDevicesGet200Response {
	return v.value
}

func (v *NullableV1HealthcheckDevicesGet200Response) Set(val *V1HealthcheckDevicesGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1HealthcheckDevicesGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1HealthcheckDevicesGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1HealthcheckDevicesGet200Response(val *V1HealthcheckDevicesGet200Response) *NullableV1HealthcheckDevicesGet200Response {
	return &NullableV1HealthcheckDevicesGet200Response{value: val, isSet: true}
}

func (v NullableV1HealthcheckDevicesGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1HealthcheckDevicesGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


