/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the AssuranceApprovedAppEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssuranceApprovedAppEntry{}

// AssuranceApprovedAppEntry struct for AssuranceApprovedAppEntry
type AssuranceApprovedAppEntry struct {
	// number of active users (required)
	ActiveUsers *int64 `json:"activeUsers,omitempty"`
	// approved AI tool category (required)
	Category *string `json:"category,omitempty"`
	// data sent in kbps (required)
	DataSentKbps *float64 `json:"dataSentKbps,omitempty"`
	// approved app entry identifier (required)
	Id *string `json:"id,omitempty"`
	// approved AI tool name (required)
	Tool *string `json:"tool,omitempty"`
}

// NewAssuranceApprovedAppEntry instantiates a new AssuranceApprovedAppEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssuranceApprovedAppEntry() *AssuranceApprovedAppEntry {
	this := AssuranceApprovedAppEntry{}
	return &this
}

// NewAssuranceApprovedAppEntryWithDefaults instantiates a new AssuranceApprovedAppEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssuranceApprovedAppEntryWithDefaults() *AssuranceApprovedAppEntry {
	this := AssuranceApprovedAppEntry{}
	return &this
}

// GetActiveUsers returns the ActiveUsers field value if set, zero value otherwise.
func (o *AssuranceApprovedAppEntry) GetActiveUsers() int64 {
	if o == nil || IsNil(o.ActiveUsers) {
		var ret int64
		return ret
	}
	return *o.ActiveUsers
}

// GetActiveUsersOk returns a tuple with the ActiveUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceApprovedAppEntry) GetActiveUsersOk() (*int64, bool) {
	if o == nil || IsNil(o.ActiveUsers) {
		return nil, false
	}
	return o.ActiveUsers, true
}

// HasActiveUsers returns a boolean if a field has been set.
func (o *AssuranceApprovedAppEntry) HasActiveUsers() bool {
	if o != nil && !IsNil(o.ActiveUsers) {
		return true
	}

	return false
}

// SetActiveUsers gets a reference to the given int64 and assigns it to the ActiveUsers field.
func (o *AssuranceApprovedAppEntry) SetActiveUsers(v int64) {
	o.ActiveUsers = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *AssuranceApprovedAppEntry) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceApprovedAppEntry) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *AssuranceApprovedAppEntry) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *AssuranceApprovedAppEntry) SetCategory(v string) {
	o.Category = &v
}

// GetDataSentKbps returns the DataSentKbps field value if set, zero value otherwise.
func (o *AssuranceApprovedAppEntry) GetDataSentKbps() float64 {
	if o == nil || IsNil(o.DataSentKbps) {
		var ret float64
		return ret
	}
	return *o.DataSentKbps
}

// GetDataSentKbpsOk returns a tuple with the DataSentKbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceApprovedAppEntry) GetDataSentKbpsOk() (*float64, bool) {
	if o == nil || IsNil(o.DataSentKbps) {
		return nil, false
	}
	return o.DataSentKbps, true
}

// HasDataSentKbps returns a boolean if a field has been set.
func (o *AssuranceApprovedAppEntry) HasDataSentKbps() bool {
	if o != nil && !IsNil(o.DataSentKbps) {
		return true
	}

	return false
}

// SetDataSentKbps gets a reference to the given float64 and assigns it to the DataSentKbps field.
func (o *AssuranceApprovedAppEntry) SetDataSentKbps(v float64) {
	o.DataSentKbps = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AssuranceApprovedAppEntry) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceApprovedAppEntry) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AssuranceApprovedAppEntry) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AssuranceApprovedAppEntry) SetId(v string) {
	o.Id = &v
}

// GetTool returns the Tool field value if set, zero value otherwise.
func (o *AssuranceApprovedAppEntry) GetTool() string {
	if o == nil || IsNil(o.Tool) {
		var ret string
		return ret
	}
	return *o.Tool
}

// GetToolOk returns a tuple with the Tool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceApprovedAppEntry) GetToolOk() (*string, bool) {
	if o == nil || IsNil(o.Tool) {
		return nil, false
	}
	return o.Tool, true
}

// HasTool returns a boolean if a field has been set.
func (o *AssuranceApprovedAppEntry) HasTool() bool {
	if o != nil && !IsNil(o.Tool) {
		return true
	}

	return false
}

// SetTool gets a reference to the given string and assigns it to the Tool field.
func (o *AssuranceApprovedAppEntry) SetTool(v string) {
	o.Tool = &v
}

func (o AssuranceApprovedAppEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssuranceApprovedAppEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ActiveUsers) {
		toSerialize["activeUsers"] = o.ActiveUsers
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.DataSentKbps) {
		toSerialize["dataSentKbps"] = o.DataSentKbps
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Tool) {
		toSerialize["tool"] = o.Tool
	}
	return toSerialize, nil
}

type NullableAssuranceApprovedAppEntry struct {
	value *AssuranceApprovedAppEntry
	isSet bool
}

func (v NullableAssuranceApprovedAppEntry) Get() *AssuranceApprovedAppEntry {
	return v.value
}

func (v *NullableAssuranceApprovedAppEntry) Set(val *AssuranceApprovedAppEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableAssuranceApprovedAppEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableAssuranceApprovedAppEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssuranceApprovedAppEntry(val *AssuranceApprovedAppEntry) *NullableAssuranceApprovedAppEntry {
	return &NullableAssuranceApprovedAppEntry{value: val, isSet: true}
}

func (v NullableAssuranceApprovedAppEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssuranceApprovedAppEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


