/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetB2bCustomersPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bCustomersPostResponse{}

// V1ExtranetB2bCustomersPostResponse struct for V1ExtranetB2bCustomersPostResponse
type V1ExtranetB2bCustomersPostResponse struct {
	Id *int64 `json:"id,omitempty"`
	Invite *ManaV2ExtranetServiceCustomerInvite `json:"invite,omitempty"`
}

// NewV1ExtranetB2bCustomersPostResponse instantiates a new V1ExtranetB2bCustomersPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bCustomersPostResponse() *V1ExtranetB2bCustomersPostResponse {
	this := V1ExtranetB2bCustomersPostResponse{}
	return &this
}

// NewV1ExtranetB2bCustomersPostResponseWithDefaults instantiates a new V1ExtranetB2bCustomersPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bCustomersPostResponseWithDefaults() *V1ExtranetB2bCustomersPostResponse {
	this := V1ExtranetB2bCustomersPostResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V1ExtranetB2bCustomersPostResponse) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bCustomersPostResponse) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V1ExtranetB2bCustomersPostResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *V1ExtranetB2bCustomersPostResponse) SetId(v int64) {
	o.Id = &v
}

// GetInvite returns the Invite field value if set, zero value otherwise.
func (o *V1ExtranetB2bCustomersPostResponse) GetInvite() ManaV2ExtranetServiceCustomerInvite {
	if o == nil || IsNil(o.Invite) {
		var ret ManaV2ExtranetServiceCustomerInvite
		return ret
	}
	return *o.Invite
}

// GetInviteOk returns a tuple with the Invite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bCustomersPostResponse) GetInviteOk() (*ManaV2ExtranetServiceCustomerInvite, bool) {
	if o == nil || IsNil(o.Invite) {
		return nil, false
	}
	return o.Invite, true
}

// HasInvite returns a boolean if a field has been set.
func (o *V1ExtranetB2bCustomersPostResponse) HasInvite() bool {
	if o != nil && !IsNil(o.Invite) {
		return true
	}

	return false
}

// SetInvite gets a reference to the given ManaV2ExtranetServiceCustomerInvite and assigns it to the Invite field.
func (o *V1ExtranetB2bCustomersPostResponse) SetInvite(v ManaV2ExtranetServiceCustomerInvite) {
	o.Invite = &v
}

func (o V1ExtranetB2bCustomersPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bCustomersPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Invite) {
		toSerialize["invite"] = o.Invite
	}
	return toSerialize, nil
}

type NullableV1ExtranetB2bCustomersPostResponse struct {
	value *V1ExtranetB2bCustomersPostResponse
	isSet bool
}

func (v NullableV1ExtranetB2bCustomersPostResponse) Get() *V1ExtranetB2bCustomersPostResponse {
	return v.value
}

func (v *NullableV1ExtranetB2bCustomersPostResponse) Set(val *V1ExtranetB2bCustomersPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bCustomersPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bCustomersPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bCustomersPostResponse(val *V1ExtranetB2bCustomersPostResponse) *NullableV1ExtranetB2bCustomersPostResponse {
	return &NullableV1ExtranetB2bCustomersPostResponse{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bCustomersPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bCustomersPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


