/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetB2bMatchesCustomersPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bMatchesCustomersPostRequest{}

// V1ExtranetB2bMatchesCustomersPostRequest struct for V1ExtranetB2bMatchesCustomersPostRequest
type V1ExtranetB2bMatchesCustomersPostRequest struct {
	Customers []ManaV2ExtranetServiceProducerCustomer `json:"customers,omitempty"`
	ServiceId *int64 `json:"serviceId,omitempty"`
}

// NewV1ExtranetB2bMatchesCustomersPostRequest instantiates a new V1ExtranetB2bMatchesCustomersPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bMatchesCustomersPostRequest() *V1ExtranetB2bMatchesCustomersPostRequest {
	this := V1ExtranetB2bMatchesCustomersPostRequest{}
	return &this
}

// NewV1ExtranetB2bMatchesCustomersPostRequestWithDefaults instantiates a new V1ExtranetB2bMatchesCustomersPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bMatchesCustomersPostRequestWithDefaults() *V1ExtranetB2bMatchesCustomersPostRequest {
	this := V1ExtranetB2bMatchesCustomersPostRequest{}
	return &this
}

// GetCustomers returns the Customers field value if set, zero value otherwise.
func (o *V1ExtranetB2bMatchesCustomersPostRequest) GetCustomers() []ManaV2ExtranetServiceProducerCustomer {
	if o == nil || IsNil(o.Customers) {
		var ret []ManaV2ExtranetServiceProducerCustomer
		return ret
	}
	return o.Customers
}

// GetCustomersOk returns a tuple with the Customers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMatchesCustomersPostRequest) GetCustomersOk() ([]ManaV2ExtranetServiceProducerCustomer, bool) {
	if o == nil || IsNil(o.Customers) {
		return nil, false
	}
	return o.Customers, true
}

// HasCustomers returns a boolean if a field has been set.
func (o *V1ExtranetB2bMatchesCustomersPostRequest) HasCustomers() bool {
	if o != nil && !IsNil(o.Customers) {
		return true
	}

	return false
}

// SetCustomers gets a reference to the given []ManaV2ExtranetServiceProducerCustomer and assigns it to the Customers field.
func (o *V1ExtranetB2bMatchesCustomersPostRequest) SetCustomers(v []ManaV2ExtranetServiceProducerCustomer) {
	o.Customers = v
}

// GetServiceId returns the ServiceId field value if set, zero value otherwise.
func (o *V1ExtranetB2bMatchesCustomersPostRequest) GetServiceId() int64 {
	if o == nil || IsNil(o.ServiceId) {
		var ret int64
		return ret
	}
	return *o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMatchesCustomersPostRequest) GetServiceIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ServiceId) {
		return nil, false
	}
	return o.ServiceId, true
}

// HasServiceId returns a boolean if a field has been set.
func (o *V1ExtranetB2bMatchesCustomersPostRequest) HasServiceId() bool {
	if o != nil && !IsNil(o.ServiceId) {
		return true
	}

	return false
}

// SetServiceId gets a reference to the given int64 and assigns it to the ServiceId field.
func (o *V1ExtranetB2bMatchesCustomersPostRequest) SetServiceId(v int64) {
	o.ServiceId = &v
}

func (o V1ExtranetB2bMatchesCustomersPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bMatchesCustomersPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Customers) {
		toSerialize["customers"] = o.Customers
	}
	if !IsNil(o.ServiceId) {
		toSerialize["serviceId"] = o.ServiceId
	}
	return toSerialize, nil
}

type NullableV1ExtranetB2bMatchesCustomersPostRequest struct {
	value *V1ExtranetB2bMatchesCustomersPostRequest
	isSet bool
}

func (v NullableV1ExtranetB2bMatchesCustomersPostRequest) Get() *V1ExtranetB2bMatchesCustomersPostRequest {
	return v.value
}

func (v *NullableV1ExtranetB2bMatchesCustomersPostRequest) Set(val *V1ExtranetB2bMatchesCustomersPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bMatchesCustomersPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bMatchesCustomersPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bMatchesCustomersPostRequest(val *V1ExtranetB2bMatchesCustomersPostRequest) *NullableV1ExtranetB2bMatchesCustomersPostRequest {
	return &NullableV1ExtranetB2bMatchesCustomersPostRequest{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bMatchesCustomersPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bMatchesCustomersPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


