/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2AssuranceCreateAiAdoptionApproveEntryPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2AssuranceCreateAiAdoptionApproveEntryPostRequest{}

// V2AssuranceCreateAiAdoptionApproveEntryPostRequest struct for V2AssuranceCreateAiAdoptionApproveEntryPostRequest
type V2AssuranceCreateAiAdoptionApproveEntryPostRequest struct {
	ApprovedAppEntry AssuranceApprovedAppEntryRequest `json:"approvedAppEntry"`
}

type _V2AssuranceCreateAiAdoptionApproveEntryPostRequest V2AssuranceCreateAiAdoptionApproveEntryPostRequest

// NewV2AssuranceCreateAiAdoptionApproveEntryPostRequest instantiates a new V2AssuranceCreateAiAdoptionApproveEntryPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2AssuranceCreateAiAdoptionApproveEntryPostRequest(approvedAppEntry AssuranceApprovedAppEntryRequest) *V2AssuranceCreateAiAdoptionApproveEntryPostRequest {
	this := V2AssuranceCreateAiAdoptionApproveEntryPostRequest{}
	this.ApprovedAppEntry = approvedAppEntry
	return &this
}

// NewV2AssuranceCreateAiAdoptionApproveEntryPostRequestWithDefaults instantiates a new V2AssuranceCreateAiAdoptionApproveEntryPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2AssuranceCreateAiAdoptionApproveEntryPostRequestWithDefaults() *V2AssuranceCreateAiAdoptionApproveEntryPostRequest {
	this := V2AssuranceCreateAiAdoptionApproveEntryPostRequest{}
	return &this
}

// GetApprovedAppEntry returns the ApprovedAppEntry field value
func (o *V2AssuranceCreateAiAdoptionApproveEntryPostRequest) GetApprovedAppEntry() AssuranceApprovedAppEntryRequest {
	if o == nil {
		var ret AssuranceApprovedAppEntryRequest
		return ret
	}

	return o.ApprovedAppEntry
}

// GetApprovedAppEntryOk returns a tuple with the ApprovedAppEntry field value
// and a boolean to check if the value has been set.
func (o *V2AssuranceCreateAiAdoptionApproveEntryPostRequest) GetApprovedAppEntryOk() (*AssuranceApprovedAppEntryRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApprovedAppEntry, true
}

// SetApprovedAppEntry sets field value
func (o *V2AssuranceCreateAiAdoptionApproveEntryPostRequest) SetApprovedAppEntry(v AssuranceApprovedAppEntryRequest) {
	o.ApprovedAppEntry = v
}

func (o V2AssuranceCreateAiAdoptionApproveEntryPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2AssuranceCreateAiAdoptionApproveEntryPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["approvedAppEntry"] = o.ApprovedAppEntry
	return toSerialize, nil
}

func (o *V2AssuranceCreateAiAdoptionApproveEntryPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"approvedAppEntry",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2AssuranceCreateAiAdoptionApproveEntryPostRequest := _V2AssuranceCreateAiAdoptionApproveEntryPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2AssuranceCreateAiAdoptionApproveEntryPostRequest)

	if err != nil {
		return err
	}

	*o = V2AssuranceCreateAiAdoptionApproveEntryPostRequest(varV2AssuranceCreateAiAdoptionApproveEntryPostRequest)

	return err
}

type NullableV2AssuranceCreateAiAdoptionApproveEntryPostRequest struct {
	value *V2AssuranceCreateAiAdoptionApproveEntryPostRequest
	isSet bool
}

func (v NullableV2AssuranceCreateAiAdoptionApproveEntryPostRequest) Get() *V2AssuranceCreateAiAdoptionApproveEntryPostRequest {
	return v.value
}

func (v *NullableV2AssuranceCreateAiAdoptionApproveEntryPostRequest) Set(val *V2AssuranceCreateAiAdoptionApproveEntryPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AssuranceCreateAiAdoptionApproveEntryPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AssuranceCreateAiAdoptionApproveEntryPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AssuranceCreateAiAdoptionApproveEntryPostRequest(val *V2AssuranceCreateAiAdoptionApproveEntryPostRequest) *NullableV2AssuranceCreateAiAdoptionApproveEntryPostRequest {
	return &NullableV2AssuranceCreateAiAdoptionApproveEntryPostRequest{value: val, isSet: true}
}

func (v NullableV2AssuranceCreateAiAdoptionApproveEntryPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AssuranceCreateAiAdoptionApproveEntryPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


