/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1SoftwareRolloutsPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SoftwareRolloutsPostRequest{}

// V1SoftwareRolloutsPostRequest struct for V1SoftwareRolloutsPostRequest
type V1SoftwareRolloutsPostRequest struct {
	RolloutConfig UpgradeRolloutConfig `json:"rolloutConfig"`
}

type _V1SoftwareRolloutsPostRequest V1SoftwareRolloutsPostRequest

// NewV1SoftwareRolloutsPostRequest instantiates a new V1SoftwareRolloutsPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SoftwareRolloutsPostRequest(rolloutConfig UpgradeRolloutConfig) *V1SoftwareRolloutsPostRequest {
	this := V1SoftwareRolloutsPostRequest{}
	this.RolloutConfig = rolloutConfig
	return &this
}

// NewV1SoftwareRolloutsPostRequestWithDefaults instantiates a new V1SoftwareRolloutsPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SoftwareRolloutsPostRequestWithDefaults() *V1SoftwareRolloutsPostRequest {
	this := V1SoftwareRolloutsPostRequest{}
	return &this
}

// GetRolloutConfig returns the RolloutConfig field value
func (o *V1SoftwareRolloutsPostRequest) GetRolloutConfig() UpgradeRolloutConfig {
	if o == nil {
		var ret UpgradeRolloutConfig
		return ret
	}

	return o.RolloutConfig
}

// GetRolloutConfigOk returns a tuple with the RolloutConfig field value
// and a boolean to check if the value has been set.
func (o *V1SoftwareRolloutsPostRequest) GetRolloutConfigOk() (*UpgradeRolloutConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RolloutConfig, true
}

// SetRolloutConfig sets field value
func (o *V1SoftwareRolloutsPostRequest) SetRolloutConfig(v UpgradeRolloutConfig) {
	o.RolloutConfig = v
}

func (o V1SoftwareRolloutsPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SoftwareRolloutsPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rolloutConfig"] = o.RolloutConfig
	return toSerialize, nil
}

func (o *V1SoftwareRolloutsPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rolloutConfig",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1SoftwareRolloutsPostRequest := _V1SoftwareRolloutsPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1SoftwareRolloutsPostRequest)

	if err != nil {
		return err
	}

	*o = V1SoftwareRolloutsPostRequest(varV1SoftwareRolloutsPostRequest)

	return err
}

type NullableV1SoftwareRolloutsPostRequest struct {
	value *V1SoftwareRolloutsPostRequest
	isSet bool
}

func (v NullableV1SoftwareRolloutsPostRequest) Get() *V1SoftwareRolloutsPostRequest {
	return v.value
}

func (v *NullableV1SoftwareRolloutsPostRequest) Set(val *V1SoftwareRolloutsPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SoftwareRolloutsPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SoftwareRolloutsPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SoftwareRolloutsPostRequest(val *V1SoftwareRolloutsPostRequest) *NullableV1SoftwareRolloutsPostRequest {
	return &NullableV1SoftwareRolloutsPostRequest{value: val, isSet: true}
}

func (v NullableV1SoftwareRolloutsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SoftwareRolloutsPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


