/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2PublicVifSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2PublicVifSummary{}

// ManaV2PublicVifSummary struct for ManaV2PublicVifSummary
type ManaV2PublicVifSummary struct {
	// id of this Public VIF
	Id *int64 `json:"id,omitempty"`
	// name of this Public VIF
	ServiceName *string `json:"serviceName,omitempty"`
	UpdatedAt *GoogleProtobufTimestamp `json:"updatedAt,omitempty"`
	// creator of this Public VIF
	UserName *string `json:"userName,omitempty"`
}

// NewManaV2PublicVifSummary instantiates a new ManaV2PublicVifSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2PublicVifSummary() *ManaV2PublicVifSummary {
	this := ManaV2PublicVifSummary{}
	return &this
}

// NewManaV2PublicVifSummaryWithDefaults instantiates a new ManaV2PublicVifSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2PublicVifSummaryWithDefaults() *ManaV2PublicVifSummary {
	this := ManaV2PublicVifSummary{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ManaV2PublicVifSummary) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifSummary) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ManaV2PublicVifSummary) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ManaV2PublicVifSummary) SetId(v int64) {
	o.Id = &v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise.
func (o *ManaV2PublicVifSummary) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName) {
		var ret string
		return ret
	}
	return *o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifSummary) GetServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceName) {
		return nil, false
	}
	return o.ServiceName, true
}

// HasServiceName returns a boolean if a field has been set.
func (o *ManaV2PublicVifSummary) HasServiceName() bool {
	if o != nil && !IsNil(o.ServiceName) {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given string and assigns it to the ServiceName field.
func (o *ManaV2PublicVifSummary) SetServiceName(v string) {
	o.ServiceName = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ManaV2PublicVifSummary) GetUpdatedAt() GoogleProtobufTimestamp {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret GoogleProtobufTimestamp
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifSummary) GetUpdatedAtOk() (*GoogleProtobufTimestamp, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ManaV2PublicVifSummary) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given GoogleProtobufTimestamp and assigns it to the UpdatedAt field.
func (o *ManaV2PublicVifSummary) SetUpdatedAt(v GoogleProtobufTimestamp) {
	o.UpdatedAt = &v
}

// GetUserName returns the UserName field value if set, zero value otherwise.
func (o *ManaV2PublicVifSummary) GetUserName() string {
	if o == nil || IsNil(o.UserName) {
		var ret string
		return ret
	}
	return *o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifSummary) GetUserNameOk() (*string, bool) {
	if o == nil || IsNil(o.UserName) {
		return nil, false
	}
	return o.UserName, true
}

// HasUserName returns a boolean if a field has been set.
func (o *ManaV2PublicVifSummary) HasUserName() bool {
	if o != nil && !IsNil(o.UserName) {
		return true
	}

	return false
}

// SetUserName gets a reference to the given string and assigns it to the UserName field.
func (o *ManaV2PublicVifSummary) SetUserName(v string) {
	o.UserName = &v
}

func (o ManaV2PublicVifSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2PublicVifSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ServiceName) {
		toSerialize["serviceName"] = o.ServiceName
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.UserName) {
		toSerialize["userName"] = o.UserName
	}
	return toSerialize, nil
}

type NullableManaV2PublicVifSummary struct {
	value *ManaV2PublicVifSummary
	isSet bool
}

func (v NullableManaV2PublicVifSummary) Get() *ManaV2PublicVifSummary {
	return v.value
}

func (v *NullableManaV2PublicVifSummary) Set(val *ManaV2PublicVifSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2PublicVifSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2PublicVifSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2PublicVifSummary(val *ManaV2PublicVifSummary) *NullableManaV2PublicVifSummary {
	return &NullableManaV2PublicVifSummary{value: val, isSet: true}
}

func (v NullableManaV2PublicVifSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2PublicVifSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


