/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2B2BExtranetMatchConsumerDetailsCustomer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2B2BExtranetMatchConsumerDetailsCustomer{}

// ManaV2B2BExtranetMatchConsumerDetailsCustomer struct for ManaV2B2BExtranetMatchConsumerDetailsCustomer
type ManaV2B2BExtranetMatchConsumerDetailsCustomer struct {
	AdminEmails []string `json:"adminEmails,omitempty"`
	CompanyName *string `json:"companyName,omitempty"`
	Id *int64 `json:"id,omitempty"`
	NumSites *int32 `json:"numSites,omitempty"`
}

// NewManaV2B2BExtranetMatchConsumerDetailsCustomer instantiates a new ManaV2B2BExtranetMatchConsumerDetailsCustomer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2B2BExtranetMatchConsumerDetailsCustomer() *ManaV2B2BExtranetMatchConsumerDetailsCustomer {
	this := ManaV2B2BExtranetMatchConsumerDetailsCustomer{}
	return &this
}

// NewManaV2B2BExtranetMatchConsumerDetailsCustomerWithDefaults instantiates a new ManaV2B2BExtranetMatchConsumerDetailsCustomer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2B2BExtranetMatchConsumerDetailsCustomerWithDefaults() *ManaV2B2BExtranetMatchConsumerDetailsCustomer {
	this := ManaV2B2BExtranetMatchConsumerDetailsCustomer{}
	return &this
}

// GetAdminEmails returns the AdminEmails field value if set, zero value otherwise.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) GetAdminEmails() []string {
	if o == nil || IsNil(o.AdminEmails) {
		var ret []string
		return ret
	}
	return o.AdminEmails
}

// GetAdminEmailsOk returns a tuple with the AdminEmails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) GetAdminEmailsOk() ([]string, bool) {
	if o == nil || IsNil(o.AdminEmails) {
		return nil, false
	}
	return o.AdminEmails, true
}

// HasAdminEmails returns a boolean if a field has been set.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) HasAdminEmails() bool {
	if o != nil && !IsNil(o.AdminEmails) {
		return true
	}

	return false
}

// SetAdminEmails gets a reference to the given []string and assigns it to the AdminEmails field.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) SetAdminEmails(v []string) {
	o.AdminEmails = v
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) GetCompanyName() string {
	if o == nil || IsNil(o.CompanyName) {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) GetCompanyNameOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyName) {
		return nil, false
	}
	return o.CompanyName, true
}

// HasCompanyName returns a boolean if a field has been set.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) HasCompanyName() bool {
	if o != nil && !IsNil(o.CompanyName) {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) SetCompanyName(v string) {
	o.CompanyName = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) SetId(v int64) {
	o.Id = &v
}

// GetNumSites returns the NumSites field value if set, zero value otherwise.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) GetNumSites() int32 {
	if o == nil || IsNil(o.NumSites) {
		var ret int32
		return ret
	}
	return *o.NumSites
}

// GetNumSitesOk returns a tuple with the NumSites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) GetNumSitesOk() (*int32, bool) {
	if o == nil || IsNil(o.NumSites) {
		return nil, false
	}
	return o.NumSites, true
}

// HasNumSites returns a boolean if a field has been set.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) HasNumSites() bool {
	if o != nil && !IsNil(o.NumSites) {
		return true
	}

	return false
}

// SetNumSites gets a reference to the given int32 and assigns it to the NumSites field.
func (o *ManaV2B2BExtranetMatchConsumerDetailsCustomer) SetNumSites(v int32) {
	o.NumSites = &v
}

func (o ManaV2B2BExtranetMatchConsumerDetailsCustomer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2B2BExtranetMatchConsumerDetailsCustomer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdminEmails) {
		toSerialize["adminEmails"] = o.AdminEmails
	}
	if !IsNil(o.CompanyName) {
		toSerialize["companyName"] = o.CompanyName
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.NumSites) {
		toSerialize["numSites"] = o.NumSites
	}
	return toSerialize, nil
}

type NullableManaV2B2BExtranetMatchConsumerDetailsCustomer struct {
	value *ManaV2B2BExtranetMatchConsumerDetailsCustomer
	isSet bool
}

func (v NullableManaV2B2BExtranetMatchConsumerDetailsCustomer) Get() *ManaV2B2BExtranetMatchConsumerDetailsCustomer {
	return v.value
}

func (v *NullableManaV2B2BExtranetMatchConsumerDetailsCustomer) Set(val *ManaV2B2BExtranetMatchConsumerDetailsCustomer) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2B2BExtranetMatchConsumerDetailsCustomer) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2B2BExtranetMatchConsumerDetailsCustomer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2B2BExtranetMatchConsumerDetailsCustomer(val *ManaV2B2BExtranetMatchConsumerDetailsCustomer) *NullableManaV2B2BExtranetMatchConsumerDetailsCustomer {
	return &NullableManaV2B2BExtranetMatchConsumerDetailsCustomer{value: val, isSet: true}
}

func (v NullableManaV2B2BExtranetMatchConsumerDetailsCustomer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2B2BExtranetMatchConsumerDetailsCustomer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


