/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2RegionCoordinates type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2RegionCoordinates{}

// ManaV2RegionCoordinates struct for ManaV2RegionCoordinates
type ManaV2RegionCoordinates struct {
	Latitude *float64 `json:"latitude,omitempty"`
	Longitude *float64 `json:"longitude,omitempty"`
}

// NewManaV2RegionCoordinates instantiates a new ManaV2RegionCoordinates object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2RegionCoordinates() *ManaV2RegionCoordinates {
	this := ManaV2RegionCoordinates{}
	return &this
}

// NewManaV2RegionCoordinatesWithDefaults instantiates a new ManaV2RegionCoordinates object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2RegionCoordinatesWithDefaults() *ManaV2RegionCoordinates {
	this := ManaV2RegionCoordinates{}
	return &this
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *ManaV2RegionCoordinates) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude) {
		var ret float64
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2RegionCoordinates) GetLatitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *ManaV2RegionCoordinates) HasLatitude() bool {
	if o != nil && !IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given float64 and assigns it to the Latitude field.
func (o *ManaV2RegionCoordinates) SetLatitude(v float64) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *ManaV2RegionCoordinates) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude) {
		var ret float64
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2RegionCoordinates) GetLongitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *ManaV2RegionCoordinates) HasLongitude() bool {
	if o != nil && !IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given float64 and assigns it to the Longitude field.
func (o *ManaV2RegionCoordinates) SetLongitude(v float64) {
	o.Longitude = &v
}

func (o ManaV2RegionCoordinates) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2RegionCoordinates) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	return toSerialize, nil
}

type NullableManaV2RegionCoordinates struct {
	value *ManaV2RegionCoordinates
	isSet bool
}

func (v NullableManaV2RegionCoordinates) Get() *ManaV2RegionCoordinates {
	return v.value
}

func (v *NullableManaV2RegionCoordinates) Set(val *ManaV2RegionCoordinates) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2RegionCoordinates) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2RegionCoordinates) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2RegionCoordinates(val *ManaV2RegionCoordinates) *NullableManaV2RegionCoordinates {
	return &NullableManaV2RegionCoordinates{value: val, isSet: true}
}

func (v NullableManaV2RegionCoordinates) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2RegionCoordinates) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


