/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetB2bProducerReviewPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bProducerReviewPostResponse{}

// V1ExtranetB2bProducerReviewPostResponse struct for V1ExtranetB2bProducerReviewPostResponse
type V1ExtranetB2bProducerReviewPostResponse struct {
	ActivityId *string `json:"activityId,omitempty"`
	Id *int64 `json:"id,omitempty"`
	Policy *ManaV2ExtranetServicePolicyResponse `json:"policy,omitempty"`
}

// NewV1ExtranetB2bProducerReviewPostResponse instantiates a new V1ExtranetB2bProducerReviewPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bProducerReviewPostResponse() *V1ExtranetB2bProducerReviewPostResponse {
	this := V1ExtranetB2bProducerReviewPostResponse{}
	return &this
}

// NewV1ExtranetB2bProducerReviewPostResponseWithDefaults instantiates a new V1ExtranetB2bProducerReviewPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bProducerReviewPostResponseWithDefaults() *V1ExtranetB2bProducerReviewPostResponse {
	this := V1ExtranetB2bProducerReviewPostResponse{}
	return &this
}

// GetActivityId returns the ActivityId field value if set, zero value otherwise.
func (o *V1ExtranetB2bProducerReviewPostResponse) GetActivityId() string {
	if o == nil || IsNil(o.ActivityId) {
		var ret string
		return ret
	}
	return *o.ActivityId
}

// GetActivityIdOk returns a tuple with the ActivityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bProducerReviewPostResponse) GetActivityIdOk() (*string, bool) {
	if o == nil || IsNil(o.ActivityId) {
		return nil, false
	}
	return o.ActivityId, true
}

// HasActivityId returns a boolean if a field has been set.
func (o *V1ExtranetB2bProducerReviewPostResponse) HasActivityId() bool {
	if o != nil && !IsNil(o.ActivityId) {
		return true
	}

	return false
}

// SetActivityId gets a reference to the given string and assigns it to the ActivityId field.
func (o *V1ExtranetB2bProducerReviewPostResponse) SetActivityId(v string) {
	o.ActivityId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V1ExtranetB2bProducerReviewPostResponse) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bProducerReviewPostResponse) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V1ExtranetB2bProducerReviewPostResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *V1ExtranetB2bProducerReviewPostResponse) SetId(v int64) {
	o.Id = &v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *V1ExtranetB2bProducerReviewPostResponse) GetPolicy() ManaV2ExtranetServicePolicyResponse {
	if o == nil || IsNil(o.Policy) {
		var ret ManaV2ExtranetServicePolicyResponse
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bProducerReviewPostResponse) GetPolicyOk() (*ManaV2ExtranetServicePolicyResponse, bool) {
	if o == nil || IsNil(o.Policy) {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *V1ExtranetB2bProducerReviewPostResponse) HasPolicy() bool {
	if o != nil && !IsNil(o.Policy) {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given ManaV2ExtranetServicePolicyResponse and assigns it to the Policy field.
func (o *V1ExtranetB2bProducerReviewPostResponse) SetPolicy(v ManaV2ExtranetServicePolicyResponse) {
	o.Policy = &v
}

func (o V1ExtranetB2bProducerReviewPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bProducerReviewPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ActivityId) {
		toSerialize["activityId"] = o.ActivityId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Policy) {
		toSerialize["policy"] = o.Policy
	}
	return toSerialize, nil
}

type NullableV1ExtranetB2bProducerReviewPostResponse struct {
	value *V1ExtranetB2bProducerReviewPostResponse
	isSet bool
}

func (v NullableV1ExtranetB2bProducerReviewPostResponse) Get() *V1ExtranetB2bProducerReviewPostResponse {
	return v.value
}

func (v *NullableV1ExtranetB2bProducerReviewPostResponse) Set(val *V1ExtranetB2bProducerReviewPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bProducerReviewPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bProducerReviewPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bProducerReviewPostResponse(val *V1ExtranetB2bProducerReviewPostResponse) *NullableV1ExtranetB2bProducerReviewPostResponse {
	return &NullableV1ExtranetB2bProducerReviewPostResponse{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bProducerReviewPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bProducerReviewPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


