/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V2AssuranceCreateAiAdoptionApproveEntryPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2AssuranceCreateAiAdoptionApproveEntryPostResponse{}

// V2AssuranceCreateAiAdoptionApproveEntryPostResponse struct for V2AssuranceCreateAiAdoptionApproveEntryPostResponse
type V2AssuranceCreateAiAdoptionApproveEntryPostResponse struct {
	// identifier of the created approved app entry (required)
	Id *string `json:"id,omitempty"`
}

// NewV2AssuranceCreateAiAdoptionApproveEntryPostResponse instantiates a new V2AssuranceCreateAiAdoptionApproveEntryPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2AssuranceCreateAiAdoptionApproveEntryPostResponse() *V2AssuranceCreateAiAdoptionApproveEntryPostResponse {
	this := V2AssuranceCreateAiAdoptionApproveEntryPostResponse{}
	return &this
}

// NewV2AssuranceCreateAiAdoptionApproveEntryPostResponseWithDefaults instantiates a new V2AssuranceCreateAiAdoptionApproveEntryPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2AssuranceCreateAiAdoptionApproveEntryPostResponseWithDefaults() *V2AssuranceCreateAiAdoptionApproveEntryPostResponse {
	this := V2AssuranceCreateAiAdoptionApproveEntryPostResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V2AssuranceCreateAiAdoptionApproveEntryPostResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2AssuranceCreateAiAdoptionApproveEntryPostResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V2AssuranceCreateAiAdoptionApproveEntryPostResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *V2AssuranceCreateAiAdoptionApproveEntryPostResponse) SetId(v string) {
	o.Id = &v
}

func (o V2AssuranceCreateAiAdoptionApproveEntryPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2AssuranceCreateAiAdoptionApproveEntryPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableV2AssuranceCreateAiAdoptionApproveEntryPostResponse struct {
	value *V2AssuranceCreateAiAdoptionApproveEntryPostResponse
	isSet bool
}

func (v NullableV2AssuranceCreateAiAdoptionApproveEntryPostResponse) Get() *V2AssuranceCreateAiAdoptionApproveEntryPostResponse {
	return v.value
}

func (v *NullableV2AssuranceCreateAiAdoptionApproveEntryPostResponse) Set(val *V2AssuranceCreateAiAdoptionApproveEntryPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AssuranceCreateAiAdoptionApproveEntryPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AssuranceCreateAiAdoptionApproveEntryPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AssuranceCreateAiAdoptionApproveEntryPostResponse(val *V2AssuranceCreateAiAdoptionApproveEntryPostResponse) *NullableV2AssuranceCreateAiAdoptionApproveEntryPostResponse {
	return &NullableV2AssuranceCreateAiAdoptionApproveEntryPostResponse{value: val, isSet: true}
}

func (v NullableV2AssuranceCreateAiAdoptionApproveEntryPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AssuranceCreateAiAdoptionApproveEntryPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


