/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2ExtranetNatTranslationCentralized type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2ExtranetNatTranslationCentralized{}

// ManaV2ExtranetNatTranslationCentralized struct for ManaV2ExtranetNatTranslationCentralized
type ManaV2ExtranetNatTranslationCentralized struct {
	Prefixes *map[string]ManaV2ExtranetNatTranslationDevicePrefixes `json:"prefixes,omitempty"`
}

// NewManaV2ExtranetNatTranslationCentralized instantiates a new ManaV2ExtranetNatTranslationCentralized object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2ExtranetNatTranslationCentralized() *ManaV2ExtranetNatTranslationCentralized {
	this := ManaV2ExtranetNatTranslationCentralized{}
	return &this
}

// NewManaV2ExtranetNatTranslationCentralizedWithDefaults instantiates a new ManaV2ExtranetNatTranslationCentralized object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2ExtranetNatTranslationCentralizedWithDefaults() *ManaV2ExtranetNatTranslationCentralized {
	this := ManaV2ExtranetNatTranslationCentralized{}
	return &this
}

// GetPrefixes returns the Prefixes field value if set, zero value otherwise.
func (o *ManaV2ExtranetNatTranslationCentralized) GetPrefixes() map[string]ManaV2ExtranetNatTranslationDevicePrefixes {
	if o == nil || IsNil(o.Prefixes) {
		var ret map[string]ManaV2ExtranetNatTranslationDevicePrefixes
		return ret
	}
	return *o.Prefixes
}

// GetPrefixesOk returns a tuple with the Prefixes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetNatTranslationCentralized) GetPrefixesOk() (*map[string]ManaV2ExtranetNatTranslationDevicePrefixes, bool) {
	if o == nil || IsNil(o.Prefixes) {
		return nil, false
	}
	return o.Prefixes, true
}

// HasPrefixes returns a boolean if a field has been set.
func (o *ManaV2ExtranetNatTranslationCentralized) HasPrefixes() bool {
	if o != nil && !IsNil(o.Prefixes) {
		return true
	}

	return false
}

// SetPrefixes gets a reference to the given map[string]ManaV2ExtranetNatTranslationDevicePrefixes and assigns it to the Prefixes field.
func (o *ManaV2ExtranetNatTranslationCentralized) SetPrefixes(v map[string]ManaV2ExtranetNatTranslationDevicePrefixes) {
	o.Prefixes = &v
}

func (o ManaV2ExtranetNatTranslationCentralized) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2ExtranetNatTranslationCentralized) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Prefixes) {
		toSerialize["prefixes"] = o.Prefixes
	}
	return toSerialize, nil
}

type NullableManaV2ExtranetNatTranslationCentralized struct {
	value *ManaV2ExtranetNatTranslationCentralized
	isSet bool
}

func (v NullableManaV2ExtranetNatTranslationCentralized) Get() *ManaV2ExtranetNatTranslationCentralized {
	return v.value
}

func (v *NullableManaV2ExtranetNatTranslationCentralized) Set(val *ManaV2ExtranetNatTranslationCentralized) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2ExtranetNatTranslationCentralized) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2ExtranetNatTranslationCentralized) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2ExtranetNatTranslationCentralized(val *ManaV2ExtranetNatTranslationCentralized) *NullableManaV2ExtranetNatTranslationCentralized {
	return &NullableManaV2ExtranetNatTranslationCentralized{value: val, isSet: true}
}

func (v NullableManaV2ExtranetNatTranslationCentralized) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2ExtranetNatTranslationCentralized) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


