/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SoftwareRolloutsGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SoftwareRolloutsGetResponse{}

// V1SoftwareRolloutsGetResponse struct for V1SoftwareRolloutsGetResponse
type V1SoftwareRolloutsGetResponse struct {
	Rollouts []UpgradeRollout `json:"rollouts,omitempty"`
}

// NewV1SoftwareRolloutsGetResponse instantiates a new V1SoftwareRolloutsGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SoftwareRolloutsGetResponse() *V1SoftwareRolloutsGetResponse {
	this := V1SoftwareRolloutsGetResponse{}
	return &this
}

// NewV1SoftwareRolloutsGetResponseWithDefaults instantiates a new V1SoftwareRolloutsGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SoftwareRolloutsGetResponseWithDefaults() *V1SoftwareRolloutsGetResponse {
	this := V1SoftwareRolloutsGetResponse{}
	return &this
}

// GetRollouts returns the Rollouts field value if set, zero value otherwise.
func (o *V1SoftwareRolloutsGetResponse) GetRollouts() []UpgradeRollout {
	if o == nil || IsNil(o.Rollouts) {
		var ret []UpgradeRollout
		return ret
	}
	return o.Rollouts
}

// GetRolloutsOk returns a tuple with the Rollouts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SoftwareRolloutsGetResponse) GetRolloutsOk() ([]UpgradeRollout, bool) {
	if o == nil || IsNil(o.Rollouts) {
		return nil, false
	}
	return o.Rollouts, true
}

// HasRollouts returns a boolean if a field has been set.
func (o *V1SoftwareRolloutsGetResponse) HasRollouts() bool {
	if o != nil && !IsNil(o.Rollouts) {
		return true
	}

	return false
}

// SetRollouts gets a reference to the given []UpgradeRollout and assigns it to the Rollouts field.
func (o *V1SoftwareRolloutsGetResponse) SetRollouts(v []UpgradeRollout) {
	o.Rollouts = v
}

func (o V1SoftwareRolloutsGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SoftwareRolloutsGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rollouts) {
		toSerialize["rollouts"] = o.Rollouts
	}
	return toSerialize, nil
}

type NullableV1SoftwareRolloutsGetResponse struct {
	value *V1SoftwareRolloutsGetResponse
	isSet bool
}

func (v NullableV1SoftwareRolloutsGetResponse) Get() *V1SoftwareRolloutsGetResponse {
	return v.value
}

func (v *NullableV1SoftwareRolloutsGetResponse) Set(val *V1SoftwareRolloutsGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SoftwareRolloutsGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SoftwareRolloutsGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SoftwareRolloutsGetResponse(val *V1SoftwareRolloutsGetResponse) *NullableV1SoftwareRolloutsGetResponse {
	return &NullableV1SoftwareRolloutsGetResponse{value: val, isSet: true}
}

func (v NullableV1SoftwareRolloutsGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SoftwareRolloutsGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


