/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V2AssuranceAiAdoptionSummaryPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2AssuranceAiAdoptionSummaryPostRequest{}

// V2AssuranceAiAdoptionSummaryPostRequest struct for V2AssuranceAiAdoptionSummaryPostRequest
type V2AssuranceAiAdoptionSummaryPostRequest struct {
	TimeWindow AssuranceTimeWindow `json:"timeWindow"`
	// list size of user list in where widget (required)
	UserListSize int64 `json:"userListSize"`
}

type _V2AssuranceAiAdoptionSummaryPostRequest V2AssuranceAiAdoptionSummaryPostRequest

// NewV2AssuranceAiAdoptionSummaryPostRequest instantiates a new V2AssuranceAiAdoptionSummaryPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2AssuranceAiAdoptionSummaryPostRequest(timeWindow AssuranceTimeWindow, userListSize int64) *V2AssuranceAiAdoptionSummaryPostRequest {
	this := V2AssuranceAiAdoptionSummaryPostRequest{}
	this.TimeWindow = timeWindow
	this.UserListSize = userListSize
	return &this
}

// NewV2AssuranceAiAdoptionSummaryPostRequestWithDefaults instantiates a new V2AssuranceAiAdoptionSummaryPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2AssuranceAiAdoptionSummaryPostRequestWithDefaults() *V2AssuranceAiAdoptionSummaryPostRequest {
	this := V2AssuranceAiAdoptionSummaryPostRequest{}
	return &this
}

// GetTimeWindow returns the TimeWindow field value
func (o *V2AssuranceAiAdoptionSummaryPostRequest) GetTimeWindow() AssuranceTimeWindow {
	if o == nil {
		var ret AssuranceTimeWindow
		return ret
	}

	return o.TimeWindow
}

// GetTimeWindowOk returns a tuple with the TimeWindow field value
// and a boolean to check if the value has been set.
func (o *V2AssuranceAiAdoptionSummaryPostRequest) GetTimeWindowOk() (*AssuranceTimeWindow, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeWindow, true
}

// SetTimeWindow sets field value
func (o *V2AssuranceAiAdoptionSummaryPostRequest) SetTimeWindow(v AssuranceTimeWindow) {
	o.TimeWindow = v
}

// GetUserListSize returns the UserListSize field value
func (o *V2AssuranceAiAdoptionSummaryPostRequest) GetUserListSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UserListSize
}

// GetUserListSizeOk returns a tuple with the UserListSize field value
// and a boolean to check if the value has been set.
func (o *V2AssuranceAiAdoptionSummaryPostRequest) GetUserListSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserListSize, true
}

// SetUserListSize sets field value
func (o *V2AssuranceAiAdoptionSummaryPostRequest) SetUserListSize(v int64) {
	o.UserListSize = v
}

func (o V2AssuranceAiAdoptionSummaryPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2AssuranceAiAdoptionSummaryPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timeWindow"] = o.TimeWindow
	toSerialize["userListSize"] = o.UserListSize
	return toSerialize, nil
}

func (o *V2AssuranceAiAdoptionSummaryPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timeWindow",
		"userListSize",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2AssuranceAiAdoptionSummaryPostRequest := _V2AssuranceAiAdoptionSummaryPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2AssuranceAiAdoptionSummaryPostRequest)

	if err != nil {
		return err
	}

	*o = V2AssuranceAiAdoptionSummaryPostRequest(varV2AssuranceAiAdoptionSummaryPostRequest)

	return err
}

type NullableV2AssuranceAiAdoptionSummaryPostRequest struct {
	value *V2AssuranceAiAdoptionSummaryPostRequest
	isSet bool
}

func (v NullableV2AssuranceAiAdoptionSummaryPostRequest) Get() *V2AssuranceAiAdoptionSummaryPostRequest {
	return v.value
}

func (v *NullableV2AssuranceAiAdoptionSummaryPostRequest) Set(val *V2AssuranceAiAdoptionSummaryPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2AssuranceAiAdoptionSummaryPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2AssuranceAiAdoptionSummaryPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2AssuranceAiAdoptionSummaryPostRequest(val *V2AssuranceAiAdoptionSummaryPostRequest) *NullableV2AssuranceAiAdoptionSummaryPostRequest {
	return &NullableV2AssuranceAiAdoptionSummaryPostRequest{value: val, isSet: true}
}

func (v NullableV2AssuranceAiAdoptionSummaryPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2AssuranceAiAdoptionSummaryPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


