/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2IPsecGatewayPeersConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2IPsecGatewayPeersConfig{}

// ManaV2IPsecGatewayPeersConfig struct for ManaV2IPsecGatewayPeersConfig
type ManaV2IPsecGatewayPeersConfig struct {
	// Name of the IPsec gateway service
	Name *string `json:"name,omitempty"`
	RemotePeers []ManaV2IPsecGatewayRemotePeer `json:"remotePeers,omitempty"`
	Routing *ManaV2IpsecRoutingConfig `json:"routing,omitempty"`
}

// NewManaV2IPsecGatewayPeersConfig instantiates a new ManaV2IPsecGatewayPeersConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2IPsecGatewayPeersConfig() *ManaV2IPsecGatewayPeersConfig {
	this := ManaV2IPsecGatewayPeersConfig{}
	return &this
}

// NewManaV2IPsecGatewayPeersConfigWithDefaults instantiates a new ManaV2IPsecGatewayPeersConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2IPsecGatewayPeersConfigWithDefaults() *ManaV2IPsecGatewayPeersConfig {
	this := ManaV2IPsecGatewayPeersConfig{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ManaV2IPsecGatewayPeersConfig) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2IPsecGatewayPeersConfig) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ManaV2IPsecGatewayPeersConfig) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ManaV2IPsecGatewayPeersConfig) SetName(v string) {
	o.Name = &v
}

// GetRemotePeers returns the RemotePeers field value if set, zero value otherwise.
func (o *ManaV2IPsecGatewayPeersConfig) GetRemotePeers() []ManaV2IPsecGatewayRemotePeer {
	if o == nil || IsNil(o.RemotePeers) {
		var ret []ManaV2IPsecGatewayRemotePeer
		return ret
	}
	return o.RemotePeers
}

// GetRemotePeersOk returns a tuple with the RemotePeers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2IPsecGatewayPeersConfig) GetRemotePeersOk() ([]ManaV2IPsecGatewayRemotePeer, bool) {
	if o == nil || IsNil(o.RemotePeers) {
		return nil, false
	}
	return o.RemotePeers, true
}

// HasRemotePeers returns a boolean if a field has been set.
func (o *ManaV2IPsecGatewayPeersConfig) HasRemotePeers() bool {
	if o != nil && !IsNil(o.RemotePeers) {
		return true
	}

	return false
}

// SetRemotePeers gets a reference to the given []ManaV2IPsecGatewayRemotePeer and assigns it to the RemotePeers field.
func (o *ManaV2IPsecGatewayPeersConfig) SetRemotePeers(v []ManaV2IPsecGatewayRemotePeer) {
	o.RemotePeers = v
}

// GetRouting returns the Routing field value if set, zero value otherwise.
func (o *ManaV2IPsecGatewayPeersConfig) GetRouting() ManaV2IpsecRoutingConfig {
	if o == nil || IsNil(o.Routing) {
		var ret ManaV2IpsecRoutingConfig
		return ret
	}
	return *o.Routing
}

// GetRoutingOk returns a tuple with the Routing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2IPsecGatewayPeersConfig) GetRoutingOk() (*ManaV2IpsecRoutingConfig, bool) {
	if o == nil || IsNil(o.Routing) {
		return nil, false
	}
	return o.Routing, true
}

// HasRouting returns a boolean if a field has been set.
func (o *ManaV2IPsecGatewayPeersConfig) HasRouting() bool {
	if o != nil && !IsNil(o.Routing) {
		return true
	}

	return false
}

// SetRouting gets a reference to the given ManaV2IpsecRoutingConfig and assigns it to the Routing field.
func (o *ManaV2IPsecGatewayPeersConfig) SetRouting(v ManaV2IpsecRoutingConfig) {
	o.Routing = &v
}

func (o ManaV2IPsecGatewayPeersConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2IPsecGatewayPeersConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RemotePeers) {
		toSerialize["remotePeers"] = o.RemotePeers
	}
	if !IsNil(o.Routing) {
		toSerialize["routing"] = o.Routing
	}
	return toSerialize, nil
}

type NullableManaV2IPsecGatewayPeersConfig struct {
	value *ManaV2IPsecGatewayPeersConfig
	isSet bool
}

func (v NullableManaV2IPsecGatewayPeersConfig) Get() *ManaV2IPsecGatewayPeersConfig {
	return v.value
}

func (v *NullableManaV2IPsecGatewayPeersConfig) Set(val *ManaV2IPsecGatewayPeersConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2IPsecGatewayPeersConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2IPsecGatewayPeersConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2IPsecGatewayPeersConfig(val *ManaV2IPsecGatewayPeersConfig) *NullableManaV2IPsecGatewayPeersConfig {
	return &NullableManaV2IPsecGatewayPeersConfig{value: val, isSet: true}
}

func (v NullableManaV2IPsecGatewayPeersConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2IPsecGatewayPeersConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


