/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1RegionsRegionIdGatewaysGetResponseGateway type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1RegionsRegionIdGatewaysGetResponseGateway{}

// V1RegionsRegionIdGatewaysGetResponseGateway struct for V1RegionsRegionIdGatewaysGetResponseGateway
type V1RegionsRegionIdGatewaysGetResponseGateway struct {
	DeviceId *int64 `json:"deviceId,omitempty"`
	Hostname *string `json:"hostname,omitempty"`
}

// NewV1RegionsRegionIdGatewaysGetResponseGateway instantiates a new V1RegionsRegionIdGatewaysGetResponseGateway object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1RegionsRegionIdGatewaysGetResponseGateway() *V1RegionsRegionIdGatewaysGetResponseGateway {
	this := V1RegionsRegionIdGatewaysGetResponseGateway{}
	return &this
}

// NewV1RegionsRegionIdGatewaysGetResponseGatewayWithDefaults instantiates a new V1RegionsRegionIdGatewaysGetResponseGateway object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1RegionsRegionIdGatewaysGetResponseGatewayWithDefaults() *V1RegionsRegionIdGatewaysGetResponseGateway {
	this := V1RegionsRegionIdGatewaysGetResponseGateway{}
	return &this
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *V1RegionsRegionIdGatewaysGetResponseGateway) GetDeviceId() int64 {
	if o == nil || IsNil(o.DeviceId) {
		var ret int64
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1RegionsRegionIdGatewaysGetResponseGateway) GetDeviceIdOk() (*int64, bool) {
	if o == nil || IsNil(o.DeviceId) {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *V1RegionsRegionIdGatewaysGetResponseGateway) HasDeviceId() bool {
	if o != nil && !IsNil(o.DeviceId) {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given int64 and assigns it to the DeviceId field.
func (o *V1RegionsRegionIdGatewaysGetResponseGateway) SetDeviceId(v int64) {
	o.DeviceId = &v
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *V1RegionsRegionIdGatewaysGetResponseGateway) GetHostname() string {
	if o == nil || IsNil(o.Hostname) {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1RegionsRegionIdGatewaysGetResponseGateway) GetHostnameOk() (*string, bool) {
	if o == nil || IsNil(o.Hostname) {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *V1RegionsRegionIdGatewaysGetResponseGateway) HasHostname() bool {
	if o != nil && !IsNil(o.Hostname) {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *V1RegionsRegionIdGatewaysGetResponseGateway) SetHostname(v string) {
	o.Hostname = &v
}

func (o V1RegionsRegionIdGatewaysGetResponseGateway) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1RegionsRegionIdGatewaysGetResponseGateway) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceId) {
		toSerialize["deviceId"] = o.DeviceId
	}
	if !IsNil(o.Hostname) {
		toSerialize["hostname"] = o.Hostname
	}
	return toSerialize, nil
}

type NullableV1RegionsRegionIdGatewaysGetResponseGateway struct {
	value *V1RegionsRegionIdGatewaysGetResponseGateway
	isSet bool
}

func (v NullableV1RegionsRegionIdGatewaysGetResponseGateway) Get() *V1RegionsRegionIdGatewaysGetResponseGateway {
	return v.value
}

func (v *NullableV1RegionsRegionIdGatewaysGetResponseGateway) Set(val *V1RegionsRegionIdGatewaysGetResponseGateway) {
	v.value = val
	v.isSet = true
}

func (v NullableV1RegionsRegionIdGatewaysGetResponseGateway) IsSet() bool {
	return v.isSet
}

func (v *NullableV1RegionsRegionIdGatewaysGetResponseGateway) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1RegionsRegionIdGatewaysGetResponseGateway(val *V1RegionsRegionIdGatewaysGetResponseGateway) *NullableV1RegionsRegionIdGatewaysGetResponseGateway {
	return &NullableV1RegionsRegionIdGatewaysGetResponseGateway{value: val, isSet: true}
}

func (v NullableV1RegionsRegionIdGatewaysGetResponseGateway) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1RegionsRegionIdGatewaysGetResponseGateway) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


