/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2SakConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2SakConfiguration{}

// ManaV2SakConfiguration struct for ManaV2SakConfiguration
type ManaV2SakConfiguration struct {
	CipherSuite *string `json:"cipherSuite,omitempty"`
	// The interface ID (required for when each lag member has a different MACsec configuration - when split_sak_config_by_lag_member is true) (required)
	LagMemberInterfaceId *int64 `json:"lagMemberInterfaceId,omitempty"`
	NullableRekeyInterval *ManaV2NullableMaCsecRekeyInterval `json:"nullableRekeyInterval,omitempty"`
	NullableReplayProtectionWindowSize *ManaV2NullableMaCsecReplayProtectionWindowSize `json:"nullableReplayProtectionWindowSize,omitempty"`
	RekeyInterval *int64 `json:"rekeyInterval,omitempty"`
	ReplayProtectionWindowSize *int64 `json:"replayProtectionWindowSize,omitempty"`
}

// NewManaV2SakConfiguration instantiates a new ManaV2SakConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2SakConfiguration() *ManaV2SakConfiguration {
	this := ManaV2SakConfiguration{}
	return &this
}

// NewManaV2SakConfigurationWithDefaults instantiates a new ManaV2SakConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2SakConfigurationWithDefaults() *ManaV2SakConfiguration {
	this := ManaV2SakConfiguration{}
	return &this
}

// GetCipherSuite returns the CipherSuite field value if set, zero value otherwise.
func (o *ManaV2SakConfiguration) GetCipherSuite() string {
	if o == nil || IsNil(o.CipherSuite) {
		var ret string
		return ret
	}
	return *o.CipherSuite
}

// GetCipherSuiteOk returns a tuple with the CipherSuite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2SakConfiguration) GetCipherSuiteOk() (*string, bool) {
	if o == nil || IsNil(o.CipherSuite) {
		return nil, false
	}
	return o.CipherSuite, true
}

// HasCipherSuite returns a boolean if a field has been set.
func (o *ManaV2SakConfiguration) HasCipherSuite() bool {
	if o != nil && !IsNil(o.CipherSuite) {
		return true
	}

	return false
}

// SetCipherSuite gets a reference to the given string and assigns it to the CipherSuite field.
func (o *ManaV2SakConfiguration) SetCipherSuite(v string) {
	o.CipherSuite = &v
}

// GetLagMemberInterfaceId returns the LagMemberInterfaceId field value if set, zero value otherwise.
func (o *ManaV2SakConfiguration) GetLagMemberInterfaceId() int64 {
	if o == nil || IsNil(o.LagMemberInterfaceId) {
		var ret int64
		return ret
	}
	return *o.LagMemberInterfaceId
}

// GetLagMemberInterfaceIdOk returns a tuple with the LagMemberInterfaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2SakConfiguration) GetLagMemberInterfaceIdOk() (*int64, bool) {
	if o == nil || IsNil(o.LagMemberInterfaceId) {
		return nil, false
	}
	return o.LagMemberInterfaceId, true
}

// HasLagMemberInterfaceId returns a boolean if a field has been set.
func (o *ManaV2SakConfiguration) HasLagMemberInterfaceId() bool {
	if o != nil && !IsNil(o.LagMemberInterfaceId) {
		return true
	}

	return false
}

// SetLagMemberInterfaceId gets a reference to the given int64 and assigns it to the LagMemberInterfaceId field.
func (o *ManaV2SakConfiguration) SetLagMemberInterfaceId(v int64) {
	o.LagMemberInterfaceId = &v
}

// GetNullableRekeyInterval returns the NullableRekeyInterval field value if set, zero value otherwise.
func (o *ManaV2SakConfiguration) GetNullableRekeyInterval() ManaV2NullableMaCsecRekeyInterval {
	if o == nil || IsNil(o.NullableRekeyInterval) {
		var ret ManaV2NullableMaCsecRekeyInterval
		return ret
	}
	return *o.NullableRekeyInterval
}

// GetNullableRekeyIntervalOk returns a tuple with the NullableRekeyInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2SakConfiguration) GetNullableRekeyIntervalOk() (*ManaV2NullableMaCsecRekeyInterval, bool) {
	if o == nil || IsNil(o.NullableRekeyInterval) {
		return nil, false
	}
	return o.NullableRekeyInterval, true
}

// HasNullableRekeyInterval returns a boolean if a field has been set.
func (o *ManaV2SakConfiguration) HasNullableRekeyInterval() bool {
	if o != nil && !IsNil(o.NullableRekeyInterval) {
		return true
	}

	return false
}

// SetNullableRekeyInterval gets a reference to the given ManaV2NullableMaCsecRekeyInterval and assigns it to the NullableRekeyInterval field.
func (o *ManaV2SakConfiguration) SetNullableRekeyInterval(v ManaV2NullableMaCsecRekeyInterval) {
	o.NullableRekeyInterval = &v
}

// GetNullableReplayProtectionWindowSize returns the NullableReplayProtectionWindowSize field value if set, zero value otherwise.
func (o *ManaV2SakConfiguration) GetNullableReplayProtectionWindowSize() ManaV2NullableMaCsecReplayProtectionWindowSize {
	if o == nil || IsNil(o.NullableReplayProtectionWindowSize) {
		var ret ManaV2NullableMaCsecReplayProtectionWindowSize
		return ret
	}
	return *o.NullableReplayProtectionWindowSize
}

// GetNullableReplayProtectionWindowSizeOk returns a tuple with the NullableReplayProtectionWindowSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2SakConfiguration) GetNullableReplayProtectionWindowSizeOk() (*ManaV2NullableMaCsecReplayProtectionWindowSize, bool) {
	if o == nil || IsNil(o.NullableReplayProtectionWindowSize) {
		return nil, false
	}
	return o.NullableReplayProtectionWindowSize, true
}

// HasNullableReplayProtectionWindowSize returns a boolean if a field has been set.
func (o *ManaV2SakConfiguration) HasNullableReplayProtectionWindowSize() bool {
	if o != nil && !IsNil(o.NullableReplayProtectionWindowSize) {
		return true
	}

	return false
}

// SetNullableReplayProtectionWindowSize gets a reference to the given ManaV2NullableMaCsecReplayProtectionWindowSize and assigns it to the NullableReplayProtectionWindowSize field.
func (o *ManaV2SakConfiguration) SetNullableReplayProtectionWindowSize(v ManaV2NullableMaCsecReplayProtectionWindowSize) {
	o.NullableReplayProtectionWindowSize = &v
}

// GetRekeyInterval returns the RekeyInterval field value if set, zero value otherwise.
func (o *ManaV2SakConfiguration) GetRekeyInterval() int64 {
	if o == nil || IsNil(o.RekeyInterval) {
		var ret int64
		return ret
	}
	return *o.RekeyInterval
}

// GetRekeyIntervalOk returns a tuple with the RekeyInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2SakConfiguration) GetRekeyIntervalOk() (*int64, bool) {
	if o == nil || IsNil(o.RekeyInterval) {
		return nil, false
	}
	return o.RekeyInterval, true
}

// HasRekeyInterval returns a boolean if a field has been set.
func (o *ManaV2SakConfiguration) HasRekeyInterval() bool {
	if o != nil && !IsNil(o.RekeyInterval) {
		return true
	}

	return false
}

// SetRekeyInterval gets a reference to the given int64 and assigns it to the RekeyInterval field.
func (o *ManaV2SakConfiguration) SetRekeyInterval(v int64) {
	o.RekeyInterval = &v
}

// GetReplayProtectionWindowSize returns the ReplayProtectionWindowSize field value if set, zero value otherwise.
func (o *ManaV2SakConfiguration) GetReplayProtectionWindowSize() int64 {
	if o == nil || IsNil(o.ReplayProtectionWindowSize) {
		var ret int64
		return ret
	}
	return *o.ReplayProtectionWindowSize
}

// GetReplayProtectionWindowSizeOk returns a tuple with the ReplayProtectionWindowSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2SakConfiguration) GetReplayProtectionWindowSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.ReplayProtectionWindowSize) {
		return nil, false
	}
	return o.ReplayProtectionWindowSize, true
}

// HasReplayProtectionWindowSize returns a boolean if a field has been set.
func (o *ManaV2SakConfiguration) HasReplayProtectionWindowSize() bool {
	if o != nil && !IsNil(o.ReplayProtectionWindowSize) {
		return true
	}

	return false
}

// SetReplayProtectionWindowSize gets a reference to the given int64 and assigns it to the ReplayProtectionWindowSize field.
func (o *ManaV2SakConfiguration) SetReplayProtectionWindowSize(v int64) {
	o.ReplayProtectionWindowSize = &v
}

func (o ManaV2SakConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2SakConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CipherSuite) {
		toSerialize["cipherSuite"] = o.CipherSuite
	}
	if !IsNil(o.LagMemberInterfaceId) {
		toSerialize["lagMemberInterfaceId"] = o.LagMemberInterfaceId
	}
	if !IsNil(o.NullableRekeyInterval) {
		toSerialize["nullableRekeyInterval"] = o.NullableRekeyInterval
	}
	if !IsNil(o.NullableReplayProtectionWindowSize) {
		toSerialize["nullableReplayProtectionWindowSize"] = o.NullableReplayProtectionWindowSize
	}
	if !IsNil(o.RekeyInterval) {
		toSerialize["rekeyInterval"] = o.RekeyInterval
	}
	if !IsNil(o.ReplayProtectionWindowSize) {
		toSerialize["replayProtectionWindowSize"] = o.ReplayProtectionWindowSize
	}
	return toSerialize, nil
}

type NullableManaV2SakConfiguration struct {
	value *ManaV2SakConfiguration
	isSet bool
}

func (v NullableManaV2SakConfiguration) Get() *ManaV2SakConfiguration {
	return v.value
}

func (v *NullableManaV2SakConfiguration) Set(val *ManaV2SakConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2SakConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2SakConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2SakConfiguration(val *ManaV2SakConfiguration) *NullableManaV2SakConfiguration {
	return &NullableManaV2SakConfiguration{value: val, isSet: true}
}

func (v NullableManaV2SakConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2SakConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


