/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1ExtranetB2bMatchesMatchIdGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bMatchesMatchIdGetResponse{}

// V1ExtranetB2bMatchesMatchIdGetResponse struct for V1ExtranetB2bMatchesMatchIdGetResponse
type V1ExtranetB2bMatchesMatchIdGetResponse struct {
	CustomerName *string `json:"customerName,omitempty"`
	Match *ManaV2B2bExtranetMatch `json:"match,omitempty"`
	MatchId *int64 `json:"matchId,omitempty"`
	ServiceName *string `json:"serviceName,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewV1ExtranetB2bMatchesMatchIdGetResponse instantiates a new V1ExtranetB2bMatchesMatchIdGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bMatchesMatchIdGetResponse() *V1ExtranetB2bMatchesMatchIdGetResponse {
	this := V1ExtranetB2bMatchesMatchIdGetResponse{}
	return &this
}

// NewV1ExtranetB2bMatchesMatchIdGetResponseWithDefaults instantiates a new V1ExtranetB2bMatchesMatchIdGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bMatchesMatchIdGetResponseWithDefaults() *V1ExtranetB2bMatchesMatchIdGetResponse {
	this := V1ExtranetB2bMatchesMatchIdGetResponse{}
	return &this
}

// GetCustomerName returns the CustomerName field value if set, zero value otherwise.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) GetCustomerName() string {
	if o == nil || IsNil(o.CustomerName) {
		var ret string
		return ret
	}
	return *o.CustomerName
}

// GetCustomerNameOk returns a tuple with the CustomerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) GetCustomerNameOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerName) {
		return nil, false
	}
	return o.CustomerName, true
}

// HasCustomerName returns a boolean if a field has been set.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) HasCustomerName() bool {
	if o != nil && !IsNil(o.CustomerName) {
		return true
	}

	return false
}

// SetCustomerName gets a reference to the given string and assigns it to the CustomerName field.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) SetCustomerName(v string) {
	o.CustomerName = &v
}

// GetMatch returns the Match field value if set, zero value otherwise.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) GetMatch() ManaV2B2bExtranetMatch {
	if o == nil || IsNil(o.Match) {
		var ret ManaV2B2bExtranetMatch
		return ret
	}
	return *o.Match
}

// GetMatchOk returns a tuple with the Match field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) GetMatchOk() (*ManaV2B2bExtranetMatch, bool) {
	if o == nil || IsNil(o.Match) {
		return nil, false
	}
	return o.Match, true
}

// HasMatch returns a boolean if a field has been set.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) HasMatch() bool {
	if o != nil && !IsNil(o.Match) {
		return true
	}

	return false
}

// SetMatch gets a reference to the given ManaV2B2bExtranetMatch and assigns it to the Match field.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) SetMatch(v ManaV2B2bExtranetMatch) {
	o.Match = &v
}

// GetMatchId returns the MatchId field value if set, zero value otherwise.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) GetMatchId() int64 {
	if o == nil || IsNil(o.MatchId) {
		var ret int64
		return ret
	}
	return *o.MatchId
}

// GetMatchIdOk returns a tuple with the MatchId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) GetMatchIdOk() (*int64, bool) {
	if o == nil || IsNil(o.MatchId) {
		return nil, false
	}
	return o.MatchId, true
}

// HasMatchId returns a boolean if a field has been set.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) HasMatchId() bool {
	if o != nil && !IsNil(o.MatchId) {
		return true
	}

	return false
}

// SetMatchId gets a reference to the given int64 and assigns it to the MatchId field.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) SetMatchId(v int64) {
	o.MatchId = &v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName) {
		var ret string
		return ret
	}
	return *o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) GetServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceName) {
		return nil, false
	}
	return o.ServiceName, true
}

// HasServiceName returns a boolean if a field has been set.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) HasServiceName() bool {
	if o != nil && !IsNil(o.ServiceName) {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given string and assigns it to the ServiceName field.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) SetServiceName(v string) {
	o.ServiceName = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1ExtranetB2bMatchesMatchIdGetResponse) SetStatus(v string) {
	o.Status = &v
}

func (o V1ExtranetB2bMatchesMatchIdGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bMatchesMatchIdGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerName) {
		toSerialize["customerName"] = o.CustomerName
	}
	if !IsNil(o.Match) {
		toSerialize["match"] = o.Match
	}
	if !IsNil(o.MatchId) {
		toSerialize["matchId"] = o.MatchId
	}
	if !IsNil(o.ServiceName) {
		toSerialize["serviceName"] = o.ServiceName
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1ExtranetB2bMatchesMatchIdGetResponse struct {
	value *V1ExtranetB2bMatchesMatchIdGetResponse
	isSet bool
}

func (v NullableV1ExtranetB2bMatchesMatchIdGetResponse) Get() *V1ExtranetB2bMatchesMatchIdGetResponse {
	return v.value
}

func (v *NullableV1ExtranetB2bMatchesMatchIdGetResponse) Set(val *V1ExtranetB2bMatchesMatchIdGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bMatchesMatchIdGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bMatchesMatchIdGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bMatchesMatchIdGetResponse(val *V1ExtranetB2bMatchesMatchIdGetResponse) *NullableV1ExtranetB2bMatchesMatchIdGetResponse {
	return &NullableV1ExtranetB2bMatchesMatchIdGetResponse{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bMatchesMatchIdGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bMatchesMatchIdGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


