/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1ExtranetPublicVifPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetPublicVifPostRequest{}

// V1ExtranetPublicVifPostRequest struct for V1ExtranetPublicVifPostRequest
type V1ExtranetPublicVifPostRequest struct {
	ConsumerPolicy ManaV2PublicVifConsumerPolicy `json:"consumerPolicy"`
	ProducerPolicy ManaV2PublicVifProducerPolicy `json:"producerPolicy"`
	ServiceName *string `json:"serviceName,omitempty"`
	// Type of the service whether it is application or peering (required)
	Type string `json:"type"`
}

type _V1ExtranetPublicVifPostRequest V1ExtranetPublicVifPostRequest

// NewV1ExtranetPublicVifPostRequest instantiates a new V1ExtranetPublicVifPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetPublicVifPostRequest(consumerPolicy ManaV2PublicVifConsumerPolicy, producerPolicy ManaV2PublicVifProducerPolicy, type_ string) *V1ExtranetPublicVifPostRequest {
	this := V1ExtranetPublicVifPostRequest{}
	this.ConsumerPolicy = consumerPolicy
	this.ProducerPolicy = producerPolicy
	this.Type = type_
	return &this
}

// NewV1ExtranetPublicVifPostRequestWithDefaults instantiates a new V1ExtranetPublicVifPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetPublicVifPostRequestWithDefaults() *V1ExtranetPublicVifPostRequest {
	this := V1ExtranetPublicVifPostRequest{}
	return &this
}

// GetConsumerPolicy returns the ConsumerPolicy field value
func (o *V1ExtranetPublicVifPostRequest) GetConsumerPolicy() ManaV2PublicVifConsumerPolicy {
	if o == nil {
		var ret ManaV2PublicVifConsumerPolicy
		return ret
	}

	return o.ConsumerPolicy
}

// GetConsumerPolicyOk returns a tuple with the ConsumerPolicy field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetPublicVifPostRequest) GetConsumerPolicyOk() (*ManaV2PublicVifConsumerPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConsumerPolicy, true
}

// SetConsumerPolicy sets field value
func (o *V1ExtranetPublicVifPostRequest) SetConsumerPolicy(v ManaV2PublicVifConsumerPolicy) {
	o.ConsumerPolicy = v
}

// GetProducerPolicy returns the ProducerPolicy field value
func (o *V1ExtranetPublicVifPostRequest) GetProducerPolicy() ManaV2PublicVifProducerPolicy {
	if o == nil {
		var ret ManaV2PublicVifProducerPolicy
		return ret
	}

	return o.ProducerPolicy
}

// GetProducerPolicyOk returns a tuple with the ProducerPolicy field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetPublicVifPostRequest) GetProducerPolicyOk() (*ManaV2PublicVifProducerPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProducerPolicy, true
}

// SetProducerPolicy sets field value
func (o *V1ExtranetPublicVifPostRequest) SetProducerPolicy(v ManaV2PublicVifProducerPolicy) {
	o.ProducerPolicy = v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise.
func (o *V1ExtranetPublicVifPostRequest) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName) {
		var ret string
		return ret
	}
	return *o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetPublicVifPostRequest) GetServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceName) {
		return nil, false
	}
	return o.ServiceName, true
}

// HasServiceName returns a boolean if a field has been set.
func (o *V1ExtranetPublicVifPostRequest) HasServiceName() bool {
	if o != nil && !IsNil(o.ServiceName) {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given string and assigns it to the ServiceName field.
func (o *V1ExtranetPublicVifPostRequest) SetServiceName(v string) {
	o.ServiceName = &v
}

// GetType returns the Type field value
func (o *V1ExtranetPublicVifPostRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetPublicVifPostRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *V1ExtranetPublicVifPostRequest) SetType(v string) {
	o.Type = v
}

func (o V1ExtranetPublicVifPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetPublicVifPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["consumerPolicy"] = o.ConsumerPolicy
	toSerialize["producerPolicy"] = o.ProducerPolicy
	if !IsNil(o.ServiceName) {
		toSerialize["serviceName"] = o.ServiceName
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *V1ExtranetPublicVifPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"consumerPolicy",
		"producerPolicy",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1ExtranetPublicVifPostRequest := _V1ExtranetPublicVifPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1ExtranetPublicVifPostRequest)

	if err != nil {
		return err
	}

	*o = V1ExtranetPublicVifPostRequest(varV1ExtranetPublicVifPostRequest)

	return err
}

type NullableV1ExtranetPublicVifPostRequest struct {
	value *V1ExtranetPublicVifPostRequest
	isSet bool
}

func (v NullableV1ExtranetPublicVifPostRequest) Get() *V1ExtranetPublicVifPostRequest {
	return v.value
}

func (v *NullableV1ExtranetPublicVifPostRequest) Set(val *V1ExtranetPublicVifPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetPublicVifPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetPublicVifPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetPublicVifPostRequest(val *V1ExtranetPublicVifPostRequest) *NullableV1ExtranetPublicVifPostRequest {
	return &NullableV1ExtranetPublicVifPostRequest{value: val, isSet: true}
}

func (v NullableV1ExtranetPublicVifPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetPublicVifPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


