/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2ExtranetNatTranslationPeerToPeer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2ExtranetNatTranslationPeerToPeer{}

// ManaV2ExtranetNatTranslationPeerToPeer struct for ManaV2ExtranetNatTranslationPeerToPeer
type ManaV2ExtranetNatTranslationPeerToPeer struct {
	Prefixes []ManaV2ExtranetNatTranslationPeerToPeerPrefix `json:"prefixes,omitempty"`
}

// NewManaV2ExtranetNatTranslationPeerToPeer instantiates a new ManaV2ExtranetNatTranslationPeerToPeer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2ExtranetNatTranslationPeerToPeer() *ManaV2ExtranetNatTranslationPeerToPeer {
	this := ManaV2ExtranetNatTranslationPeerToPeer{}
	return &this
}

// NewManaV2ExtranetNatTranslationPeerToPeerWithDefaults instantiates a new ManaV2ExtranetNatTranslationPeerToPeer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2ExtranetNatTranslationPeerToPeerWithDefaults() *ManaV2ExtranetNatTranslationPeerToPeer {
	this := ManaV2ExtranetNatTranslationPeerToPeer{}
	return &this
}

// GetPrefixes returns the Prefixes field value if set, zero value otherwise.
func (o *ManaV2ExtranetNatTranslationPeerToPeer) GetPrefixes() []ManaV2ExtranetNatTranslationPeerToPeerPrefix {
	if o == nil || IsNil(o.Prefixes) {
		var ret []ManaV2ExtranetNatTranslationPeerToPeerPrefix
		return ret
	}
	return o.Prefixes
}

// GetPrefixesOk returns a tuple with the Prefixes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2ExtranetNatTranslationPeerToPeer) GetPrefixesOk() ([]ManaV2ExtranetNatTranslationPeerToPeerPrefix, bool) {
	if o == nil || IsNil(o.Prefixes) {
		return nil, false
	}
	return o.Prefixes, true
}

// HasPrefixes returns a boolean if a field has been set.
func (o *ManaV2ExtranetNatTranslationPeerToPeer) HasPrefixes() bool {
	if o != nil && !IsNil(o.Prefixes) {
		return true
	}

	return false
}

// SetPrefixes gets a reference to the given []ManaV2ExtranetNatTranslationPeerToPeerPrefix and assigns it to the Prefixes field.
func (o *ManaV2ExtranetNatTranslationPeerToPeer) SetPrefixes(v []ManaV2ExtranetNatTranslationPeerToPeerPrefix) {
	o.Prefixes = v
}

func (o ManaV2ExtranetNatTranslationPeerToPeer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2ExtranetNatTranslationPeerToPeer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Prefixes) {
		toSerialize["prefixes"] = o.Prefixes
	}
	return toSerialize, nil
}

type NullableManaV2ExtranetNatTranslationPeerToPeer struct {
	value *ManaV2ExtranetNatTranslationPeerToPeer
	isSet bool
}

func (v NullableManaV2ExtranetNatTranslationPeerToPeer) Get() *ManaV2ExtranetNatTranslationPeerToPeer {
	return v.value
}

func (v *NullableManaV2ExtranetNatTranslationPeerToPeer) Set(val *ManaV2ExtranetNatTranslationPeerToPeer) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2ExtranetNatTranslationPeerToPeer) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2ExtranetNatTranslationPeerToPeer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2ExtranetNatTranslationPeerToPeer(val *ManaV2ExtranetNatTranslationPeerToPeer) *NullableManaV2ExtranetNatTranslationPeerToPeer {
	return &NullableManaV2ExtranetNatTranslationPeerToPeer{value: val, isSet: true}
}

func (v NullableManaV2ExtranetNatTranslationPeerToPeer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2ExtranetNatTranslationPeerToPeer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


