/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the AssuranceKpiMetric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssuranceKpiMetric{}

// AssuranceKpiMetric struct for AssuranceKpiMetric
type AssuranceKpiMetric struct {
	// delta value for the metric
	Delta *float64 `json:"delta,omitempty"`
	// name of the metric
	Name *string `json:"name,omitempty"`
	// AI adoption percent for the metric
	Percent *float64 `json:"percent,omitempty"`
	// AI adoption tag for the metric
	Tag *string `json:"tag,omitempty"`
	// AI adoption token usage value
	TokenUsage *float64 `json:"tokenUsage,omitempty"`
	// metric value (required)
	Value *float64 `json:"value,omitempty"`
}

// NewAssuranceKpiMetric instantiates a new AssuranceKpiMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssuranceKpiMetric() *AssuranceKpiMetric {
	this := AssuranceKpiMetric{}
	return &this
}

// NewAssuranceKpiMetricWithDefaults instantiates a new AssuranceKpiMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssuranceKpiMetricWithDefaults() *AssuranceKpiMetric {
	this := AssuranceKpiMetric{}
	return &this
}

// GetDelta returns the Delta field value if set, zero value otherwise.
func (o *AssuranceKpiMetric) GetDelta() float64 {
	if o == nil || IsNil(o.Delta) {
		var ret float64
		return ret
	}
	return *o.Delta
}

// GetDeltaOk returns a tuple with the Delta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceKpiMetric) GetDeltaOk() (*float64, bool) {
	if o == nil || IsNil(o.Delta) {
		return nil, false
	}
	return o.Delta, true
}

// HasDelta returns a boolean if a field has been set.
func (o *AssuranceKpiMetric) HasDelta() bool {
	if o != nil && !IsNil(o.Delta) {
		return true
	}

	return false
}

// SetDelta gets a reference to the given float64 and assigns it to the Delta field.
func (o *AssuranceKpiMetric) SetDelta(v float64) {
	o.Delta = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AssuranceKpiMetric) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceKpiMetric) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AssuranceKpiMetric) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AssuranceKpiMetric) SetName(v string) {
	o.Name = &v
}

// GetPercent returns the Percent field value if set, zero value otherwise.
func (o *AssuranceKpiMetric) GetPercent() float64 {
	if o == nil || IsNil(o.Percent) {
		var ret float64
		return ret
	}
	return *o.Percent
}

// GetPercentOk returns a tuple with the Percent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceKpiMetric) GetPercentOk() (*float64, bool) {
	if o == nil || IsNil(o.Percent) {
		return nil, false
	}
	return o.Percent, true
}

// HasPercent returns a boolean if a field has been set.
func (o *AssuranceKpiMetric) HasPercent() bool {
	if o != nil && !IsNil(o.Percent) {
		return true
	}

	return false
}

// SetPercent gets a reference to the given float64 and assigns it to the Percent field.
func (o *AssuranceKpiMetric) SetPercent(v float64) {
	o.Percent = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *AssuranceKpiMetric) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceKpiMetric) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *AssuranceKpiMetric) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *AssuranceKpiMetric) SetTag(v string) {
	o.Tag = &v
}

// GetTokenUsage returns the TokenUsage field value if set, zero value otherwise.
func (o *AssuranceKpiMetric) GetTokenUsage() float64 {
	if o == nil || IsNil(o.TokenUsage) {
		var ret float64
		return ret
	}
	return *o.TokenUsage
}

// GetTokenUsageOk returns a tuple with the TokenUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceKpiMetric) GetTokenUsageOk() (*float64, bool) {
	if o == nil || IsNil(o.TokenUsage) {
		return nil, false
	}
	return o.TokenUsage, true
}

// HasTokenUsage returns a boolean if a field has been set.
func (o *AssuranceKpiMetric) HasTokenUsage() bool {
	if o != nil && !IsNil(o.TokenUsage) {
		return true
	}

	return false
}

// SetTokenUsage gets a reference to the given float64 and assigns it to the TokenUsage field.
func (o *AssuranceKpiMetric) SetTokenUsage(v float64) {
	o.TokenUsage = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *AssuranceKpiMetric) GetValue() float64 {
	if o == nil || IsNil(o.Value) {
		var ret float64
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssuranceKpiMetric) GetValueOk() (*float64, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *AssuranceKpiMetric) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float64 and assigns it to the Value field.
func (o *AssuranceKpiMetric) SetValue(v float64) {
	o.Value = &v
}

func (o AssuranceKpiMetric) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssuranceKpiMetric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Delta) {
		toSerialize["delta"] = o.Delta
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Percent) {
		toSerialize["percent"] = o.Percent
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	if !IsNil(o.TokenUsage) {
		toSerialize["tokenUsage"] = o.TokenUsage
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableAssuranceKpiMetric struct {
	value *AssuranceKpiMetric
	isSet bool
}

func (v NullableAssuranceKpiMetric) Get() *AssuranceKpiMetric {
	return v.value
}

func (v *NullableAssuranceKpiMetric) Set(val *AssuranceKpiMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableAssuranceKpiMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableAssuranceKpiMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssuranceKpiMetric(val *AssuranceKpiMetric) *NullableAssuranceKpiMetric {
	return &NullableAssuranceKpiMetric{value: val, isSet: true}
}

func (v NullableAssuranceKpiMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssuranceKpiMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


