/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1PvifIdPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1PvifIdPutRequest{}

// V1PvifIdPutRequest struct for V1PvifIdPutRequest
type V1PvifIdPutRequest struct {
	Configuration ManaV2PublicVifGatewayWriteRequest `json:"configuration"`
}

type _V1PvifIdPutRequest V1PvifIdPutRequest

// NewV1PvifIdPutRequest instantiates a new V1PvifIdPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1PvifIdPutRequest(configuration ManaV2PublicVifGatewayWriteRequest) *V1PvifIdPutRequest {
	this := V1PvifIdPutRequest{}
	this.Configuration = configuration
	return &this
}

// NewV1PvifIdPutRequestWithDefaults instantiates a new V1PvifIdPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1PvifIdPutRequestWithDefaults() *V1PvifIdPutRequest {
	this := V1PvifIdPutRequest{}
	return &this
}

// GetConfiguration returns the Configuration field value
func (o *V1PvifIdPutRequest) GetConfiguration() ManaV2PublicVifGatewayWriteRequest {
	if o == nil {
		var ret ManaV2PublicVifGatewayWriteRequest
		return ret
	}

	return o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value
// and a boolean to check if the value has been set.
func (o *V1PvifIdPutRequest) GetConfigurationOk() (*ManaV2PublicVifGatewayWriteRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Configuration, true
}

// SetConfiguration sets field value
func (o *V1PvifIdPutRequest) SetConfiguration(v ManaV2PublicVifGatewayWriteRequest) {
	o.Configuration = v
}

func (o V1PvifIdPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1PvifIdPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["configuration"] = o.Configuration
	return toSerialize, nil
}

func (o *V1PvifIdPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"configuration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1PvifIdPutRequest := _V1PvifIdPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1PvifIdPutRequest)

	if err != nil {
		return err
	}

	*o = V1PvifIdPutRequest(varV1PvifIdPutRequest)

	return err
}

type NullableV1PvifIdPutRequest struct {
	value *V1PvifIdPutRequest
	isSet bool
}

func (v NullableV1PvifIdPutRequest) Get() *V1PvifIdPutRequest {
	return v.value
}

func (v *NullableV1PvifIdPutRequest) Set(val *V1PvifIdPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1PvifIdPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1PvifIdPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1PvifIdPutRequest(val *V1PvifIdPutRequest) *NullableV1PvifIdPutRequest {
	return &NullableV1PvifIdPutRequest{value: val, isSet: true}
}

func (v NullableV1PvifIdPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1PvifIdPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


