/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1ExtranetPublicVifIdPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetPublicVifIdPutRequest{}

// V1ExtranetPublicVifIdPutRequest struct for V1ExtranetPublicVifIdPutRequest
type V1ExtranetPublicVifIdPutRequest struct {
	ConsumerPolicy *ManaV2PublicVifConsumerPolicy `json:"consumerPolicy,omitempty"`
	ProducerPolicy ManaV2PublicVifProducerPolicy `json:"producerPolicy"`
}

type _V1ExtranetPublicVifIdPutRequest V1ExtranetPublicVifIdPutRequest

// NewV1ExtranetPublicVifIdPutRequest instantiates a new V1ExtranetPublicVifIdPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetPublicVifIdPutRequest(producerPolicy ManaV2PublicVifProducerPolicy) *V1ExtranetPublicVifIdPutRequest {
	this := V1ExtranetPublicVifIdPutRequest{}
	this.ProducerPolicy = producerPolicy
	return &this
}

// NewV1ExtranetPublicVifIdPutRequestWithDefaults instantiates a new V1ExtranetPublicVifIdPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetPublicVifIdPutRequestWithDefaults() *V1ExtranetPublicVifIdPutRequest {
	this := V1ExtranetPublicVifIdPutRequest{}
	return &this
}

// GetConsumerPolicy returns the ConsumerPolicy field value if set, zero value otherwise.
func (o *V1ExtranetPublicVifIdPutRequest) GetConsumerPolicy() ManaV2PublicVifConsumerPolicy {
	if o == nil || IsNil(o.ConsumerPolicy) {
		var ret ManaV2PublicVifConsumerPolicy
		return ret
	}
	return *o.ConsumerPolicy
}

// GetConsumerPolicyOk returns a tuple with the ConsumerPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ExtranetPublicVifIdPutRequest) GetConsumerPolicyOk() (*ManaV2PublicVifConsumerPolicy, bool) {
	if o == nil || IsNil(o.ConsumerPolicy) {
		return nil, false
	}
	return o.ConsumerPolicy, true
}

// HasConsumerPolicy returns a boolean if a field has been set.
func (o *V1ExtranetPublicVifIdPutRequest) HasConsumerPolicy() bool {
	if o != nil && !IsNil(o.ConsumerPolicy) {
		return true
	}

	return false
}

// SetConsumerPolicy gets a reference to the given ManaV2PublicVifConsumerPolicy and assigns it to the ConsumerPolicy field.
func (o *V1ExtranetPublicVifIdPutRequest) SetConsumerPolicy(v ManaV2PublicVifConsumerPolicy) {
	o.ConsumerPolicy = &v
}

// GetProducerPolicy returns the ProducerPolicy field value
func (o *V1ExtranetPublicVifIdPutRequest) GetProducerPolicy() ManaV2PublicVifProducerPolicy {
	if o == nil {
		var ret ManaV2PublicVifProducerPolicy
		return ret
	}

	return o.ProducerPolicy
}

// GetProducerPolicyOk returns a tuple with the ProducerPolicy field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetPublicVifIdPutRequest) GetProducerPolicyOk() (*ManaV2PublicVifProducerPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProducerPolicy, true
}

// SetProducerPolicy sets field value
func (o *V1ExtranetPublicVifIdPutRequest) SetProducerPolicy(v ManaV2PublicVifProducerPolicy) {
	o.ProducerPolicy = v
}

func (o V1ExtranetPublicVifIdPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetPublicVifIdPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConsumerPolicy) {
		toSerialize["consumerPolicy"] = o.ConsumerPolicy
	}
	toSerialize["producerPolicy"] = o.ProducerPolicy
	return toSerialize, nil
}

func (o *V1ExtranetPublicVifIdPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"producerPolicy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1ExtranetPublicVifIdPutRequest := _V1ExtranetPublicVifIdPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1ExtranetPublicVifIdPutRequest)

	if err != nil {
		return err
	}

	*o = V1ExtranetPublicVifIdPutRequest(varV1ExtranetPublicVifIdPutRequest)

	return err
}

type NullableV1ExtranetPublicVifIdPutRequest struct {
	value *V1ExtranetPublicVifIdPutRequest
	isSet bool
}

func (v NullableV1ExtranetPublicVifIdPutRequest) Get() *V1ExtranetPublicVifIdPutRequest {
	return v.value
}

func (v *NullableV1ExtranetPublicVifIdPutRequest) Set(val *V1ExtranetPublicVifIdPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetPublicVifIdPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetPublicVifIdPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetPublicVifIdPutRequest(val *V1ExtranetPublicVifIdPutRequest) *NullableV1ExtranetPublicVifIdPutRequest {
	return &NullableV1ExtranetPublicVifIdPutRequest{value: val, isSet: true}
}

func (v NullableV1ExtranetPublicVifIdPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetPublicVifIdPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


