/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2LanSegmentPublicInterfacesLists type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2LanSegmentPublicInterfacesLists{}

// ManaV2LanSegmentPublicInterfacesLists struct for ManaV2LanSegmentPublicInterfacesLists
type ManaV2LanSegmentPublicInterfacesLists struct {
	PrivateInterfaces []ManaV2LanSegmentPublicInterfaceEntry `json:"privateInterfaces,omitempty"`
	PublicInterfaces []ManaV2LanSegmentPublicInterfaceEntry `json:"publicInterfaces,omitempty"`
}

// NewManaV2LanSegmentPublicInterfacesLists instantiates a new ManaV2LanSegmentPublicInterfacesLists object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2LanSegmentPublicInterfacesLists() *ManaV2LanSegmentPublicInterfacesLists {
	this := ManaV2LanSegmentPublicInterfacesLists{}
	return &this
}

// NewManaV2LanSegmentPublicInterfacesListsWithDefaults instantiates a new ManaV2LanSegmentPublicInterfacesLists object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2LanSegmentPublicInterfacesListsWithDefaults() *ManaV2LanSegmentPublicInterfacesLists {
	this := ManaV2LanSegmentPublicInterfacesLists{}
	return &this
}

// GetPrivateInterfaces returns the PrivateInterfaces field value if set, zero value otherwise.
func (o *ManaV2LanSegmentPublicInterfacesLists) GetPrivateInterfaces() []ManaV2LanSegmentPublicInterfaceEntry {
	if o == nil || IsNil(o.PrivateInterfaces) {
		var ret []ManaV2LanSegmentPublicInterfaceEntry
		return ret
	}
	return o.PrivateInterfaces
}

// GetPrivateInterfacesOk returns a tuple with the PrivateInterfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2LanSegmentPublicInterfacesLists) GetPrivateInterfacesOk() ([]ManaV2LanSegmentPublicInterfaceEntry, bool) {
	if o == nil || IsNil(o.PrivateInterfaces) {
		return nil, false
	}
	return o.PrivateInterfaces, true
}

// HasPrivateInterfaces returns a boolean if a field has been set.
func (o *ManaV2LanSegmentPublicInterfacesLists) HasPrivateInterfaces() bool {
	if o != nil && !IsNil(o.PrivateInterfaces) {
		return true
	}

	return false
}

// SetPrivateInterfaces gets a reference to the given []ManaV2LanSegmentPublicInterfaceEntry and assigns it to the PrivateInterfaces field.
func (o *ManaV2LanSegmentPublicInterfacesLists) SetPrivateInterfaces(v []ManaV2LanSegmentPublicInterfaceEntry) {
	o.PrivateInterfaces = v
}

// GetPublicInterfaces returns the PublicInterfaces field value if set, zero value otherwise.
func (o *ManaV2LanSegmentPublicInterfacesLists) GetPublicInterfaces() []ManaV2LanSegmentPublicInterfaceEntry {
	if o == nil || IsNil(o.PublicInterfaces) {
		var ret []ManaV2LanSegmentPublicInterfaceEntry
		return ret
	}
	return o.PublicInterfaces
}

// GetPublicInterfacesOk returns a tuple with the PublicInterfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2LanSegmentPublicInterfacesLists) GetPublicInterfacesOk() ([]ManaV2LanSegmentPublicInterfaceEntry, bool) {
	if o == nil || IsNil(o.PublicInterfaces) {
		return nil, false
	}
	return o.PublicInterfaces, true
}

// HasPublicInterfaces returns a boolean if a field has been set.
func (o *ManaV2LanSegmentPublicInterfacesLists) HasPublicInterfaces() bool {
	if o != nil && !IsNil(o.PublicInterfaces) {
		return true
	}

	return false
}

// SetPublicInterfaces gets a reference to the given []ManaV2LanSegmentPublicInterfaceEntry and assigns it to the PublicInterfaces field.
func (o *ManaV2LanSegmentPublicInterfacesLists) SetPublicInterfaces(v []ManaV2LanSegmentPublicInterfaceEntry) {
	o.PublicInterfaces = v
}

func (o ManaV2LanSegmentPublicInterfacesLists) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2LanSegmentPublicInterfacesLists) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PrivateInterfaces) {
		toSerialize["privateInterfaces"] = o.PrivateInterfaces
	}
	if !IsNil(o.PublicInterfaces) {
		toSerialize["publicInterfaces"] = o.PublicInterfaces
	}
	return toSerialize, nil
}

type NullableManaV2LanSegmentPublicInterfacesLists struct {
	value *ManaV2LanSegmentPublicInterfacesLists
	isSet bool
}

func (v NullableManaV2LanSegmentPublicInterfacesLists) Get() *ManaV2LanSegmentPublicInterfacesLists {
	return v.value
}

func (v *NullableManaV2LanSegmentPublicInterfacesLists) Set(val *ManaV2LanSegmentPublicInterfacesLists) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2LanSegmentPublicInterfacesLists) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2LanSegmentPublicInterfacesLists) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2LanSegmentPublicInterfacesLists(val *ManaV2LanSegmentPublicInterfacesLists) *NullableManaV2LanSegmentPublicInterfacesLists {
	return &NullableManaV2LanSegmentPublicInterfacesLists{value: val, isSet: true}
}

func (v NullableManaV2LanSegmentPublicInterfacesLists) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2LanSegmentPublicInterfacesLists) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


