/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the ManaV2PublicVifConsumerLanSegmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManaV2PublicVifConsumerLanSegmentResponse{}

// ManaV2PublicVifConsumerLanSegmentResponse struct for ManaV2PublicVifConsumerLanSegmentResponse
type ManaV2PublicVifConsumerLanSegmentResponse struct {
	AllowedPrefixes []string `json:"allowedPrefixes,omitempty"`
	OutboundSecurityRules []ManaV2SecurityPolicyRule `json:"outboundSecurityRules,omitempty"`
	// LAN segment ID for the service
	ServiceLanSegment *int64 `json:"serviceLanSegment,omitempty"`
	TrafficRules []ManaV2TrafficPolicyRule `json:"trafficRules,omitempty"`
}

// NewManaV2PublicVifConsumerLanSegmentResponse instantiates a new ManaV2PublicVifConsumerLanSegmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManaV2PublicVifConsumerLanSegmentResponse() *ManaV2PublicVifConsumerLanSegmentResponse {
	this := ManaV2PublicVifConsumerLanSegmentResponse{}
	return &this
}

// NewManaV2PublicVifConsumerLanSegmentResponseWithDefaults instantiates a new ManaV2PublicVifConsumerLanSegmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManaV2PublicVifConsumerLanSegmentResponseWithDefaults() *ManaV2PublicVifConsumerLanSegmentResponse {
	this := ManaV2PublicVifConsumerLanSegmentResponse{}
	return &this
}

// GetAllowedPrefixes returns the AllowedPrefixes field value if set, zero value otherwise.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) GetAllowedPrefixes() []string {
	if o == nil || IsNil(o.AllowedPrefixes) {
		var ret []string
		return ret
	}
	return o.AllowedPrefixes
}

// GetAllowedPrefixesOk returns a tuple with the AllowedPrefixes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) GetAllowedPrefixesOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedPrefixes) {
		return nil, false
	}
	return o.AllowedPrefixes, true
}

// HasAllowedPrefixes returns a boolean if a field has been set.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) HasAllowedPrefixes() bool {
	if o != nil && !IsNil(o.AllowedPrefixes) {
		return true
	}

	return false
}

// SetAllowedPrefixes gets a reference to the given []string and assigns it to the AllowedPrefixes field.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) SetAllowedPrefixes(v []string) {
	o.AllowedPrefixes = v
}

// GetOutboundSecurityRules returns the OutboundSecurityRules field value if set, zero value otherwise.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) GetOutboundSecurityRules() []ManaV2SecurityPolicyRule {
	if o == nil || IsNil(o.OutboundSecurityRules) {
		var ret []ManaV2SecurityPolicyRule
		return ret
	}
	return o.OutboundSecurityRules
}

// GetOutboundSecurityRulesOk returns a tuple with the OutboundSecurityRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) GetOutboundSecurityRulesOk() ([]ManaV2SecurityPolicyRule, bool) {
	if o == nil || IsNil(o.OutboundSecurityRules) {
		return nil, false
	}
	return o.OutboundSecurityRules, true
}

// HasOutboundSecurityRules returns a boolean if a field has been set.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) HasOutboundSecurityRules() bool {
	if o != nil && !IsNil(o.OutboundSecurityRules) {
		return true
	}

	return false
}

// SetOutboundSecurityRules gets a reference to the given []ManaV2SecurityPolicyRule and assigns it to the OutboundSecurityRules field.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) SetOutboundSecurityRules(v []ManaV2SecurityPolicyRule) {
	o.OutboundSecurityRules = v
}

// GetServiceLanSegment returns the ServiceLanSegment field value if set, zero value otherwise.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) GetServiceLanSegment() int64 {
	if o == nil || IsNil(o.ServiceLanSegment) {
		var ret int64
		return ret
	}
	return *o.ServiceLanSegment
}

// GetServiceLanSegmentOk returns a tuple with the ServiceLanSegment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) GetServiceLanSegmentOk() (*int64, bool) {
	if o == nil || IsNil(o.ServiceLanSegment) {
		return nil, false
	}
	return o.ServiceLanSegment, true
}

// HasServiceLanSegment returns a boolean if a field has been set.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) HasServiceLanSegment() bool {
	if o != nil && !IsNil(o.ServiceLanSegment) {
		return true
	}

	return false
}

// SetServiceLanSegment gets a reference to the given int64 and assigns it to the ServiceLanSegment field.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) SetServiceLanSegment(v int64) {
	o.ServiceLanSegment = &v
}

// GetTrafficRules returns the TrafficRules field value if set, zero value otherwise.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) GetTrafficRules() []ManaV2TrafficPolicyRule {
	if o == nil || IsNil(o.TrafficRules) {
		var ret []ManaV2TrafficPolicyRule
		return ret
	}
	return o.TrafficRules
}

// GetTrafficRulesOk returns a tuple with the TrafficRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) GetTrafficRulesOk() ([]ManaV2TrafficPolicyRule, bool) {
	if o == nil || IsNil(o.TrafficRules) {
		return nil, false
	}
	return o.TrafficRules, true
}

// HasTrafficRules returns a boolean if a field has been set.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) HasTrafficRules() bool {
	if o != nil && !IsNil(o.TrafficRules) {
		return true
	}

	return false
}

// SetTrafficRules gets a reference to the given []ManaV2TrafficPolicyRule and assigns it to the TrafficRules field.
func (o *ManaV2PublicVifConsumerLanSegmentResponse) SetTrafficRules(v []ManaV2TrafficPolicyRule) {
	o.TrafficRules = v
}

func (o ManaV2PublicVifConsumerLanSegmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManaV2PublicVifConsumerLanSegmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllowedPrefixes) {
		toSerialize["allowedPrefixes"] = o.AllowedPrefixes
	}
	if !IsNil(o.OutboundSecurityRules) {
		toSerialize["outboundSecurityRules"] = o.OutboundSecurityRules
	}
	if !IsNil(o.ServiceLanSegment) {
		toSerialize["serviceLanSegment"] = o.ServiceLanSegment
	}
	if !IsNil(o.TrafficRules) {
		toSerialize["trafficRules"] = o.TrafficRules
	}
	return toSerialize, nil
}

type NullableManaV2PublicVifConsumerLanSegmentResponse struct {
	value *ManaV2PublicVifConsumerLanSegmentResponse
	isSet bool
}

func (v NullableManaV2PublicVifConsumerLanSegmentResponse) Get() *ManaV2PublicVifConsumerLanSegmentResponse {
	return v.value
}

func (v *NullableManaV2PublicVifConsumerLanSegmentResponse) Set(val *ManaV2PublicVifConsumerLanSegmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableManaV2PublicVifConsumerLanSegmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableManaV2PublicVifConsumerLanSegmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManaV2PublicVifConsumerLanSegmentResponse(val *ManaV2PublicVifConsumerLanSegmentResponse) *NullableManaV2PublicVifConsumerLanSegmentResponse {
	return &NullableManaV2PublicVifConsumerLanSegmentResponse{value: val, isSet: true}
}

func (v NullableManaV2PublicVifConsumerLanSegmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManaV2PublicVifConsumerLanSegmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


