/*
Graphiant APIs

**To use the APIs:**  1) Login using `/api/v1/auth/login`   2) Copy the value of \"token\" in the response   3) Click the \"Authorize\" button   4) In the \"Value\" text field enter: `Bearer <your token>`   5) Click \"Authorize\"   6) All requests are now authorized.  **Token valid for 2 hours. If expired:**   - Login again, click \"Authorize\", paste new token.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1DevicesDeviceIdStagedConfigCompareGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1DevicesDeviceIdStagedConfigCompareGet200Response{}

// V1DevicesDeviceIdStagedConfigCompareGet200Response struct for V1DevicesDeviceIdStagedConfigCompareGet200Response
type V1DevicesDeviceIdStagedConfigCompareGet200Response struct {
	Diff *string `json:"diff,omitempty"`
}

// NewV1DevicesDeviceIdStagedConfigCompareGet200Response instantiates a new V1DevicesDeviceIdStagedConfigCompareGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1DevicesDeviceIdStagedConfigCompareGet200Response() *V1DevicesDeviceIdStagedConfigCompareGet200Response {
	this := V1DevicesDeviceIdStagedConfigCompareGet200Response{}
	return &this
}

// NewV1DevicesDeviceIdStagedConfigCompareGet200ResponseWithDefaults instantiates a new V1DevicesDeviceIdStagedConfigCompareGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1DevicesDeviceIdStagedConfigCompareGet200ResponseWithDefaults() *V1DevicesDeviceIdStagedConfigCompareGet200Response {
	this := V1DevicesDeviceIdStagedConfigCompareGet200Response{}
	return &this
}

// GetDiff returns the Diff field value if set, zero value otherwise.
func (o *V1DevicesDeviceIdStagedConfigCompareGet200Response) GetDiff() string {
	if o == nil || IsNil(o.Diff) {
		var ret string
		return ret
	}
	return *o.Diff
}

// GetDiffOk returns a tuple with the Diff field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1DevicesDeviceIdStagedConfigCompareGet200Response) GetDiffOk() (*string, bool) {
	if o == nil || IsNil(o.Diff) {
		return nil, false
	}
	return o.Diff, true
}

// HasDiff returns a boolean if a field has been set.
func (o *V1DevicesDeviceIdStagedConfigCompareGet200Response) HasDiff() bool {
	if o != nil && !IsNil(o.Diff) {
		return true
	}

	return false
}

// SetDiff gets a reference to the given string and assigns it to the Diff field.
func (o *V1DevicesDeviceIdStagedConfigCompareGet200Response) SetDiff(v string) {
	o.Diff = &v
}

func (o V1DevicesDeviceIdStagedConfigCompareGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1DevicesDeviceIdStagedConfigCompareGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Diff) {
		toSerialize["diff"] = o.Diff
	}
	return toSerialize, nil
}

type NullableV1DevicesDeviceIdStagedConfigCompareGet200Response struct {
	value *V1DevicesDeviceIdStagedConfigCompareGet200Response
	isSet bool
}

func (v NullableV1DevicesDeviceIdStagedConfigCompareGet200Response) Get() *V1DevicesDeviceIdStagedConfigCompareGet200Response {
	return v.value
}

func (v *NullableV1DevicesDeviceIdStagedConfigCompareGet200Response) Set(val *V1DevicesDeviceIdStagedConfigCompareGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1DevicesDeviceIdStagedConfigCompareGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1DevicesDeviceIdStagedConfigCompareGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1DevicesDeviceIdStagedConfigCompareGet200Response(val *V1DevicesDeviceIdStagedConfigCompareGet200Response) *NullableV1DevicesDeviceIdStagedConfigCompareGet200Response {
	return &NullableV1DevicesDeviceIdStagedConfigCompareGet200Response{value: val, isSet: true}
}

func (v NullableV1DevicesDeviceIdStagedConfigCompareGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1DevicesDeviceIdStagedConfigCompareGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


